export type Values=Record<string,number>;
export type Control={key:string;label:string;min:number;max:number;step:number;initial:number;unit?:string;options?:string[]};
export type Activity={slug:string;tag:string;mission:string;hint:string;science:string;controls:Control[];run?:boolean};
const r=(key:string,label:string,min:number,max:number,step:number,initial:number,unit=""):Control=>({key,label,min,max,step,initial,unit});
const s=(key:string,label:string,options:string[],initial=0):Control=>({key,label,min:0,max:options.length-1,step:1,initial,options});
export const activities:Activity[]=[
 {slug:"vector-lab",tag:"VECTOR NAVIGATOR",mission:"Combine vectors A and B to make resultant R = ⟨6, 8⟩ with magnitude 10.",hint:"Components add independently. One solution is A = ⟨2, 3⟩ and B = ⟨4, 5⟩.",science:"Vectors are represented by Cartesian components. R = A + B, magnitude |R| = √(Rx²+Ry²), and direction is atan2(Ry,Rx). The graph uses equal x/y scale.",controls:[r("ax","Vector A · x",-10,10,1,2),r("ay","Vector A · y",-10,10,1,3),r("bx","Vector B · x",-10,10,1,1),r("by","Vector B · y",-10,10,1,1)]},
 {slug:"function-explorer",tag:"ROOT DETECTIVE",mission:"Build an upward-opening quadratic whose roots are −3 and 2.",hint:"(x + 3)(x − 2) = x² + x − 6, so try a = 1, b = 1, c = −6.",science:"For f(x)=ax²+bx+c, real roots use the quadratic formula and the vertex is at x=−b/(2a). Changing a controls opening and vertical stretch; b and c shift the vertex and intercepts.",controls:[r("a","Coefficient a",-3,3,.25,1),r("b","Coefficient b",-8,8,.25,0),r("c","Coefficient c",-10,10,.5,0)]},
 {slug:"geometry-slice-3d",tag:"SECTION SCANNER",mission:"Create and record a circle, square, and triangle by slicing different solids.",hint:"Horizontal cylinder → circle. Horizontal cube → square. Vertical center slice through a cone → triangle.",science:"The cross-section is the intersection of a plane and solid. The 3D model clips the solid at the movable plane; the section outline is a geometric teaching overlay. The named section assumes a centered slice and ideal solids.",controls:[s("solid","Solid",["Cylinder","Cube","Cone","Sphere"]),s("plane","Slice orientation",["Horizontal","Vertical"]),r("offset","Plane offset",-.7,.7,.05,0)]},
 {slug:"pythagorean-puzzle",tag:"RIGHT-TRIANGLE QUEST",mission:"Solve the missing hypotenuse for all three right triangles.",hint:"Use c = √(a²+b²). The puzzles are 3–4–5, 5–12–13, and 8–15–17 triangles.",science:"For a right triangle, the area relationship between squares on its sides is a²+b²=c². The exercise checks the hypotenuse, not arbitrary triangle side lengths.",controls:[s("puzzle","Triangle",["Puzzle A","Puzzle B","Puzzle C"]),r("answer","Your hypotenuse",0,25,.1,7,"units")]},
 {slug:"unit-circle-challenge",tag:"ANGLE ORBIT",mission:"Identify the coordinates at 0°, 90°, 180°, and 270°. Record all four.",hint:"A unit-circle point is (cos θ, sin θ). Start at (1,0) and move counterclockwise.",science:"On a radius-one circle, x=cos θ and y=sin θ. Degrees are converted to radians internally; coordinate choices focus on the four quadrantal angles.",controls:[r("angle","Angle",0,360,15,45,"°"),s("answer","Coordinate",["Choose coordinates","(1, 0)","(0, 1)","(−1, 0)","(0, −1)"])]},
 {slug:"quadratic-transformation",tag:"PARABOLA MATCH",mission:"Match all three target parabolas using vertex form y = a(x − h)² + k.",hint:"Read the vertex (h,k), then use the opening direction and width to determine a.",science:"Vertex form exposes translation and vertical scale: h shifts horizontally, k vertically, |a| stretches/compresses, and negative a reflects across the x-axis.",controls:[s("target","Target graph",["Target A","Target B","Target C"]),r("a","Vertical scale a",-3,3,.25,1),r("h","Horizontal shift h",-5,5,.5,0),r("k","Vertical shift k",-5,5,.5,0)]},
 {slug:"slope-intercept-challenge",tag:"LINE MATCH",mission:"Match all three target lines using y = mx + b.",hint:"Slope is rise/run; b is the y-intercept. Use the highlighted intercept and second point.",science:"In y=mx+b, m is the constant rate of change and b is the output at x=0. Two distinct points determine one nonvertical line.",controls:[s("target","Target line",["Target A","Target B","Target C"]),r("m","Slope m",-5,5,.25,0),r("b","Intercept b",-8,8,.5,0)]},
 {slug:"geometry-transformation",tag:"TRANSFORMATION LAB",mission:"Complete translation, rotation, reflection, and dilation challenges. Record all four.",hint:"Translation: ⟨4,−2⟩. Rotation: 90° counterclockwise. Reflection: y-axis. Dilation: scale factor 2.",science:"Coordinates are transformed about the origin. Translation preserves lengths and angles; rotation and reflection preserve congruence; dilation preserves angles but scales lengths and area.",controls:[s("challenge","Transformation",["Translation","Rotation","Reflection","Dilation"]),r("tx","Horizontal translation",-6,6,1,0),r("ty","Vertical translation",-6,6,1,0),r("angle","Rotation",-180,180,15,0,"°"),s("axis","Reflection axis",["x-axis","y-axis"]),r("scale","Dilation factor",.5,3,.25,1)]},
 {slug:"probability-experiment",tag:"CHANCE LAB",mission:"Run at least 500 trials for coin, die, and spinner events; get within 8 percentage points of theory for each.",hint:"Increase trials to 1,000. Each experiment uses a reproducible seed so evidence can be checked.",science:"Pseudo-random trials estimate P(heads)=1/2, P(die≥5)=1/3, and P(blue spinner)=1/4. The law of large numbers concerns long-run convergence, not a guarantee that every finite sample is close.",run:true,controls:[s("experiment","Random event",["Coin: heads","Die: 5 or 6","Spinner: blue quarter"]),r("trials","Number of trials",10,1000,10,100),r("seed","Experiment seed",1,99,1,42)]},
 {slug:"derivative-tangent",tag:"TANGENT TRACKER",mission:"Match the tangent slope for x², x³, and sin(x). Record all three.",hint:"Derivatives: x² → 2x; x³ → 3x²; sin(x) → cos(x). Match your slope guess at the selected x.",science:"The derivative is the limit of secant slopes and gives instantaneous rate of change. The graph shows the exact analytic tangent; the challenge compares your slope estimate with it.",controls:[s("function","Function",["f(x) = x²","f(x) = x³","f(x) = sin(x)"]),r("x","Point x",-3,3,.1,1),r("guess","Your slope",-10,15,.1,1)]},
 {slug:"area-under-curve",tag:"INTEGRAL BUILDER",mission:"Use midpoint rectangles to approximate all three definite integrals within 0.03. Record all three.",hint:"Choose midpoint sums and at least 40 rectangles. The problems are ∫₀³x²dx, ∫₀πsin(x)dx, and ∫₀⁴(2+x)dx.",science:"A Riemann sum adds rectangle areas f(sample)Δx. Left, midpoint and right sampling converge under suitable conditions as rectangle width shrinks. Exact values shown are analytic definite integrals.",controls:[s("problem","Integral",["∫₀³ x² dx","∫₀π sin(x) dx","∫₀⁴ (2+x) dx"]),r("rectangles","Rectangles",2,50,1,10),s("method","Sample point",["Left","Midpoint","Right"])]},
 {slug:"matrix-transformation",tag:"MATRIX ENGINE",mission:"Match a 90° rotation, a horizontal shear, and a y-axis reflection. Record all three matrices.",hint:"Rotation: [[0,−1],[1,0]]. Shear: [[1,1],[0,1]]. y-axis reflection: [[−1,0],[0,1]].",science:"A 2×2 matrix sends (x,y) to (ax+by,cx+dy). Its columns are transformed basis vectors. The determinant scales signed area; determinant zero collapses the plane to a line or point.",controls:[s("target","Target transform",["Rotate 90°","Horizontal shear","Reflect across y-axis"]),r("a","Matrix a",-2,2,.25,1),r("b","Matrix b",-2,2,.25,0),r("c","Matrix c",-2,2,.25,0),r("d","Matrix d",-2,2,.25,1)]},
];
export const initialValues=(activity:Activity):Values=>Object.fromEntries(activity.controls.map(c=>[c.key,c.initial]));
export const clamp=(n:number,a=0,b=1)=>Math.max(a,Math.min(b,n));
export function vector(v:Values){const x=v.ax+v.bx,y=v.ay+v.by;return{x,y,magnitude:Math.hypot(x,y),angle:Math.atan2(y,x)*180/Math.PI};}
export function quadratic(v:Values){const disc=v.b*v.b-4*v.a*v.c,roots=v.a!==0&&disc>=0?[(-v.b-Math.sqrt(disc))/(2*v.a),(-v.b+Math.sqrt(disc))/(2*v.a)].sort((a,b)=>a-b):[];return{disc,roots,vertexX:v.a?-v.b/(2*v.a):Infinity,vertexY:v.a?v.c-v.b*v.b/(4*v.a):Infinity};}
export function sliceShape(v:Values){if(v.solid===3)return"Circle";if(v.solid===0)return v.plane===0?"Circle":"Rectangle";if(v.solid===1)return v.plane===0?"Square":"Rectangle";return v.plane===0?"Circle":"Triangle";}
export const triangles=[[3,4,5],[5,12,13],[8,15,17]] as const;
export const quadraticTargets=[{a:1,h:2,k:-3},{a:-.5,h:-2,k:2},{a:2,h:1,k:1}];
export const lineTargets=[{m:2,b:-3},{m:-1.5,b:4},{m:.5,b:-2}];
export const baseShape:[number,number][]=[[-1,-1],[1,-1],[.4,1.2]];
export function transformShape(v:Values){return baseShape.map(([x,y]):[number,number]=>{switch(v.challenge){case 0:return[x+v.tx,y+v.ty];case 1:{const a=v.angle*Math.PI/180;return[x*Math.cos(a)-y*Math.sin(a),x*Math.sin(a)+y*Math.cos(a)];}case 2:return v.axis?[ -x,y]:[x,-y];default:return[x*v.scale,y*v.scale];}});}
function random(seed:number){let state=(seed|0)>>>0;return()=>{state=(state*1664525+1013904223)>>>0;return state/4294967296;};}
export function probability(v:Values){const rand=random(v.seed+v.experiment*1009);let success=0;for(let i=0;i<v.trials;i++){const x=rand();if(v.experiment===0?x<.5:v.experiment===1?Math.floor(x*6)>=4:x<.25)success++;}const theory=[.5,1/3,.25][v.experiment];return{success,experimental:success/v.trials,theory,error:Math.abs(success/v.trials-theory)};}
export function functionValue(kind:number,x:number){return kind===0?x*x:kind===1?x*x*x:Math.sin(x);}
export function derivative(kind:number,x:number){return kind===0?2*x:kind===1?3*x*x:Math.cos(x);}
export const integrals=[{a:0,b:3,exact:9,fn:(x:number)=>x*x},{a:0,b:Math.PI,exact:2,fn:(x:number)=>Math.sin(x)},{a:0,b:4,exact:16,fn:(x:number)=>2+x}];
export function riemann(v:Values){const p=integrals[v.problem],dx=(p.b-p.a)/v.rectangles,offset=[0,.5,1][v.method];let sum=0;const bars=[] as {x:number;width:number;height:number}[];for(let i=0;i<v.rectangles;i++){const x=p.a+(i+offset)*dx,height=p.fn(x);sum+=height*dx;bars.push({x:p.a+i*dx,width:dx,height});}return{...p,dx,sum,error:Math.abs(sum-p.exact),bars};}
export function matrix(v:Values){return{det:v.a*v.d-v.b*v.c,apply:([x,y]:[number,number]):[number,number]=>[v.a*x+v.b*y,v.c*x+v.d*y]};}
const close=(a:number,b:number,tolerance=.001)=>Math.abs(a-b)<=tolerance;
export function mission(slug:string,v:Values,ran=false){let ok=false,step="done",required=1,text="Adjust the model, then record your solution.";switch(slug){
 case"vector-lab":{const q=vector(v);ok=close(q.x,6)&&close(q.y,8);text=`Resultant ⟨${q.x}, ${q.y}⟩ · magnitude ${q.magnitude.toFixed(2)}. Target ⟨6, 8⟩.`;break;}
 case"function-explorer":{const q=quadratic(v);ok=v.a>0&&q.roots.length===2&&close(q.roots[0],-3,.01)&&close(q.roots[1],2,.01);text=q.roots.length?`Roots ${q.roots.map(x=>x.toFixed(2)).join(" and ")}. Target −3 and 2, opening upward.`:"No two real roots at these coefficients.";break;}
 case"geometry-slice-3d":{const shape=sliceShape(v);ok=["Circle","Square","Triangle"].includes(shape)&&Math.abs(v.offset)<.1;step=shape;required=3;text=`Centered ${["horizontal","vertical"][v.plane]} slice of the ${["cylinder","cube","cone","sphere"][v.solid]}: ${shape}.`;break;}
 case"pythagorean-puzzle":{const tri=triangles[v.puzzle];ok=close(v.answer,tri[2],.05);step=String(v.puzzle);required=3;text=`√(${tri[0]}² + ${tri[1]}²) = ${tri[2]}.`;break;}
 case"unit-circle-challenge":{const a=((v.angle%360)+360)%360,index=[0,90,180,270].indexOf(a);ok=index>=0&&v.answer===index+1;step=String(index);required=4;text=ok?`${a}° corresponds to ${["(1, 0)","(0, 1)","(−1, 0)","(0, −1)"][index]}.`:"Choose a quadrantal angle and match (cos θ, sin θ).";break;}
 case"quadratic-transformation":{const q=quadraticTargets[v.target];ok=close(v.a,q.a)&&close(v.h,q.h)&&close(v.k,q.k);step=String(v.target);required=3;text=`Your vertex (${v.h}, ${v.k}), scale ${v.a}. Match the target's vertex, opening, and width.`;break;}
 case"slope-intercept-challenge":{const q=lineTargets[v.target];ok=close(v.m,q.m)&&close(v.b,q.b);step=String(v.target);required=3;text=`Your line y = ${v.m}x ${v.b<0?"−":"+"} ${Math.abs(v.b)}. Match the highlighted target.`;break;}
 case"geometry-transformation":{ok=v.challenge===0?close(v.tx,4)&&close(v.ty,-2):v.challenge===1?close(v.angle,90):v.challenge===2?v.axis===1:close(v.scale,2);step=String(v.challenge);required=4;text=ok?`${["Translation ⟨4,−2⟩","90° counterclockwise rotation","Reflection across y-axis","Dilation by 2"][v.challenge]} completed.`:"The blue image does not overlap the target yet.";break;}
 case"probability-experiment":{const p=probability(v);ok=ran&&v.trials>=500&&p.error<=.08;step=String(v.experiment);required=3;text=`Experimental ${(p.experimental*100).toFixed(1)}% · theoretical ${(p.theory*100).toFixed(1)}% · error ${(p.error*100).toFixed(1)} points.`;break;}
 case"derivative-tangent":{const d=derivative(v.function,v.x);ok=close(v.guess,d,.1);step=String(v.function);required=3;text=`At x=${v.x.toFixed(1)}, tangent slope ${d.toFixed(2)}; your estimate ${v.guess.toFixed(2)}.`;break;}
 case"area-under-curve":{const q=riemann(v);ok=v.method===1&&v.rectangles>=40&&q.error<=.03;step=String(v.problem);required=3;text=`Midpoint sum ${q.sum.toFixed(4)} · exact ${q.exact.toFixed(4)} · error ${q.error.toFixed(4)}.`;break;}
 case"matrix-transformation":{const q=[[0,-1,1,0],[1,1,0,1],[-1,0,0,1]][v.target];ok=[v.a,v.b,v.c,v.d].every((x,i)=>close(x,q[i]));step=String(v.target);required=3;text=`Matrix [[${v.a}, ${v.b}], [${v.c}, ${v.d}]] · determinant ${matrix(v).det.toFixed(2)}.`;break;}
 }return{ok,step,required,text};}
