export type Values = Record<string, number>;
export type Control = { key:string; label:string; min:number; max:number; step:number; initial:number; unit?:string; options?:string[] };
export type Activity = { slug:string; tag:string; mission:string; hint:string; science:string; controls:Control[]; source:[string,string]; run:true };

const r=(key:string,label:string,min:number,max:number,step:number,initial:number,unit=""):Control=>({key,label,min,max,step,initial,unit});
export const clamp=(n:number,a=0,b=1)=>Math.max(a,Math.min(b,n));
export const initialValues=(activity:Activity):Values=>Object.fromEntries(activity.controls.map(control=>[control.key,control.initial]));

export const activities:Activity[]=[
 {slug:"greenhouse-effect-simulator",tag:"CLIMATE LAB",mission:"Build a low-warming atmosphere: keep modeled equilibrium warming below 1.5°C while CO₂ is at or below 420 ppm.",hint:"Lower greenhouse gases and increase planetary reflectivity slightly. Watch forcing first, then temperature.",science:"A transparent teaching model based on logarithmic CO₂ radiative forcing, a simplified methane term, and an albedo adjustment. Climate feedbacks, aerosols, oceans, spatial variation, and time lags are compressed into one response; this is not a forecast.",run:true,controls:[r("co2","Atmospheric CO₂",280,800,10,560,"ppm"),r("methane","Atmospheric methane",700,2600,50,1900,"ppb"),r("albedo","Planetary albedo",.26,.34,.01,.30,"fraction")],source:["NASA: causes of climate change","https://science.nasa.gov/climate-change/causes/"]},
 {slug:"carbon-cycle-simulator",tag:"CARBON BUDGET",mission:"Reach net zero or net removal and hold atmospheric CO₂ below 430 ppm after 30 modeled years.",hint:"Reduce annual emissions and strengthen forest, ocean, and engineered removal. The sinks must equal or exceed emissions.",science:"One-box atmospheric carbon budget. One ppm CO₂ is approximated as 7.8 GtCO₂, and annual source/sink rates are held constant. Real sinks respond nonlinearly and can weaken; this model is for mass-balance reasoning, not prediction.",run:true,controls:[r("emissions","Annual emissions",10,50,1,38,"GtCO₂/yr"),r("forest","Forest uptake",0,18,1,7,"GtCO₂/yr"),r("ocean","Ocean uptake",0,14,1,8,"GtCO₂/yr"),r("removal","Additional removal",0,25,1,2,"GtCO₂/yr")],source:["NOAA: the carbon cycle","https://www.noaa.gov/education/resource-collections/climate/carbon-cycle"]},
 {slug:"sea-level-rise-simulator",tag:"COAST WATCH",mission:"Create an adaptation case with less than 0.35 m of modeled sea-level rise over 80 years.",hint:"Bring warming below about 1.5°C. Thermal expansion and land-ice melt both increase with warming.",science:"Scenario model using illustrative warming-dependent rates for thermal expansion and land-ice contribution. Local subsidence, currents, gravitational effects, storms, and nonlinear ice-sheet change are omitted. Never use it for engineering or evacuation planning.",run:true,controls:[r("warming","Global warming",.5,4.5,.1,3,"°C"),r("years","Time horizon",20,120,5,80,"years"),r("subsidence","Local land subsidence",0,5,.5,1,"mm/yr")],source:["NOAA: sea level rise","https://oceanservice.noaa.gov/hazards/sealevelrise/sealevelrise-tech-report.html"]},
 {slug:"ocean-acidification-simulator",tag:"OCEAN CHEMISTRY",mission:"Protect shell-building organisms: keep modeled surface-ocean pH at or above 8.00 and shell health at or above 70%.",hint:"Lower atmospheric CO₂ and nutrient pollution. Warming adds a smaller stress in this teaching model.",science:"Empirical classroom relationship showing that added atmospheric CO₂ lowers ocean pH and carbonate availability. It does not solve the full marine carbonate system, alkalinity, salinity, circulation, or species-specific biology.",run:true,controls:[r("co2","Atmospheric CO₂",280,900,10,620,"ppm"),r("warming","Ocean warming",0,4,.1,2,"°C"),r("nutrients","Nutrient pollution",0,100,5,55,"index")],source:["NOAA: ocean acidification","https://oceanacidification.noaa.gov/what-is-ocean-acidification/"]},
 {slug:"renewable-energy-grid-simulator",tag:"GRID COMMAND",mission:"Power the city with at least 95% reliability, at least 80% clean generation, and no more than 8 tCO₂/h.",hint:"Diversify solar, wind, and hydro, then add storage for the remaining gap. Gas can protect reliability but raises emissions.",science:"Capacity-factor dispatch model for one representative hour. Storage is a limited dispatch resource, gas fills the residual up to installed capacity, and transmission, ramping, weather correlation, energy duration, and market operation are omitted.",run:true,controls:[r("demand","City demand",40,140,5,100,"MW"),r("solar","Solar capacity",0,240,10,80,"MW"),r("wind","Wind capacity",0,200,10,60,"MW"),r("hydro","Hydro capacity",0,80,5,20,"MW"),r("storage","Available storage",0,80,5,10,"MWh"),r("gas","Gas backup capacity",0,80,5,60,"MW")],source:["U.S. DOE: energy storage","https://www.energy.gov/oe/energy-storage"]},
 {slug:"air-pollution-smog-simulator",tag:"CLEAN AIR CONTROL",mission:"Run a clean-air scenario with AQI at or below 50 and both PM₂.₅ and ozone in the good range.",hint:"Cut traffic and industry, then increase wind. Strong inversions trap pollution near the surface.",science:"Screening-level index combining illustrative primary PM₂.₅ emissions and sunlight-driven ozone chemistry. It is not the regulatory EPA AQI calculation or an air-quality forecast; atmospheric chemistry and terrain are greatly simplified.",run:true,controls:[r("traffic","Traffic emissions",0,100,5,75,"index"),r("industry","Industrial emissions",0,100,5,65,"index"),r("wind","Wind speed",0,12,.5,2,"m/s"),r("inversion","Temperature inversion",0,100,5,75,"strength"),r("sunlight","Sunlight",0,100,5,80,"index")],source:["EPA: air quality and climate research","https://www.epa.gov/air-research/air-quality-and-climate-change-research"]},
 {slug:"deforestation-water-cycle-simulator",tag:"WATERSHED LAB",mission:"Restore the watershed: infiltration must exceed 55% and soil loss stay below 5 t/ha per storm.",hint:"Increase forest cover, reduce soil compaction, and test a gentler slope or rainfall event.",science:"Event water-balance model using vegetation, soil compaction, slope, and rainfall intensity to estimate runoff, infiltration, and relative soil loss. Soil type, antecedent moisture, channels, and sediment routing are omitted.",run:true,controls:[r("forest","Forest cover",0,100,5,25,"%"),r("rain","Rainfall intensity",10,100,5,70,"mm/h"),r("slope","Slope",0,35,1,20,"°"),r("compaction","Soil compaction",0,100,5,70,"index")],source:["USGS: water cycle","https://www.usgs.gov/special-topics/water-science-school/science/water-cycle"]},
 {slug:"biodiversity-habitat-fragmentation",tag:"WILDLIFE PLANNER",mission:"Create a viable habitat network with connectivity and population viability both at or above 75%.",hint:"Use fewer large habitat patches, add a wide corridor, and reduce pollution pressure.",science:"Landscape teaching index based on remaining habitat, fragmentation, corridor width, and pollution. It does not represent a particular species, genetics, edge geometry, disease, or demographic randomness.",run:true,controls:[r("habitat","Habitat remaining",10,100,5,45,"%"),r("patches","Number of patches",1,12,1,9,"patches"),r("corridor","Wildlife corridor width",0,100,5,15,"index"),r("pollution","Pollution pressure",0,100,5,55,"index")],source:["USGS: habitat connectivity","https://www.usgs.gov/programs/climate-adaptation-science-centers/science/ecological-connectivity"]},
 {slug:"urban-heat-island-simulator",tag:"COOL CITY LAB",mission:"Cool the neighborhood: keep afternoon heat anomaly below 1.5°C and stormwater runoff below 45%.",hint:"Add tree canopy and permeable ground, then brighten roofs. Trees help both heat and runoff.",science:"Neighborhood-scale response model for shade, evapotranspiration, roof reflectance, and impervious cover. Building geometry, humidity, wind, nighttime heat storage, irrigation, and local climate are omitted.",run:true,controls:[r("trees","Tree canopy",0,60,5,10,"%"),r("coolRoofs","Cool-roof coverage",0,100,5,15,"%"),r("permeable","Permeable ground",0,80,5,10,"%"),r("temperature","Regional hot-day temperature",28,44,1,39,"°C")],source:["EPA: heat islands","https://www.epa.gov/heatislands"]},
 {slug:"climate-resilience-city-builder",tag:"RESILIENCE MISSION",mission:"Keep total investment within 100 points and reduce combined flood, heat, and storm risk below 30/100.",hint:"Spread the budget across wetlands, drainage, shade, barriers, and early warning. One defense cannot solve every hazard.",science:"Multi-hazard decision game with transparent weighted risk-reduction scores and diminishing returns. Costs and risks are normalized classroom points, not monetary estimates or a site-specific adaptation plan.",run:true,controls:[r("hazard","Climate hazard severity",30,100,5,80,"index"),r("wetlands","Wetland restoration",0,40,5,5,"points"),r("drainage","Green drainage",0,40,5,5,"points"),r("shade","Shade and cooling",0,40,5,5,"points"),r("barriers","Flood barriers",0,40,5,5,"points"),r("warning","Early warning",0,40,5,5,"points")],source:["EPA: climate adaptation resource center","https://www.epa.gov/arc-x"]},
];

export function greenhouse(v:Values){const co2=5.35*Math.log(v.co2/280),methane=.036*(Math.sqrt(v.methane)-Math.sqrt(700)),albedo=(.30-v.albedo)*25,forcing=co2+methane+albedo;return{forcing,warming:Math.max(0,forcing*.8),outgoing:240-forcing};}
export function carbon(v:Values,years=30){const net=v.emissions-v.forest-v.ocean-v.removal;return{net,ppm:Math.max(280,420+net*years/7.8),stored:(v.forest+v.ocean+v.removal)*years};}
export function seaLevel(v:Values){const thermal=.9*v.warming,ice=1.8*Math.max(0,v.warming-.3),rate=thermal+ice+v.subsidence;return{thermal:thermal*v.years/1000,ice:ice*v.years/1000,local:v.subsidence*v.years/1000,total:rate*v.years/1000,rate};}
export function acidification(v:Values){const ph=clamp(8.20-.19*Math.log(v.co2/280)-.018*v.warming-.00045*v.nutrients,7.55,8.25),shell=clamp((ph-7.72)/.4*100-v.warming*3,0,100);return{ph,shell,carbonate:clamp(shell*.92,0,100)};}
export function grid(v:Values){const solar=v.solar*.25,wind=v.wind*.40,hydro=v.hydro*.55,clean=solar+wind+hydro,storage=Math.min(v.storage*.8,Math.max(0,v.demand-clean)),gas=Math.min(v.gas,Math.max(0,v.demand-clean-storage)),served=clean+storage+gas;return{solar,wind,hydro,clean,storage,gas,reliability:clamp(served/v.demand)*100,cleanShare:clamp((clean+storage)/Math.max(served,1))*100,emissions:gas*.4,shortfall:Math.max(0,v.demand-served)};}
export function air(v:Values){const trapping=.45+v.inversion/120,dispersion=1+v.wind*.42,pm=(4+(v.traffic*.18+v.industry*.24)*trapping)/dispersion,ozone=25+(v.traffic*.24+v.industry*.13)*(v.sunlight/100)*trapping/(1+v.wind*.16),aqi=Math.max(pm/12*50,ozone/54*50);return{pm,ozone,aqi:Math.min(300,aqi)};}
export function watershed(v:Values){const protection=v.forest/100,compaction=v.compaction/100,slope=v.slope/35,intensity=v.rain/100,runoff=clamp(.08+.52*compaction+.28*slope+.18*intensity-.48*protection),infiltration=clamp(1-runoff-.08)*100,soilLoss=Math.max(0,v.rain*.012*(1+3*slope)*(1+compaction*2)*(1-protection*.85));return{runoff:runoff*100,infiltration,soilLoss};}
export function biodiversity(v:Values){const habitat=v.habitat/100,fragment=clamp(1-(v.patches-1)/14),corridor=v.corridor/100,pollution=1-v.pollution/130,connectivity=clamp((fragment*.55+corridor*.45)*(0.55+habitat*.45))*100,viability=clamp(habitat*.55+connectivity/100*.35+pollution*.25-.15)*100;return{connectivity,viability,edge:clamp((v.patches-1)/11)*100};}
export function urbanHeat(v:Values){const baseline=Math.max(0,(v.temperature-28)*.12+2.6),cooling=v.trees*.045+v.coolRoofs*.018+v.permeable*.012,anomaly=Math.max(.2,baseline-cooling),runoff=clamp(.82-v.trees*.004-v.permeable*.007)*100;return{anomaly,runoff,local:v.temperature+anomaly};}
export function resilience(v:Values){const budget=v.wetlands+v.drainage+v.shade+v.barriers+v.warning,base=v.hazard,normalized=(x:number)=>1-Math.exp(-x/24),flood=base*(1-(.25*normalized(v.wetlands)+.3*normalized(v.drainage)+.3*normalized(v.barriers)+.15*normalized(v.warning))),heat=base*(1-(.15*normalized(v.wetlands)+.55*normalized(v.shade)+.3*normalized(v.warning))),storm=base*(1-(.2*normalized(v.wetlands)+.25*normalized(v.drainage)+.25*normalized(v.barriers)+.3*normalized(v.warning))),risk=(flood+heat+storm)/3;return{budget,flood,heat,storm,risk};}

export function metrics(slug:string,v:Values){switch(slug){case"greenhouse-effect-simulator":return greenhouse(v);case"carbon-cycle-simulator":return carbon(v);case"sea-level-rise-simulator":return seaLevel(v);case"ocean-acidification-simulator":return acidification(v);case"renewable-energy-grid-simulator":return grid(v);case"air-pollution-smog-simulator":return air(v);case"deforestation-water-cycle-simulator":return watershed(v);case"biodiversity-habitat-fragmentation":return biodiversity(v);case"urban-heat-island-simulator":return urbanHeat(v);default:return resilience(v);}}
export function mission(slug:string,v:Values,ran:boolean){let ok=false,text="Run the model before recording evidence.";if(!ran)return{ok,step:"complete",required:1,text};switch(slug){
 case"greenhouse-effect-simulator":{const m=greenhouse(v);ok=m.warming<1.5&&v.co2<=420;text=`Modeled warming ${m.warming.toFixed(2)}°C · CO₂ ${v.co2} ppm.`;break;}
 case"carbon-cycle-simulator":{const m=carbon(v);ok=m.net<=0&&m.ppm<430;text=`Net flow ${m.net.toFixed(1)} GtCO₂/yr · year-30 CO₂ ${m.ppm.toFixed(0)} ppm.`;break;}
 case"sea-level-rise-simulator":{const m=seaLevel(v);ok=m.total<.35&&v.years===80;text=`Modeled local rise ${m.total.toFixed(2)} m over ${v.years} years.`;break;}
 case"ocean-acidification-simulator":{const m=acidification(v);ok=m.ph>=8&&m.shell>=70;text=`Surface pH ${m.ph.toFixed(2)} · shell health ${m.shell.toFixed(0)}%.`;break;}
 case"renewable-energy-grid-simulator":{const m=grid(v);ok=m.reliability>=95&&m.cleanShare>=80&&m.emissions<=8;text=`Reliability ${m.reliability.toFixed(0)}% · clean share ${m.cleanShare.toFixed(0)}% · emissions ${m.emissions.toFixed(1)} tCO₂/h.`;break;}
 case"air-pollution-smog-simulator":{const m=air(v);ok=m.aqi<=50&&m.pm<=12&&m.ozone<=54;text=`AQI proxy ${m.aqi.toFixed(0)} · PM₂.₅ ${m.pm.toFixed(1)} µg/m³ · ozone ${m.ozone.toFixed(0)} ppb.`;break;}
 case"deforestation-water-cycle-simulator":{const m=watershed(v);ok=m.infiltration>55&&m.soilLoss<5;text=`Infiltration ${m.infiltration.toFixed(0)}% · soil loss ${m.soilLoss.toFixed(1)} t/ha.`;break;}
 case"biodiversity-habitat-fragmentation":{const m=biodiversity(v);ok=m.connectivity>=75&&m.viability>=75;text=`Connectivity ${m.connectivity.toFixed(0)}% · viability ${m.viability.toFixed(0)}%.`;break;}
 case"urban-heat-island-simulator":{const m=urbanHeat(v);ok=m.anomaly<1.5&&m.runoff<45;text=`Heat anomaly +${m.anomaly.toFixed(1)}°C · runoff ${m.runoff.toFixed(0)}%.`;break;}
 default:{const m=resilience(v);ok=m.budget<=100&&m.risk<30;text=`Investment ${m.budget}/100 · residual risk ${m.risk.toFixed(0)}/100.`;}
 }return{ok,step:"complete",required:1,text};}
