"use client";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import type { SubjectDefinition, SimulationCard } from "@/lib/subjects/catalog";
import { activities, codons, dnaComplement, dnaTemplate, foodChoices, heartRoute, immuneTurn, initialImmune, initialValues, logistic, mission, organelles, photosynthesis, predatorPrey, proteinTarget, rechallenge, rnaTarget, selection, sequenceMove, stages, transport, type ImmuneAction, type Values } from "@/lib/simulations/biologyLabs/model";
import { BiologyScene } from "./BiologyScene";
import { BiologyDisplay } from "./BiologyDisplay";
import styles from "../chemistry/chemistry.module.css";
import bio from "./biology.module.css";

const STORE="learnerkits-biology-missions-v1";
type Journal={completed:string[];observations:Record<string,string[]>};
const emptyJournal=():Journal=>({completed:[],observations:{}});
function loadJournal(){try{const p=JSON.parse(localStorage.getItem(STORE)||"{}");const observations=Object.fromEntries(Object.entries(p.observations||{}).filter((entry):entry is [string,string[]]=>{const [key,value]=entry;return activities.some(a=>a.slug===key)&&Array.isArray(value)&&value.every(v=>typeof v==="string");}));return{completed:Array.isArray(p.completed)?p.completed.filter((v:unknown)=>typeof v==="string"&&activities.some(a=>a.slug===v)):[],observations};}catch{return emptyJournal();}}
const sceneSlugs=["animal-cell-3d","cell-membrane-transport","human-heart-3d"];
const fmt=(n:number,d=1)=>Number.isFinite(n)?n.toFixed(d):"—";
function readouts(slug:string,v:Values,time:number,sequence:{index:number;mistakes:number},dna:string,rna:string,protein:string[],heart:number,edges:string[],immune:ReturnType<typeof initialImmune>):[string,string][]{switch(slug){
 case"population-growth":return[["Generation",fmt(time*2,0)],["Population",fmt(logistic(v,time*2),0)],["Percent of capacity",`${fmt(logistic(v,time*2)/v.capacity*100,0)}%`]];
 case"predator-prey":{const p=predatorPrey(v,Math.max(1,Math.ceil(time*6))).at(-1)!;return[["Year",fmt(time*6,0)],["Prey",fmt(p.a,0)],["Predators",fmt(p.b||0,0)]];}
 case"animal-cell-3d":return[["Selected",organelles[v.organelle].name],["Function match",v.function?organelles[v.function-1]?.function||"Unknown":"Not chosen"],["Structures identified","Record each match"]];
 case"cell-membrane-transport":{const m=transport(v);return[["Observed route",m.kind],["Direction",m.valid?m.direction:"No net transport"],["Relative rate",m.valid?fmt(m.rate,1):"0"]];}
 case"mitosis-challenge":return[["Current stage",stages[sequence.index]],["Stages completed",`${sequence.index} / 6`],["Sequence errors",String(sequence.mistakes)]];
 case"dna-replication":return[["Template",dnaTemplate],["New strand",dna||"—"],["Pairs built",`${dna.length} / ${dnaComplement.length}`]];
 case"protein-synthesis":return[["mRNA",rna||"—"],["Codons complete",`${Math.floor(rna.length/3)} / 4`],["Peptide",protein.join(" · ")||"—"]];
 case"human-heart-3d":return[["Current location",heartRoute[heart]],["Route checkpoints",`${heart} / ${heartRoute.length-1}`],["Blood oxygen",heart===0||heart>=7?"Oxygen-rich":"Oxygen-poor"]];
 case"natural-selection":{const end=selection(v,Math.floor(time*2)).at(-1)!.a;return[["Generation",fmt(time*2,0)],["Dark trait",`${fmt(end,1)}%`],["Light trait",`${fmt(100-end,1)}%`]];}
 case"food-web-builder":return[["Links selected",`${edges.length} / 7`],["Removal",v.removed?"Grasshopper":"None"],["Predicted response",["Not chosen","Frog declines","Rabbit declines","Fish increase"][v.prediction]]];
 case"photosynthesis-lab":return[["Relative rate",`${fmt(photosynthesis(v),1)}%`],["Resource budget",`${v.light}% light · ${v.co2} ppm`],["Temperature",`${v.temperature}°C`]];
 default:return[["Exposure",String(immune.exposure)],["Pathogens",fmt(immune.pathogens,0)],["Tissue health",`${fmt(immune.tissue,0)}%`]];
}}

export function BiologyActivitiesClient({locale,subject,simulation}:{locale:string;subject:SubjectDefinition;simulation:SimulationCard}){
 const activity=activities.find(a=>a.slug===simulation.slug)!,slug=activity.slug;
 const [values,setValues]=useState(()=>initialValues(activity)),[time,setTime]=useState(0),[running,setRunning]=useState(false),[speed,setSpeed]=useState(1),[journal,setJournal]=useState<Journal>(emptyJournal),[feedback,setFeedback]=useState<{ok:boolean;text:string}|null>(null),[hint,setHint]=useState(false),[saved,setSaved]=useState(true);
 const [sequence,setSequence]=useState({index:0,mistakes:0}),[dna,setDna]=useState(""),[rna,setRna]=useState(""),[protein,setProtein]=useState<string[]>([]),[heart,setHeart]=useState(0),[heartMistakes,setHeartMistakes]=useState(0),[edges,setEdges]=useState<string[]>([]),[immune,setImmune]=useState(initialImmune);
 const live=useRef({running,speed});live.current={running,speed};
 useEffect(()=>setJournal(loadJournal()),[]);
 useEffect(()=>{let last=performance.now();const timer=window.setInterval(()=>{const now=performance.now(),dt=Math.min(.1,(now-last)/1000);last=now;if(live.current.running&&!document.hidden)setTime(t=>Math.min(10,t+dt*live.current.speed));},50);return()=>clearInterval(timer);},[]);
 useEffect(()=>{if(time>=10)setRunning(false);},[time]);
 function update(key:string,value:number){setValues(v=>({...v,[key]:value}));setFeedback(null);setTime(0);setRunning(false);}
 function reset(){setValues(initialValues(activity));setTime(0);setRunning(false);setSequence({index:0,mistakes:0});setDna("");setRna("");setProtein([]);setHeart(0);setHeartMistakes(0);setEdges([]);setImmune(initialImmune());setFeedback(null);}
 const result=mission(slug,values,time>=10,{sequence,dna,rna,protein,heart,edges,immune}),stamps=journal.observations[slug]||[],complete=journal.completed.includes(slug);
 function check(){const current=mission(slug,values,time>=10,{sequence,dna,rna,protein,heart,edges,immune});if(!current.ok){setFeedback(current);return;}const stored=loadJournal(),steps=[...new Set([...(stored.observations[slug]||[]),...(journal.observations[slug]||[]),current.step])],done=steps.length>=current.required,next={completed:[...new Set([...stored.completed,...journal.completed,...(done?[slug]:[])])],observations:{...stored.observations,...journal.observations,[slug]:steps}};setJournal(next);try{localStorage.setItem(STORE,JSON.stringify(next));setSaved(true);}catch{setSaved(false);}setFeedback({ok:true,text:`${done?"Mission complete · biology badge earned!":`${steps.length}/${current.required} discoveries recorded.`} ${current.text}`});}
 function run(){setTime(0);setRunning(true);setFeedback(null);}
 const heartOptions=heart<heartRoute.length-1?[...new Set([heartRoute[heart+1],heartRoute[(heart+4)%(heartRoute.length-1)],heartRoute[(heart+7)%(heartRoute.length-1)]])]:[];
 const stageOptions=sequence.index<6?[...new Set([sequence.index+1,(sequence.index+3)%6+1,(sequence.index+4)%6+1])].filter(i=>i<=6):[];
 const custom=["mitosis-challenge","dna-replication","protein-synthesis","human-heart-3d","food-web-builder","immune-system-defense"].includes(slug);
 return <main className={`${styles.page} ${bio.page}`}>
  <header className={styles.header}><div><Link className={styles.back} href={`/${locale}/subjects/biology`}>← Biology & Ecosystems</Link><div className={styles.eyebrow}>BIOLOGY MISSIONS / LAB {String(activities.findIndex(a=>a.slug===slug)+1).padStart(2,"0")}</div><h1>{simulation.title}</h1><p>{simulation.outcome}</p></div><div className={`${styles.notebook} ${bio.badges}`}><span>YOUR BIOLOGY BADGES</span><strong>{journal.completed.length}<small> / 12</small></strong><span>{journal.completed.length>=9?"Systems biologist":journal.completed.length>=5?"Lab investigator":"Trainee scientist"}</span><div>{activities.map(a=><i key={a.slug} data-earned={journal.completed.includes(a.slug)}/>)}</div></div></header>
  <div className={bio.ribbon}><strong>◉ {activity.tag}</strong><span>{activity.run?"Change one variable. Run the model. Record evidence.":"Solve the biological system one step at a time."}</span><b>+1 BIOLOGY BADGE</b></div>
  <div className={styles.workspace}><section className={styles.scenePanel}><div className={styles.sceneTop}><span><i/>{sceneSlugs.includes(slug)?"INTERACTIVE 3D SPECIMEN":"LIVE BIOLOGY WORKBENCH"}</span><span className={bio.status}>{running?"● MODEL RUNNING":time>=10?"RUN COMPLETE":"READY"}</span></div><div className={styles.stage}>{sceneSlugs.includes(slug)?<BiologyScene slug={slug} values={values} time={time} heart={heart} onSelect={i=>{if(slug==="animal-cell-3d")update("organelle",i);}}/>:<BiologyDisplay slug={slug} values={values} time={time} sequence={sequence} dna={dna} rna={rna} protein={protein} heart={heart} edges={edges} immune={immune}/>}</div>
   <div className={styles.metrics}>{readouts(slug,values,time,sequence,dna,rna,protein,heart,edges,immune).map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>
   {activity.run&&<div className={bio.transport}><button onClick={()=>{if(time>=10)setTime(0);setRunning(r=>!r);}}>{running?"Ⅱ Pause":time>=10?"↻ Replay":"▶ Run model"}</button><progress value={time} max="10" aria-label="Model playback"/><span>{fmt(time*10,0)}%</span><select value={speed} aria-label="Playback speed" onChange={e=>setSpeed(Number(e.target.value))}><option value="1">1×</option><option value="2">2×</option><option value=".5">½×</option></select></div>}
   {slug==="animal-cell-3d"&&<div className={bio.legend}>{organelles.map((o,i)=><button key={o.name} aria-pressed={values.organelle===i} onClick={()=>update("organelle",i)}><i style={{background:`#${o.color.toString(16).padStart(6,"0")}`}}/>{o.name}</button>)}</div>}
   {slug==="cell-membrane-transport"&&<div className={bio.legend}><span>Gold: outside molecules</span><span>Blue: inside molecules</span><span>{transport(values).valid?`${transport(values).kind} is possible`:"Membrane blocks this setup"}</span></div>}
   {slug==="human-heart-3d"&&<div className={bio.legend}><span>Blue: oxygen-poor route to lungs</span><span>Red: oxygen-rich route to body</span><span>{heartMistakes} route errors</span></div>}
   <div className={bio.caption}>{slug==="human-heart-3d"?<><a href="https://dbarchive.biosciencedbc.jp/en/bodyparts3d/download.html" target="_blank" rel="noreferrer">BodyParts3D anatomical mesh</a> · © The Database Center for Life Science · CC BY 4.0 · colors and blood-route markers added for learning.</>:<>Educational model · sizes, rates, and visual density may be rescaled. Open “Model assumptions & science” before drawing real-world conclusions.</>}</div>
  </section><aside className={styles.controlsPanel}><div className={styles.mission}><div className={styles.missionLabel}><span>YOUR MISSION</span><b>{complete?"✓ BADGE EARNED":"IN PROGRESS"}</b></div><h2>{activity.mission}</h2><div className={bio.stamps}>{Array.from({length:result.required},(_,i)=><span key={i} data-filled={stamps.length>i}>{stamps.length>i?"✓":"◇"}</span>)}<small>{Math.min(stamps.length,result.required)} / {result.required}</small></div><button className={styles.hintButton} onClick={()=>setHint(h=>!h)} aria-expanded={hint}>{hint?"Close hint":"Need a hint?"}</button>{hint&&<p>{activity.hint}</p>}</div>
   <div className={styles.controlTitle}><h2>{custom?"Mission controls":"Experiment controls"}</h2><button onClick={reset}>↺ Reset</button></div>
   {!custom&&<div className={styles.controls}>{activity.controls.map(c=><label key={c.key} className={styles.control}><span><b>{c.label}</b>{!c.options&&<output>{fmt(values[c.key],c.step<.01?4:c.step<1?2:0)} {c.unit}</output>}</span>{c.options?<select value={values[c.key]} onChange={e=>update(c.key,Number(e.target.value))}>{c.options.map((option,i)=><option value={i} key={option}>{option}</option>)}</select>:<input type="range" min={c.min} max={c.max} step={c.step} value={values[c.key]} onChange={e=>update(c.key,Number(e.target.value))}/>}</label>)}</div>}
   {slug==="mitosis-challenge"&&<div className={bio.gameControls}><p>Current stage: <strong>{stages[sequence.index]}</strong></p>{stageOptions.map(i=><button key={i} onClick={()=>{setSequence(s=>sequenceMove(s,i));setFeedback(null);}}>{stages[i]} <span>→</span></button>)}</div>}
   {slug==="dna-replication"&&<div className={bio.gameControls}><p>Pair with template base <strong>{dnaTemplate[dna.length]||"complete"}</strong></p><div className={bio.baseKeys}>{["A","T","C","G"].map(base=><button disabled={dna.length>=dnaTemplate.length} key={base} onClick={()=>setDna(d=>d+base)}>{base}</button>)}</div><button onClick={()=>setDna(d=>d.slice(0,-1))}>← Remove last base</button></div>}
   {slug==="protein-synthesis"&&<div className={bio.gameControls}>{rna.length<rnaTarget.length?<><p>Transcribe DNA base <strong>{[..."TACCGATTTACT"][rna.length]}</strong> into mRNA</p><div className={bio.baseKeys}>{["A","U","C","G"].map(base=><button key={base} onClick={()=>setRna(r=>r+base)}>{base}</button>)}</div><button onClick={()=>setRna(r=>r.slice(0,-1))}>← Remove RNA base</button></>:<><p>Codon <strong>{rna.slice(protein.length*3,protein.length*3+3)||"complete"}</strong> codes for…</p><div className={bio.aminoKeys}>{proteinTarget.map(a=><button disabled={protein.length>=4} key={a} onClick={()=>setProtein(p=>[...p,a])}>{a}</button>)}</div><button onClick={()=>setProtein(p=>p.slice(0,-1))}>← Remove amino acid</button><button disabled={protein.length>0} onClick={()=>setRna(r=>r.slice(0,-1))}>Edit mRNA</button></>}</div>}
   {slug==="human-heart-3d"&&<div className={bio.gameControls}><p>Blood cell at <strong>{heartRoute[heart]}</strong>. Route it next:</p>{heartOptions.map(option=><button key={option} onClick={()=>{if(option===heartRoute[heart+1])setHeart(h=>h+1);else setHeartMistakes(m=>m+1);setFeedback(null);}}>{option}<span>→</span></button>)}</div>}
   {slug==="food-web-builder"&&<><div className={bio.webButtons}>{foodChoices.map(edge=><button key={edge} aria-pressed={edges.includes(edge)} onClick={()=>setEdges(list=>list.includes(edge)?list.filter(e=>e!==edge):[...list,edge])}>{edges.includes(edge)?"✓ ":"+ "}{edge}</button>)}</div><div className={styles.controls}>{activity.controls.map(c=><label key={c.key} className={styles.control}><span><b>{c.label}</b></span><select value={values[c.key]} onChange={e=>update(c.key,Number(e.target.value))}>{c.options!.map((o,i)=><option value={i} key={o}>{o}</option>)}</select></label>)}</div></>}
   {slug==="immune-system-defense"&&<div className={bio.immuneControls}><div><span>ENERGY</span><strong>{immune.energy} / 10</strong></div>{(["Innate cells","Activate B cells","Antibody strike","Rest"] as ImmuneAction[]).map(a=><button key={a} disabled={immune.cleared||immune.won||(a!=="Rest"&&immune.energy<(a==="Activate B cells"?3:2))} onClick={()=>setImmune(s=>immuneTurn(s,a))}><span>{a}</span><small>{a==="Rest"?"recover +4":a==="Activate B cells"?"cost 3":"cost 2"}</small></button>)}{immune.cleared&&immune.exposure===1&&<button className={bio.rechallenge} onClick={()=>setImmune(rechallenge)}>⚠ Rechallenge with same pathogen</button>}</div>}
   {activity.run&&<button className={styles.action} onClick={run}>▶ Run a fresh model</button>}<button className={styles.checkButton} onClick={check}>Record discovery <span>→</span></button><div className={styles.feedback} aria-live="polite">{feedback?<div data-success={feedback.ok}><strong>{feedback.ok?"✓ Lab journal updated":"Keep investigating"}</strong><p>{feedback.text}</p></div>:<p>Interact with the model, test your prediction, then record your discovery.</p>}</div>{!saved&&<p className={styles.saveWarning}>Completed for this session; browser storage is unavailable.</p>}
   <details className={styles.science}><summary>Model assumptions & science</summary><p>{activity.science}</p>{activity.source&&<a href={activity.source[1]} target="_blank" rel="noreferrer">{activity.source[0]} ↗</a>}</details>
  </aside></div>
  <section className={styles.library}><span className={styles.eyebrow}>CONTINUE YOUR BIOLOGY MISSIONS</span><h2>12 living systems to investigate</h2><div className={styles.labLinks}>{subject.simulations.map((sim,i)=><Link key={sim.slug} href={`/${locale}/simulations/${sim.slug}`} aria-current={sim.slug===slug?"page":undefined}><span>{String(i+1).padStart(2,"0")}</span><strong>{sim.title}</strong><small>{journal.completed.includes(sim.slug)?"✓ Badge earned":"Start mission ↗"}</small></Link>)}</div></section>
 </main>;
}
