// Keep this lightweight index separate from article bodies so navigation search
// never ships the full editorial collection to the browser.
export const articleSummaries = [
  { slug: "how-students-use-ai-to-understand-science", title: "How Can Students Use AI to Understand Difficult Science Concepts?", description: "A practical student workflow for using AI explanations, checking science claims, and testing predictions with free interactive simulations.", audience: "Students", category: "AI in Education", publishedAt: "2026-09-25", updatedAt: "2026-09-26", simulationSlugs: ["newtons-laws-force-lab", "gas-law-lab"], relatedSlugs: ["ai-tutors-vs-interactive-simulations", "check-ai-generated-science-answers"] },
  { slug: "ai-tutors-vs-interactive-simulations", title: "AI Tutors vs. Interactive Simulations: How They Differ", description: "Compare AI tutors and science simulations through a worked gas-law investigation, model limitations, and a classroom decision guide.", audience: "Students and teachers", category: "AI in Education", publishedAt: "2026-09-25", updatedAt: "2026-09-26", simulationSlugs: ["gas-law-lab", "pendulum-physics"], relatedSlugs: ["how-students-use-ai-to-understand-science", "how-teachers-use-ai-to-prepare-science-lessons"] },
  { slug: "check-ai-generated-science-answers", title: "How to Check Whether an AI-Generated Science Answer Is Correct", description: "Check AI science answers using sources, units, assumptions, independent calculations, and simulation evidence, with worked examples.", audience: "Students", category: "AI in Education", publishedAt: "2026-09-25", updatedAt: "2026-09-26", simulationSlugs: ["newtons-laws-force-lab", "gas-law-lab", "circuit-builder", "moon-phases-3d"], relatedSlugs: ["how-students-use-ai-to-understand-science", "use-ai-to-create-science-practice-questions"] },
  { slug: "how-teachers-use-ai-to-prepare-science-lessons", title: "How Teachers Can Use AI to Prepare Science Lessons", description: "Build an AI-assisted science lesson with a clear learning objective, a timed force-lab activity, differentiation, and an exit assessment.", audience: "Teachers", category: "AI in Education", publishedAt: "2026-09-25", updatedAt: "2026-09-26", simulationSlugs: ["newtons-laws-force-lab", "pendulum-physics"], relatedSlugs: ["use-ai-to-create-science-practice-questions", "ai-tutors-vs-interactive-simulations"] },
  { slug: "use-ai-to-create-science-practice-questions", title: "How to Use AI to Create Science Practice Questions", description: "Create and verify useful AI science questions with a question blueprint, worked force examples, answer keys, and a revision checklist.", audience: "Students and teachers", category: "AI in Education", publishedAt: "2026-09-25", updatedAt: "2026-09-26", simulationSlugs: ["newtons-laws-force-lab", "gas-law-lab"], relatedSlugs: ["check-ai-generated-science-answers", "how-teachers-use-ai-to-prepare-science-lessons"] },
  { slug: "what-are-interactive-learning-simulations", title: "What Are Interactive Learning Simulations?", description: "Learn what interactive learning simulations are, how their models work, and how students and teachers can use them for meaningful science investigations.", audience: "Students and teachers", category: "Educational Technology", publishedAt: "2026-09-26", updatedAt: "2026-09-26", simulationSlugs: ["newtons-laws-force-lab", "gas-law-lab", "projectile-lab"], relatedSlugs: ["how-virtual-science-labs-work", "educational-simulations-for-self-study"] },
  { slug: "how-virtual-science-labs-work", title: "How Virtual Science Labs Work", description: "Explore how virtual science labs turn inputs into results, with a worked gas-pressure investigation, model limitations, and practical recording tips.", audience: "Students", category: "Educational Technology", publishedAt: "2026-09-26", updatedAt: "2026-09-26", simulationSlugs: ["gas-law-lab", "pendulum-physics"], relatedSlugs: ["what-are-interactive-learning-simulations", "virtual-labs-vs-traditional-labs", "how-to-create-a-digital-science-notebook"] },
  { slug: "virtual-labs-vs-traditional-labs", title: "Virtual Labs vs. Traditional Labs: Differences and Limitations", description: "Compare virtual and traditional science labs by learning goals, evidence, practical skills, accessibility, and a paired pendulum lesson for teachers.", audience: "Teachers", category: "Educational Technology", publishedAt: "2026-09-26", updatedAt: "2026-09-26", simulationSlugs: ["pendulum-physics", "newtons-laws-force-lab"], relatedSlugs: ["how-virtual-science-labs-work", "how-to-create-a-digital-science-notebook"] },
  { slug: "educational-simulations-for-self-study", title: "How to Use Educational Simulations for Self-Study", description: "Build a focused simulation study routine using predictions, controlled comparisons, retrieval practice, an error log, and a worked pendulum example.", audience: "Students", category: "Educational Technology", publishedAt: "2026-09-26", updatedAt: "2026-09-26", simulationSlugs: ["pendulum-physics", "newtons-laws-force-lab", "gas-law-lab"], relatedSlugs: ["what-are-interactive-learning-simulations", "how-to-create-a-digital-science-notebook", "why-visual-learning-helps-science"] },
  { slug: "why-visual-learning-helps-science", title: "Why Visual Learning Helps Explain Abstract Science Concepts", description: "Learn how diagrams, graphs, and simulations clarify abstract science, with worked force examples, accessibility tips, and learning-style distinctions.", audience: "General education", category: "Educational Technology", publishedAt: "2026-09-26", updatedAt: "2026-09-26", simulationSlugs: ["newtons-laws-force-lab", "gas-law-lab"], relatedSlugs: ["what-are-interactive-learning-simulations", "educational-simulations-for-self-study"] },
  { slug: "how-to-create-a-digital-science-notebook", title: "How to Create a Digital Science Notebook", description: "Create a digital science notebook with a reusable template, worked pendulum entry, clear data tables, source records, and an effective review routine.", audience: "Students", category: "Educational Technology", publishedAt: "2026-09-26", updatedAt: "2026-09-26", simulationSlugs: ["pendulum-physics", "gas-law-lab"], relatedSlugs: ["educational-simulations-for-self-study", "how-virtual-science-labs-work", "check-ai-generated-science-answers"] },
] as const;

export type ArticleSlug = typeof articleSummaries[number]["slug"];
export type ArticleSummary = typeof articleSummaries[number];
export const articleCategories = [
  { name: "Educational Technology", id: "educational-technology", description: "Understand simulations, compare lab formats, and build practical habits for independent science learning." },
  { name: "AI in Education", id: "ai-in-education", description: "Use AI thoughtfully to study science, check explanations, prepare lessons, and create practice questions." },
] as const;
export const articlesUpdatedAt = articleSummaries.reduce((latest, article) => article.updatedAt > latest ? article.updatedAt : latest, "");

export function getArticleSummary(slug: string) {
  return articleSummaries.find((article) => article.slug === slug);
}

export function getArticlesForSimulation(slug: string) {
  return articleSummaries.filter((article) => (article.simulationSlugs as readonly string[]).includes(slug));
}
