export type Values=Record<string,number>;
export type Control={key:string;label:string;min:number;max:number;step:number;initial:number;unit?:string;options?:string[]};
export type Activity={slug:string;instrument:string;mission:string;hint:string;science:string;controls:Control[]};
const range=(key:string,label:string,min:number,max:number,step:number,initial:number,unit=""):Control=>({key,label,min,max,step,initial,unit});
const select=(key:string,label:string,options:string[],initial=0):Control=>({key,label,options,min:0,max:options.length-1,step:1,initial});
export const activities:Activity[]=[
  {slug:"moon-phases-3d",instrument:"Lunar phase observatory",mission:"Record new moon, first quarter, full moon, and last quarter.",hint:"Set the orbital angle to 0°, 90°, 180°, and 270°. Check each observation.",science:"The Sun illuminates half the Moon. The Earth-facing illuminated fraction is (1 − cos θ)/2 in this coplanar, distant-Sun model. The 3D overview exaggerates sizes; the observer disk shows the phase from Earth.",controls:[range("angle","Moon orbital angle",0,360,5,60,"°")]},
  {slug:"solar-eclipse-3d",instrument:"Eclipse alignment bench",mission:"Create both a total and an annular solar eclipse for the observer.",hint:"Align the centers at 0°. Try 356,000 km for a total eclipse and 406,000 km for an annular eclipse. Check each.",science:"Angular disk overlap is calculated from Sun/Moon radii and observer distance. Earth–Sun distance is fixed at 1 AU; the observer is on the near side of Earth. Offset is angular separation on the sky. Orbital inclination usually prevents alignment.",controls:[range("offset","Sky alignment offset",-.8,.8,.005,.25,"°"),range("distance","Earth–Moon center distance",356000,406000,1000,384000,"km")]},
  {slug:"escape-velocity",instrument:"Escape trajectory test",mission:"Launch from Earth with positive escape energy using at most 105% of the local escape speed.",hint:"At 400 km altitude on Earth, try 11.0 km/s. Launch to trace the trajectory; altitude changes the required speed.",science:"Tangential launch in a spherical body's two-body gravity. Specific energy ε = v²/2 − μ/r; escape requires ε ≥ 0. Trajectories use velocity-Verlet integration. Surface contact stops a trace; atmospheric drag is omitted.",controls:[select("world","Launch world",["Earth","Moon","Mars"]),range("altitude","Starting altitude",100,3000,25,400,"km"),range("speed","Tangential speed",1,16,.1,8,"km/s")]},
  {slug:"gravity-slingshot",instrument:"Gravity-assist planner",mission:"Fly past Earth with at least 300 km clearance and gain at least 5 km/s of heliocentric speed.",hint:"Try an incoming relative direction of 150°, 8 km/s approach speed, and a 1,000 km flyby altitude. Select clockwise deflection.",science:"Patched-conic Earth flyby: planet-frame speed at infinity stays constant. Deflection δ = 2 asin[1/(1 + rₚv∞²/μ)]. Adding Earth's 29.78 km/s orbital velocity before and after gives the heliocentric speed change. Earth motion is treated as locally straight.",controls:[range("angle","Incoming relative direction",0,360,5,150,"°"),range("speed","Approach speed at infinity",3,15,.5,8,"km/s"),range("altitude","Closest surface clearance",100,10000,100,1000,"km"),select("side","Deflection direction",["Clockwise","Counterclockwise"])]},
  {slug:"keplers-laws-orbit",instrument:"Kepler orbit observatory",mission:"Build an orbit with a period of 2.00 ± 0.05 years and eccentricity at least 0.50.",hint:"For a solar-mass star, T² = a³. Try a = 1.59 AU and eccentricity 0.6. Notice the faster motion near perihelion.",science:"Kepler's equation M = E − e sin E sets the nonuniform orbital motion. The star is at a focus. T² = a³ uses AU, years and one solar mass; v follows vis-viva. Blue swept sectors cover equal time intervals.",controls:[range("axis","Semi-major axis",.5,3,.01,1,"AU"),range("eccentricity","Eccentricity",0,.8,.01,.25),range("anomaly","Initial mean anomaly",0,360,5,0,"°")]},
  {slug:"earth-seasons-tilt",instrument:"Season & daylight observatory",mission:"At 60° north, record a summer day above 18 hours and a winter day below 6 hours.",hint:"Set latitude to 60° and tilt to 23.5°. Orbital longitudes 90° and 270° give opposite solstices.",science:"Solar declination δ = asin(sin tilt × sin orbital longitude). Daylight = 24 acos(−tan latitude × tan δ)/π, bounded to 0–24 h. Refraction is omitted. Earth's axis holds a fixed direction through the orbit.",controls:[range("longitude","Orbital longitude",0,360,5,0,"°"),range("tilt","Axial tilt",0,35,.5,23.5,"°"),range("latitude","Observer latitude",-70,70,1,40,"°")]},
  {slug:"satellite-orbit-builder",instrument:"Satellite injection planner",mission:"Launch an Earth orbit with eccentricity below 0.03, perigee above 150 km, and inclination 25–30°.",hint:"Set speed to 100% of circular velocity, altitude to 400 km, and inclination to 28°.",science:"Tangential injection into a spherical Earth gravity field. Vis-viva determines the ellipse and perigee; the velocity-vector plane sets inclination. This model omits drag, oblateness, and later burns. The trace is calculated from gravity, not an imposed circle.",controls:[range("altitude","Injection altitude",200,2000,25,400,"km"),range("speedScale","Injection speed",75,150,1,90,"% circular"),range("inclination","Orbit inclination",0,90,1,15,"°")]},
  {slug:"planet-size-comparison-3d",instrument:"Planet scale gallery",mission:"Compare Earth and Jupiter, then identify the approximate volume ratio.",hint:"Jupiter is about 11 Earth radii. Volume scales with radius cubed, so its volume is about 1,300 Earth volumes.",science:"Planets share one true radius scale in the viewer. Volumes assume spheres and use mean radii. Saturn's rings are omitted from the comparison. Planet colors are illustrative; Earth uses a surface texture.",controls:[select("planetA","Planet A",["Mercury","Venus","Earth","Mars","Jupiter","Saturn","Uranus","Neptune"],2),select("planetB","Planet B",["Mercury","Venus","Earth","Mars","Jupiter","Saturn","Uranus","Neptune"],3),select("answer","Jupiter / Earth volume",["Choose an estimate","About 11×","About 100×","About 1,300×"])]},
  {slug:"black-hole-orbit",instrument:"Relativistic orbit observatory",mission:"Choose a stable circular orbit between 3.1 and 4 Schwarzschild radii.",hint:"The innermost stable circular orbit around a nonrotating black hole is at 3 Schwarzschild radii. Choose 3.5 to stay outside it.",science:"Nonrotating Schwarzschild black hole. rₛ = 2GM/c²; a stable timelike circular orbit requires r > 3rₛ. Local circular speed is c/√[2(r/rₛ − 1)]. The clock ratio shown is for stationary clocks, √(1 − rₛ/r). Animation speed is rescaled; no gravitational lensing is rendered.",controls:[range("mass","Black hole mass",5,100,1,10,"solar masses"),range("radius","Circular orbit radius",2,15,.1,8,"rₛ")]},
  {slug:"mars-landing-challenge",instrument:"Mars descent flight deck",mission:"Touch down at no more than 3 m/s with fuel remaining.",hint:"Start with landing assist enabled. It manages a slowing descent; turn it off to fly the throttle yourself. Use 5× speed while high, then slow down near touchdown.",science:"One-dimensional powered descent: Mars gravity 3.71 m/s², exponential atmosphere, quadratic drag, finite thrust and fuel. Assist is a feedback controller that adjusts thrust, not a scripted landing. Terrain and vehicle sizes are exaggerated.",controls:[select("assist","Landing assist",["Manual throttle","Assisted descent"],1),range("throttle","Manual throttle",0,100,1,35,"%"),select("speed","Simulation speed",["1×","5×"],0)]},
];
export const initialValues=(a:Activity):Values=>Object.fromEntries(a.controls.map(c=>[c.key,c.initial]));
export const rad=(x:number)=>x*Math.PI/180;
export const worlds=[{name:"Earth",radius:6371,mu:398600.44},{name:"Moon",radius:1737.4,mu:4902.8},{name:"Mars",radius:3389.5,mu:42828.4}];
export const planets=[{name:"Mercury",radius:2440,color:0xa9a19a},{name:"Venus",radius:6052,color:0xd8bc89},{name:"Earth",radius:6371,color:0x6f9bd2},{name:"Mars",radius:3390,color:0xc77e59},{name:"Jupiter",radius:69911,color:0xd6b590},{name:"Saturn",radius:58232,color:0xe0cba0},{name:"Uranus",radius:25362,color:0x9ecbd8},{name:"Neptune",radius:24622,color:0x587fde}];
export const phaseFraction=(angle:number)=>(1-Math.cos(rad(angle)))/2;
export function eclipse(v:Values){const sun=Math.asin(695700/149597870)*180/Math.PI,moon=Math.asin(1737.4/(v.distance-6371))*180/Math.PI,d=Math.abs(v.offset);let area=0;if(d>=sun+moon)area=0;else if(d<=Math.abs(sun-moon))area=Math.PI*Math.min(sun,moon)**2;else{area=sun*sun*Math.acos((d*d+sun*sun-moon*moon)/(2*d*sun))+moon*moon*Math.acos((d*d+moon*moon-sun*sun)/(2*d*moon))-.5*Math.sqrt((-d+sun+moon)*(d+sun-moon)*(d-sun+moon)*(d+sun+moon));}const kind=d>=sun+moon?"No eclipse":d+sun<=moon?"Total":d+moon<sun?"Annular":"Partial";return{sun,moon,coverage:Math.max(0,Math.min(1,area/(Math.PI*sun*sun))),kind};}
export function orbital(v:Values,satellite=false){const world=worlds[satellite?0:v.world],radius=world.radius+v.altitude,circular=Math.sqrt(world.mu/radius),speed=satellite?circular*v.speedScale/100:v.speed,energy=speed*speed/2-world.mu/radius,q=speed/circular,eccentricity=Math.abs(q*q-1),p=radius*q*q,perigee=p/(1+eccentricity)-world.radius,axis=energy<0?-world.mu/(2*energy):Infinity;return{world,radius,circular,escape:Math.SQRT2*circular,speed,energy,q,eccentricity,perigee,period:Number.isFinite(axis)?2*Math.PI*Math.sqrt(axis**3/world.mu):Infinity};}
export type OrbitPoint={x:number;y:number;t:number};
export function orbitTrace(v:Values,satellite=false):{points:OrbitPoint[];status:string}{const o=orbital(v,satellite),points:OrbitPoint[]=[{x:1,y:0,t:0}];let x=1,y=0,vx=0,vy=o.q;const dt=.008;for(let i=1;i<=1200;i++){const r=Math.hypot(x,y),ax=-x/r**3,ay=-y/r**3;x+=vx*dt+.5*ax*dt*dt;y+=vy*dt+.5*ay*dt*dt;const next=Math.hypot(x,y);vx+=.5*(ax-x/next**3)*dt;vy+=.5*(ay-y/next**3)*dt;points.push({x,y,t:i*dt*o.radius/o.circular});if(next<=o.world.radius/o.radius)return{points,status:"Surface impact"};if(next>=8)return{points,status:"Outbound"};}return{points,status:o.energy>=0?"Outbound":"Bound orbit"};}
export function flyby(v:Values){const relative=v.speed,rp=6371+v.altitude,e=1+rp*relative*relative/398600.44,turn=2*Math.asin(1/e),a=rad(v.angle),b=a+(v.side?1:-1)*turn,planet=29.78;const before=Math.hypot(planet+relative*Math.cos(a),relative*Math.sin(a)),after=Math.hypot(planet+relative*Math.cos(b),relative*Math.sin(b));return{e,turn,before,after,gain:after-before,incoming:[relative*Math.cos(a),relative*Math.sin(a)],outgoing:[relative*Math.cos(b),relative*Math.sin(b)]};}
export function kepler(axis:number,e:number,mean:number){let E=mean%(2*Math.PI);for(let i=0;i<15;i++)E-=(E-e*Math.sin(E)-mean%(2*Math.PI))/(1-e*Math.cos(E));const x=axis*(Math.cos(E)-e),y=axis*Math.sqrt(1-e*e)*Math.sin(E),radius=Math.hypot(x,y);return{x,y,radius,period:axis**1.5,speed:29.7847*Math.sqrt(2/radius-1/axis)};}
export function seasons(v:Values){const declination=Math.asin(Math.sin(rad(v.tilt))*Math.sin(rad(v.longitude))),argument=-Math.tan(rad(v.latitude))*Math.tan(declination),daylight=24*Math.acos(Math.max(-1,Math.min(1,argument)))/Math.PI;return{declination:declination*180/Math.PI,daylight,noon:90-Math.abs(v.latitude-declination*180/Math.PI)};}
export function blackHole(v:Values){const rs=2.95325*v.mass,r=v.radius;return{rs,orbitKm:rs*r,localSpeed:1/Math.sqrt(2*(r-1)),clock:Math.sqrt(1-1/r),stable:r>3,period:2*Math.PI*Math.sqrt((rs*r)**3/(132712440018*v.mass))};}
export type MarsState={altitude:number;velocity:number;fuel:number;time:number;throttle:number;status:"ready"|"flying"|"landed"|"crashed";impact:number};
export const initialMars=():MarsState=>({altitude:800,velocity:-45,fuel:400,time:0,throttle:0,status:"ready",impact:0});
export function stepMars(s:MarsState,v:Values,dt:number):MarsState{if(s.status!=="flying"||dt<=0)return s;const mass=900+s.fuel,density=.020*Math.exp(-s.altitude/11100),drag=-.5*density*1.5*12*s.velocity*Math.abs(s.velocity)/mass,target=-Math.max(1,Math.min(35,Math.sqrt(2*Math.max(0,s.altitude))));const command=v.assist?Math.max(0,Math.min(1,((target-s.velocity)*.8+3.71-drag)*mass/9000)):v.throttle/100;const requested=9000*command/(225*9.80665)*dt,used=Math.min(s.fuel,requested),thrust=requested>0?9000*command*used/requested:0,velocity=s.velocity+(thrust/mass-3.71+drag)*dt,altitude=s.altitude+velocity*dt;const next:MarsState={...s,altitude:Math.max(0,altitude),velocity,fuel:s.fuel-used,time:s.time+dt,throttle:thrust/9000};if(altitude<=0){next.impact=Math.abs(velocity);next.status=next.impact<=3?"landed":"crashed";next.velocity=0;next.throttle=0;}return next;}
export function checkMission(slug:string,v:Values,ran:boolean,mars:MarsState){let ok=false,text="",step="done",required=1;switch(slug){
  case"moon-phases-3d":{const a=((v.angle%360)+360)%360,k=Math.round(a/90)%4,d=Math.min(Math.abs(a-k*90),Math.abs(a-k*90-360));ok=d<=5;step=String(k);required=4;text=ok?["New moon: the sunlit half faces away.","First quarter: half the visible disk is lit.","Full moon: the Earth-facing disk is lit.","Last quarter: the other half is lit."][k]:"Move to a main phase near 0°, 90°, 180°, or 270°.";break;}
  case"solar-eclipse-3d":{const e=eclipse(v);ok=e.kind==="Total"||e.kind==="Annular";step=e.kind;required=2;text=`${e.kind}: ${(e.coverage*100).toFixed(1)}% of the Sun's disk covered. Align centers and change Moon distance.`;break;}
  case"escape-velocity":{const o=orbital(v);ok=ran&&v.world===0&&o.speed>=o.escape&&o.speed<=o.escape*1.05;text=`Local escape speed: ${o.escape.toFixed(2)} km/s. Launch from Earth just above this speed.`;break;}
  case"gravity-slingshot":{const f=flyby(v);ok=ran&&v.altitude>=300&&f.gain>=5;text=`Heliocentric speed change: ${f.gain.toFixed(2)} km/s. A gravity assist can add or remove speed, depending on geometry.`;break;}
  case"keplers-laws-orbit":{const t=v.axis**1.5;ok=Math.abs(t-2)<=.05&&v.eccentricity>=.5;text=`Period ${t.toFixed(3)} years; eccentricity ${v.eccentricity.toFixed(2)}. Target 1.95–2.05 years and e ≥ 0.50.`;break;}
  case"earth-seasons-tilt":{const s=seasons(v);ok=v.latitude===60&&(s.daylight>18||s.daylight<6);step=s.daylight>18?"summer":"winter";required=2;text=`${s.daylight.toFixed(2)} daylight hours at ${v.latitude}°. Record opposite seasons at 60° north.`;break;}
  case"satellite-orbit-builder":{const o=orbital(v,true);ok=ran&&o.eccentricity<.03&&o.perigee>150&&v.inclination>=25&&v.inclination<=30;text=`Eccentricity ${o.eccentricity.toFixed(3)}; perigee ${o.perigee.toFixed(0)} km. Launch a nearly circular orbit inclined 25–30°.`;break;}
  case"planet-size-comparison-3d":ok=((v.planetA===2&&v.planetB===4)||(v.planetA===4&&v.planetB===2))&&v.answer===3;text="Compare Earth and Jupiter. Volume is proportional to radius cubed: about 1,300×, not 11×.";break;
  case"black-hole-orbit":ok=v.radius>=3.1&&v.radius<=4;text=`Selected ${v.radius.toFixed(1)} rₛ. Stable circular orbits are outside 3 rₛ; the mission band is 3.1–4 rₛ.`;break;
  case"mars-landing-challenge":ok=mars.status==="landed"&&mars.fuel>0;text=mars.status==="landed"?`Touchdown at ${mars.impact.toFixed(2)} m/s with ${mars.fuel.toFixed(1)} kg fuel.`:mars.status==="crashed"?`Impact at ${mars.impact.toFixed(1)} m/s. Restart and brake earlier.`:"Launch the descent and slow to no more than 3 m/s before surface contact.";break;
}return{ok,text,step,required};}
