"use client";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import type { SubjectDefinition, SimulationCard } from "@/lib/subjects/catalog";
import { runtimeText } from "@/lib/i18n/runtimeText";
import { loadSettings, prefersReducedMotion } from "@/lib/settings/storage";
import { activities, blackHole, checkMission, eclipse, flyby, initialMars, initialValues, kepler, orbital, phaseFraction, planets, rad, seasons, stepMars, type Values } from "@/lib/simulations/spaceLabs/model";
import { SpaceScene } from "./SpaceScene";
import { ObserverPanel } from "./ObserverPanel";
import styles from "../chemistry/chemistry.module.css";
import space from "./space.module.css";

const STORE="learnerkits-space-labs-v1";
const format=(v:number,d=2)=>Number.isFinite(v)?v.toFixed(d):"Unbound";
function metrics(slug:string,v:Values,time:number):[string,string][]{switch(slug){
  case"moon-phases-3d":return[["Orbital angle",`${v.angle}°`],["Illuminated",`${format(phaseFraction(v.angle)*100,0)}%`],["Synodic age",`${format((v.angle%360)/360*29.53,1)} days`]];
  case"solar-eclipse-3d":{const e=eclipse(v);return[["Sun diameter",`${format(e.sun*2,3)}°`],["Moon diameter",`${format(e.moon*2,3)}°`],["Eclipse",e.kind]];}
  case"escape-velocity":case"satellite-orbit-builder":{const o=orbital(v,slug==="satellite-orbit-builder");return slug==="escape-velocity"?[["Circular speed",`${format(o.circular)} km/s`],["Escape speed",`${format(o.escape)} km/s`],["Specific energy",`${format(o.energy)} km²/s²`]]:[["Eccentricity",format(o.eccentricity,3)],["Perigee altitude",`${format(o.perigee,0)} km`],["Orbital period",Number.isFinite(o.period)?`${format(o.period/60,1)} min`:"Unbound"]];}
  case"gravity-slingshot":{const f=flyby(v);return[["Deflection",`${format(f.turn*180/Math.PI,1)}°`],["Speed change",`${format(f.gain)} km/s`],["Clearance",`${v.altitude} km`]];}
  case"keplers-laws-orbit":{const p=kepler(v.axis,v.eccentricity,rad(v.anomaly)+time/12/v.axis**1.5*Math.PI*2);return[["Period",`${format(p.period,3)} years`],["Distance",`${format(p.radius)} AU`],["Orbital speed",`${format(p.speed,1)} km/s`]];}
  case"earth-seasons-tilt":{const s=seasons(v);return[["Solar declination",`${format(s.declination,1)}°`],["Daylight",`${format(s.daylight)} h`],["Noon Sun altitude",`${format(s.noon,1)}°`]];}
  case"planet-size-comparison-3d":{const a=planets[v.planetA],b=planets[v.planetB];return[[`${a.name} radius`,`${a.radius.toLocaleString("en-US")} km`],[`${b.name} radius`,`${b.radius.toLocaleString("en-US")} km`],["Volume ratio B / A",`${format((b.radius/a.radius)**3,3)}×`]];}
  case"black-hole-orbit":{const b=blackHole(v);return[["Horizon radius",`${format(b.rs,1)} km`],["Local orbit speed",`${format(b.localSpeed*100,1)}% c`],["Stationary clock / far clock",`${format(b.clock,3)}×`]];}
  default:return[];
}}
export function SpaceActivitiesClient({locale,subject,simulation}:{locale:string;subject:SubjectDefinition;simulation:SimulationCard}){
  const activity=activities.find(a=>a.slug===simulation.slug)!,slug=activity.slug,isMars=slug==="mars-landing-challenge",launch=["escape-velocity","satellite-orbit-builder","gravity-slingshot"].includes(slug);
  const [values,setValues]=useState<Values>(()=>initialValues(activity)),[time,setTime]=useState(0),[paused,setPaused]=useState(false),[started,setStarted]=useState(false),[mars,setMars]=useState(initialMars);
  const [completed,setCompleted]=useState<string[]>([]),[steps,setSteps]=useState<string[]>([]),[feedback,setFeedback]=useState<{ok:boolean;text:string}|null>(null),[hint,setHint]=useState(false),[saved,setSaved]=useState(true),[reduced,setReduced]=useState(false);
  const live=useRef({paused,started,values,reduced});live.current={paused,started,values,reduced};
  useEffect(()=>{try{const p:unknown=JSON.parse(localStorage.getItem(STORE)||"[]");if(Array.isArray(p))setCompleted(p.filter((s):s is string=>typeof s==="string"&&activities.some(a=>a.slug===s)));}catch{/* Keep session progress. */}setReduced(prefersReducedMotion(loadSettings()));},[]);
  useEffect(()=>{let last=performance.now();const timer=window.setInterval(()=>{const now=performance.now(),dt=Math.min(.1,(now-last)/1000);last=now;const s=live.current;if(s.paused||document.hidden)return;if(isMars){if(s.started){const count=Math.max(1,Math.ceil(dt*(s.values.speed?5:1)*120));setMars(m=>{let next=m;for(let i=0;i<count;i++)next=stepMars(next,s.values,dt*(s.values.speed?5:1)/count);return next;});}}else if(launch){if(s.started)setTime(t=>Math.min(8,t+dt));}else if(!s.reduced)setTime(t=>t+dt);},50);return()=>clearInterval(timer);},[isMars,launch]);
  function update(key:string,value:number){setValues(v=>({...v,[key]:value}));setFeedback(null);if(!isMars){setTime(0);setStarted(false);}}
  function reset(){setValues(initialValues(activity));setTime(0);setPaused(false);setStarted(false);setMars(initialMars());setSteps([]);setFeedback(null);}
  function start(){setTime(0);setStarted(true);setPaused(false);setFeedback(null);if(isMars)setMars({...initialMars(),status:"flying"});}
  function check(){const r=checkMission(slug,values,started&&time>=8,mars);if(r.ok){const next=[...new Set([...steps,r.step])];setSteps(next);if(next.length>=r.required){const all=[...new Set([...completed,slug])];setCompleted(all);try{localStorage.setItem(STORE,JSON.stringify(all));setSaved(true);}catch{setSaved(false);}setFeedback({ok:true,text:`Mission complete. ${r.text}`});}else setFeedback({ok:true,text:`${next.length}/${r.required} observations recorded. ${r.text}`});}else setFeedback(r);}
  const data=isMars?[["Altitude",`${format(mars.altitude,1)} m`],["Vertical velocity",`${format(mars.velocity)} m/s`],["Fuel",`${format(mars.fuel,1)} kg`]]:metrics(slug,values,time);
  return <main className={`${styles.page} ${space.page}`}><header className={styles.header}><div><Link className={styles.back} href={`/${locale}/subjects/space`}>← {subject.eyebrow}</Link><div className={styles.eyebrow}>SPACE OBSERVATORY / {String(activities.findIndex(a=>a.slug===slug)+1).padStart(2,"0")}</div><h1>{simulation.title}</h1><p>{simulation.outcome}</p></div><div className={styles.notebook}><span>YOUR OBSERVATORY NOTEBOOK</span><strong>{completed.length}<small> / {activities.length}</small></strong><span>plus Moon Landing & Orbital Rescue missions</span></div></header>
    <div className={styles.workspace}><section className={styles.scenePanel} aria-label={simulation.title}><div className={styles.sceneTop}><span><i/>{activity.instrument}</span><button aria-pressed={paused} onClick={()=>setPaused(p=>!p)}>{paused?"▶ Resume":"Ⅱ Pause"}</button></div><div className={styles.stage}><SpaceScene slug={slug} values={values} time={time} mars={mars}/></div>
      <div className={styles.metrics}>{data.map(([label,value])=><div key={label}><span>{runtimeText(locale,label)}</span><strong>{value}</strong></div>)}</div><ObserverPanel slug={slug} values={values}/>
      {launch&&<div className={space.trace}><span>{!started?"Set conditions and launch":time<8?"Tracing trajectory…":"Trace complete"}</span><progress value={time} max={8} aria-label="Trajectory playback"/><span>Accelerated playback</span></div>}
      {slug==="keplers-laws-orbit"&&<div className={styles.legend}><span>Sun at a focus · equal-time swept sectors</span><span>12 playback seconds = 1 simulated year</span></div>}
      {slug==="black-hole-orbit"&&<div className={space.notice}><strong>{blackHole(values).stable?"Stable circular orbit":"No stable circular orbit at this radius"}</strong><p>Dark sphere: horizon · amber ring: photon orbit (1.5 rₛ) · blue ring: innermost stable orbit (3 rₛ). Probe hidden in the unstable region.</p></div>}
      {isMars&&<div className={space.notice}><strong>{mars.status==="ready"?"Ready for descent":mars.status==="flying"?`${values.assist?"Landing assist":"Manual control"} · thrust ${(mars.throttle*100).toFixed(0)}%`:mars.status==="landed"?`Touchdown · ${mars.impact.toFixed(2)} m/s`:`Crash · ${mars.impact.toFixed(1)} m/s impact`}</strong><p>Elapsed {mars.time.toFixed(1)} s · Mars gravity 3.71 m/s² · Actual thrust {format(mars.throttle*9)} kN</p></div>}
    </section><aside className={styles.controlsPanel}><div className={styles.mission}><div className={styles.missionLabel}><span>YOUR MISSION</span><b>{completed.includes(slug)?"✓ COMPLETE":"IN PROGRESS"}</b></div><h2>{activity.mission}</h2><button className={styles.hintButton} aria-expanded={hint} onClick={()=>setHint(v=>!v)}>{hint?"Hide hint":"Need a hint?"}</button>{hint&&<p>{activity.hint}</p>}</div><div className={styles.controlTitle}><h2>{isMars?"Flight controls":"Experiment controls"}</h2><button onClick={reset}>↺ Reset</button></div>
      <div className={styles.controls}>{activity.controls.map(c=><label key={c.key} className={styles.control}><span><b>{runtimeText(locale,c.label)}</b>{!c.options&&<output>{format(values[c.key],c.step<.01?3:c.step<1?c.step===.01?2:1:0)} {c.unit}</output>}</span>{c.options?<select value={values[c.key]} onChange={e=>update(c.key,Number(e.target.value))}>{c.options.map((o,i)=><option value={i} key={o}>{runtimeText(locale,o)}</option>)}</select>:<input type="range" min={c.min} max={c.max} step={c.step} value={values[c.key]} disabled={isMars&&c.key==="throttle"&&values.assist===1} onChange={e=>update(c.key,Number(e.target.value))}/>}</label>)}</div>
      {(launch||isMars)&&<button className={styles.action} disabled={isMars&&mars.status==="flying"} onClick={start}>{isMars?mars.status==="flying"?"Descent in progress…":"▶ Begin descent":"▶ Launch trajectory"}</button>}
      <button className={styles.checkButton} onClick={check}>Check mission <span>→</span></button><div className={styles.feedback} aria-live="polite" aria-atomic="true">{feedback?<div data-success={feedback.ok}><strong>{feedback.ok?"✓ Observation recorded":"Try another approach"}</strong><p>{feedback.text}</p></div>:<p>Adjust the controls, observe what changes, then check your mission.</p>}</div>{!saved&&<p className={styles.saveWarning}>Completed for this session; browser storage is unavailable.</p>}<details className={styles.science}><summary>How the science works</summary><p>{activity.science}</p>{slug==="solar-eclipse-3d"&&<a href="https://science.nasa.gov/eclipses/geometry/" target="_blank" rel="noreferrer">NASA: eclipse geometry ↗</a>}{slug==="black-hole-orbit"&&<a href="https://jila.colorado.edu/~ajsh/bh/approach.html" target="_blank" rel="noreferrer">JILA: circular orbits near a black hole ↗</a>}</details>
    </aside></div><section className={styles.library}><span className={styles.eyebrow}>CONTINUE YOUR EXPLORATION</span><h2>All {subject.simulations.length} space activities</h2><div className={styles.labLinks}>{subject.simulations.map((sim,i)=><Link key={sim.slug} href={`/${locale}/simulations/${sim.slug}`} aria-current={sim.slug===slug?"page":undefined}><span>{String(i+1).padStart(2,"0")}</span><strong>{sim.title}</strong><small>{completed.includes(sim.slug)?"✓ Completed":sim.slug==="moon-landing"||sim.slug==="orbital-rescue"?"Flight simulator ↗":"Open observatory ↗"}</small></Link>)}</div></section>
  </main>;
}
