"use client";
import { useEffect, useRef, useState } from "react";
import { useSearchParams } from "next/navigation";
import * as THREE from "three";
import { OrbitalRescueEngine, type BurnDirection, type OrbitalState } from "@/lib/simulations/orbitalRescue/engine";
import { FixedStepRunner } from "@/lib/simulations/fixedStep";
import { EARTH_MU, EARTH_RADIUS } from "@/lib/physics/constants";
import type { Messages } from "@/lib/i18n/getMessages";
import { missions } from "@/lib/missions/catalog";
import { orbitMissionComplete, orbitalScore } from "@/lib/missions/successConditions";
import { completeMission } from "@/lib/progression/storage";
import { t } from "@/lib/i18n/t";
import { loadSettings, prefersReducedMotion, renderProfile } from "@/lib/settings/storage";

const initialEngine = new OrbitalRescueEngine();
const fmt=(n:number,d=1)=>Number.isFinite(n)?n.toFixed(d):"—";
export function OrbitalRescueClient({m}:{m:Messages}){
  const searchParams=useSearchParams();
  const selectedMission=missions.find((mission)=>mission.id===searchParams.get("mission")&&mission.simulation==="orbitalRescue");
  const host=useRef<HTMLDivElement>(null); const engineRef=useRef(new OrbitalRescueEngine()); const runnerRef=useRef(new FixedStepRunner(.25,32,5));
  const [state,setState]=useState<OrbitalState>(initialEngine.getState()); const [telemetry,setTelemetry]=useState(initialEngine.telemetry());
  const [paused,setPaused]=useState(false); const [timeScale,setTimeScale]=useState(10); const [mode,setMode]=useState<"play"|"learn"|"experiment">("play");
  const playback=useRef({paused,timeScale});playback.current={paused,timeScale};
  const [experiment,setExperiment]=useState({altitudeKm:400,targetAltitudeKm:430,dryMass:8000,fuelMass:3500,maxThrust:120000});
  useEffect(()=>{if(!host.current)return;const container=host.current;const scene=new THREE.Scene();scene.background=new THREE.Color(0x01040b);const camera=new THREE.OrthographicCamera(-10,10,10,-10,.1,100);camera.position.set(0,0,25);camera.lookAt(0,0,0);const visualSettings=loadSettings();const profile=renderProfile(visualSettings.quality);const reduceMotion=prefersReducedMotion(visualSettings);const renderer=new THREE.WebGLRenderer({antialias:visualSettings.quality!=="low",powerPreference:"high-performance"});renderer.setPixelRatio(Math.min(window.devicePixelRatio,profile.pixelRatioCap));renderer.shadowMap.enabled=profile.shadows;container.appendChild(renderer.domElement);
    scene.add(new THREE.AmbientLight(0x6e8fc7,1.2));const sun=new THREE.DirectionalLight(0xffffff,2.3);sun.position.set(-8,5,10);scene.add(sun);
    const earth=new THREE.Mesh(new THREE.SphereGeometry(5.35,48,48),new THREE.MeshStandardMaterial({color:0x1e65a8,roughness:.72,metalness:.05}));scene.add(earth);const atmosphere=new THREE.Mesh(new THREE.SphereGeometry(5.52,48,48),new THREE.MeshBasicMaterial({color:0x70d9ff,transparent:true,opacity:.08,side:THREE.BackSide}));scene.add(atmosphere);
    const starGeo=new THREE.BufferGeometry();const pts=[] as number[];const orbitalStarCount=reduceMotion?Math.min(profile.starCount,300):profile.starCount;for(let i=0;i<orbitalStarCount;i++)pts.push((Math.random()-.5)*60,(Math.random()-.5)*40,-5-Math.random()*20);starGeo.setAttribute("position",new THREE.Float32BufferAttribute(pts,3));scene.add(new THREE.Points(starGeo,new THREE.PointsMaterial({color:0xffffff,size:.035})));
    const ship=new THREE.Mesh(new THREE.ConeGeometry(.13,.38,7),new THREE.MeshStandardMaterial({color:0xf2f4f8,metalness:.7,roughness:.25}));scene.add(ship);const target=new THREE.Mesh(new THREE.BoxGeometry(.26,.16,.12),new THREE.MeshStandardMaterial({color:0xffdb82,metalness:.65,roughness:.3}));scene.add(target);
    const shipHistory:number[]=[];const lineGeo=new THREE.BufferGeometry();const lineMat=new THREE.LineBasicMaterial({color:0x86e8ff,transparent:true,opacity:.55});const line=new THREE.Line(lineGeo,lineMat);scene.add(line);
    const scale=5.35/EARTH_RADIUS;let previous=performance.now(),uiClock=0,historyClock=0,raf=0,lastElapsed=0;
    const resize=()=>{const w=container.clientWidth,h=container.clientHeight,aspect=w/Math.max(1,h);camera.left=-10*aspect;camera.right=10*aspect;camera.top=10;camera.bottom=-10;camera.updateProjectionMatrix();renderer.setSize(w,h,false)};const ro=new ResizeObserver(resize);ro.observe(container);resize();
    const loop=(now:number)=>{const frame=Math.min(.1,(now-previous)/1000);previous=now;if(!playback.current.paused&&!document.hidden)runnerRef.current.advance(frame*playback.current.timeScale,(dt)=>engineRef.current.update(dt));const s=engineRef.current.getState();if(s.elapsed<lastElapsed){shipHistory.length=0;lineGeo.setAttribute("position",new THREE.Float32BufferAttribute([],3));}lastElapsed=s.elapsed;ship.position.set(s.position.x*scale,s.position.y*scale,0);target.position.set(s.targetPosition.x*scale,s.targetPosition.y*scale,0);ship.rotation.z=Math.atan2(s.velocity.y,s.velocity.x)-Math.PI/2;target.rotation.z=Math.atan2(s.targetVelocity.y,s.targetVelocity.x);
      if(!playback.current.paused&&!document.hidden)historyClock+=frame;if(historyClock>.12){historyClock=0;shipHistory.push(ship.position.x,ship.position.y,0);if(shipHistory.length>900)shipHistory.splice(0,3);lineGeo.setAttribute("position",new THREE.Float32BufferAttribute(shipHistory,3))}
      renderer.render(scene,camera);uiClock+=frame;if(uiClock>.1){uiClock=0;setState(s);setTelemetry(engineRef.current.telemetry())}raf=requestAnimationFrame(loop)};raf=requestAnimationFrame(loop);
    return()=>{cancelAnimationFrame(raf);ro.disconnect();renderer.dispose();lineGeo.dispose();lineMat.dispose();scene.traverse(o=>{if(o instanceof THREE.Mesh||o instanceof THREE.Points){o.geometry.dispose();const mat=o.material;if(Array.isArray(mat))mat.forEach(x=>x.dispose());else mat.dispose()}});container.removeChild(renderer.domElement)}
  },[]);
  const setDirection=(direction:BurnDirection)=>{engineRef.current.handleInput({direction});setState(engineRef.current.getState())};
  const reset=()=>{engineRef.current.reset();runnerRef.current.reset();setPaused(false);setState(engineRef.current.getState());setTelemetry(engineRef.current.telemetry())};
  const applyExperiment=()=>{
    const r=EARTH_RADIUS+Math.max(120,experiment.altitudeKm)*1000;
    const tr=EARTH_RADIUS+Math.max(120,experiment.targetAltitudeKm)*1000;
    const speed=Math.sqrt(EARTH_MU/r);const targetSpeed=Math.sqrt(EARTH_MU/tr);const fuel=Math.max(100,experiment.fuelMass);
    engineRef.current=new OrbitalRescueEngine({position:{x:r,y:0},velocity:{x:0,y:speed*.995},targetPosition:{x:0,y:tr},targetVelocity:{x:-targetSpeed,y:0},dryMass:Math.max(500,experiment.dryMass),fuelMass:fuel,initialFuelMass:fuel,maxThrust:Math.max(1000,experiment.maxThrust)});
    runnerRef.current.reset();setPaused(false);setState(engineRef.current.getState());setTelemetry(engineRef.current.telemetry());
  };
  const fuelPct=100*state.fuelMass/state.initialFuelMass;
  const orbitContext={state,altitude:telemetry.altitude,targetDistance:telemetry.targetDistance,relativeVelocity:telemetry.relativeVelocity};
  const missionComplete=selectedMission?orbitMissionComplete(selectedMission.id,orbitContext):false;
  const score=orbitalScore(orbitContext);
  useEffect(()=>{if(selectedMission&&missionComplete)completeMission(selectedMission.id,selectedMission.xp,score)},[selectedMission,missionComplete,score]);
  return <main className="simLayout"><section className="simViewport" aria-label={m.orbitalRescue.title}><div ref={host} className="threeHost"/><div className="overlayTop"><h1>{m.orbitalRescue.title}</h1><p>{m.orbitalRescue.instructions}</p></div>{state.status!=="active"&&<div className="statusBanner"><strong>{state.status==="rescued"?m.orbitalRescue.rescued:state.status==="reentry"?m.orbitalRescue.reentry:m.orbitalRescue.escaped}</strong><span className="muted">{state.status==="rescued"?m.orbitalRescue.rescuedReason:state.status==="reentry"?m.orbitalRescue.reentryReason:m.orbitalRescue.escapedReason}</span></div>}</section>
    <aside className="hud"><h2>{m.orbitalRescue.telemetry}</h2>{selectedMission&&<div className="card" style={{padding:12,marginBottom:12}}><span className="eyebrow">{m.missions.active}</span><h3 style={{marginBottom:5}}>{t(m,selectedMission.titleKey)}</h3><p className="muted" style={{fontSize:'.82rem'}}>{t(m,selectedMission.descriptionKey)}</p><span className="pill">{missionComplete?m.missions.complete:m.missions.inProgress}</span>{score>0&&<span className="pill">{m.missions.score}: {score}</span>}</div>}<div className="metric"><span>{m.common.altitude}</span><strong>{fmt(telemetry.altitude/1000,0)} km</strong></div><div className="metric"><span>{m.common.velocity}</span><strong>{fmt(telemetry.speed/1000,3)} km/s</strong></div><div className="metric"><span>{m.orbitalRescue.orbitalVelocity}</span><strong>{fmt(telemetry.circularSpeed/1000,3)} km/s</strong></div><div className="metric"><span>{m.orbitalRescue.deltaV}</span><strong>{fmt(telemetry.deltaVRemaining,0)} m/s</strong></div><div className="metric"><span>{m.common.fuel}</span><strong>{fmt(fuelPct,0)}%</strong></div><div className="metric"><span>{m.orbitalRescue.energy}</span><strong>{fmt(telemetry.orbitalEnergy/1e6,2)} MJ/kg</strong></div><div className="metric"><span>{m.orbitalRescue.distance}</span><strong>{fmt(telemetry.targetDistance/1000,1)} km</strong></div><div className="metric"><span>{m.orbitalRescue.relativeVelocity}</span><strong>{fmt(telemetry.relativeVelocity,1)} m/s</strong></div>
      <div className="controlGroup"><label>{m.common.throttle}: {fmt(state.thrust*100,0)}%</label><input type="range" min="0" max="1" step=".01" value={state.thrust} onChange={e=>{engineRef.current.handleInput({thrust:Number(e.target.value)});setState(engineRef.current.getState())}}/></div>
      <div className="controlGroup"><label>{m.orbitalRescue.direction}</label><div className="segmented">{([['none',m.orbitalRescue.none],['prograde',m.orbitalRescue.prograde],['retrograde',m.orbitalRescue.retrograde],['radial-out',m.orbitalRescue.radialOut],['radial-in',m.orbitalRescue.radialIn]] as [BurnDirection,string][]).map(([d,label])=><button key={d} className={state.direction===d?"active":""} onClick={()=>setDirection(d)}>{label}</button>)}</div></div>
      <div className="controlGroup"><label>{m.common.mode}</label><div className="segmented"><button className={mode==="play"?"active":""} onClick={()=>setMode("play")}>{m.common.play}</button><button className={mode==="learn"?"active":""} onClick={()=>setMode("learn")}>{m.common.learn}</button><button className={mode==="experiment"?"active":""} onClick={()=>setMode("experiment")}>{m.common.experiment}</button></div></div>
      {mode==="learn"&&<div className="card" style={{marginTop:14,padding:14}}><p className="muted" style={{fontSize:'.85rem'}}>{m.orbitalRescue.learnBody}</p><div className="formula">ε = v²/2 − μ/r</div></div>}
      {mode==="experiment"&&<div className="card" style={{marginTop:14,padding:14}}><p className="muted" style={{fontSize:'.85rem'}}>{m.orbitalRescue.experimentCopy}</p><div className="miniGrid"><div className="field"><label>{m.orbitalRescue.startAltitude} (km)</label><input className="numberInput" type="number" value={experiment.altitudeKm} onChange={e=>setExperiment(v=>({...v,altitudeKm:Number(e.target.value)}))}/></div><div className="field"><label>{m.orbitalRescue.targetAltitude} (km)</label><input className="numberInput" type="number" value={experiment.targetAltitudeKm} onChange={e=>setExperiment(v=>({...v,targetAltitudeKm:Number(e.target.value)}))}/></div><div className="field"><label>{m.common.spacecraftMass} (kg)</label><input className="numberInput" type="number" value={experiment.dryMass} onChange={e=>setExperiment(v=>({...v,dryMass:Number(e.target.value)}))}/></div><div className="field"><label>{m.common.fuelMass} (kg)</label><input className="numberInput" type="number" value={experiment.fuelMass} onChange={e=>setExperiment(v=>({...v,fuelMass:Number(e.target.value)}))}/></div><div className="field"><label>{m.common.maxThrust} (N)</label><input className="numberInput" type="number" value={experiment.maxThrust} onChange={e=>setExperiment(v=>({...v,maxThrust:Number(e.target.value)}))}/></div></div><button className="button" style={{marginTop:10}} onClick={applyExperiment}>{m.common.applyRestart}</button></div>}
      <div className="controlGroup"><label>{m.common.timeScale}</label><select className="langSelect" value={timeScale} onChange={e=>setTimeScale(Number(e.target.value))}><option value="1">1×</option><option value="10">10×</option><option value="25">25×</option><option value="50">50×</option></select></div><div className="actions"><button className="button" onClick={()=>setPaused(v=>!v)}>{paused?m.common.resume:m.common.pause}</button><button className="button" onClick={reset}>{m.common.restart}</button></div>
    </aside></main>
}
