import type { Locale } from "@/lib/i18n/config";

export const moleculeKitSimSlugs = ["molecule-builder-3d", "molecular-geometry-3d"] as const;

export type MoleculeKitCopy = {
  title: string;
  metaTitle: string;
  metaDescription: string;
  keywords: string[];
  partOfBadge: string;
  heroEyebrowSuffix: string;
  lede: string;
  ctaPrimary: string;
  ctaSecondary: (subjectName: string) => string;
  whatEyebrow: string;
  whatTitle: string;
  bullets: string[];
  kitEyebrow: string;
  kitTitle: string;
  openLab: string;
  faqEyebrow: string;
  faqTitle: string;
  faq: { q: string; a: string }[];
  banner: { newLabel: string; title: string; body: string; cta: string };
  // The VSEPR chart and per-molecule reference pages are English-only for now.
  chart: { eyebrow: string; title: string; body: string; cta: string };
};

export const moleculeKitCopy: Record<Locale, MoleculeKitCopy> = {
  en: {
    title: "Molecule Kit",
    metaTitle: "Molecule Kit: Build & Explore 3D Molecules Free",
    metaDescription: "Build stable molecules and predict their 3D shape with the free Molecule Kit — two interactive labs covering valence, bonding, VSEPR geometry, and bond angles. No sign-up required.",
    keywords: ["molecule kit", "molecule builder 3D", "molecular geometry simulator", "build molecules game", "VSEPR simulator"],
    partOfBadge: "Part of the Molecule Kit",
    heroEyebrowSuffix: "Interactive 3D lab kit",
    lede: "Build real molecules atom by atom, then predict how their shape forms. The Molecule Kit pairs two free, interactive 3D labs covering valence, bonding, VSEPR reasoning, and bond angles — no sign-up required.",
    ctaPrimary: "Start building molecules",
    ctaSecondary: (s) => `Browse all ${s} labs`,
    whatEyebrow: "What you can do in the Molecule Kit",
    whatTitle: "Two labs, one connected idea: structure predicts shape",
    bullets: [
      "Build stable molecules atom by atom by satisfying valence and common bonding patterns.",
      "Predict 3D molecular geometry from electron-group count using VSEPR reasoning.",
      "Rotate and inspect 3D models to compare electron-domain geometry with the observed molecular shape.",
      "See how lone pairs push on bonding pairs and change bond angles and overall shape.",
      "Move between building and predicting to test whether a molecule you construct matches its predicted shape.",
      "Built for grades 8–12, free forever, no sign-up required.",
    ],
    kitEyebrow: "In this kit",
    kitTitle: "The two labs",
    openLab: "Open lab",
    faqEyebrow: "Quick answers",
    faqTitle: "Common questions",
    faq: [
      { q: "What is included in the Molecule Kit?", a: "The Molecule Kit pairs two free 3D labs: Molecule Builder 3D, where you construct molecules from valence and bonding rules, and Molecular Geometry 3D Explorer, where you predict 3D molecular shape from VSEPR reasoning." },
      { q: "Do I need to sign up to use it?", a: "No. Both labs in the Molecule Kit run free in your browser with no account required." },
      { q: "What grade level is the Molecule Kit for?", a: "The Molecule Kit is designed for grades 8–12 chemistry, covering valence, bonding, and VSEPR molecular geometry." },
      { q: "Is the Molecule Kit part of a larger chemistry collection?", a: "Yes. Both labs also live in the full Chemistry subject, which includes 13 interactive labs covering reactions, solutions, gases, and more." },
    ],
    banner: { newLabel: "New", title: "Molecule Kit: build & explore 3D molecules", body: "Construct molecules from valence and bonding rules, then predict their 3D shape with VSEPR reasoning — two free interactive labs in one kit.", cta: "Explore the Molecule Kit" },
    chart: { eyebrow: "Reference", title: "VSEPR shapes chart and 3D molecule library", body: "Look up the molecular geometry, bond angle, hybridization, and polarity of more than 100 molecules and ions, each with a rotatable 3D model.", cta: "Open the VSEPR shapes chart" },
  },
  es: {
    title: "Kit de Moléculas",
    metaTitle: "Kit de Moléculas: construye y explora moléculas 3D gratis",
    metaDescription: "Construye moléculas estables y predice su forma en 3D con el Kit de Moléculas, gratuito — dos laboratorios interactivos sobre valencia, enlaces, geometría VSEPR y ángulos de enlace. Sin registro.",
    keywords: ["kit de moléculas", "construir moléculas 3D", "simulador de geometría molecular", "juego para construir moléculas", "simulador VSEPR"],
    partOfBadge: "Parte del Kit de Moléculas",
    heroEyebrowSuffix: "Kit de laboratorio 3D interactivo",
    lede: "Construye moléculas reales átomo a átomo y luego predice cómo se forma su geometría. El Kit de Moléculas combina dos laboratorios 3D gratuitos e interactivos sobre valencia, enlaces, razonamiento VSEPR y ángulos de enlace — sin necesidad de registrarte.",
    ctaPrimary: "Empieza a construir moléculas",
    ctaSecondary: (s) => `Ver todos los laboratorios de ${s}`,
    whatEyebrow: "Qué puedes hacer en el Kit de Moléculas",
    whatTitle: "Dos laboratorios, una misma idea: la estructura predice la forma",
    bullets: [
      "Construye moléculas estables átomo a átomo cumpliendo las reglas de valencia y los patrones de enlace habituales.",
      "Predice la geometría molecular en 3D a partir del número de grupos de electrones usando el razonamiento VSEPR.",
      "Gira e inspecciona modelos 3D para comparar la geometría de dominios electrónicos con la forma molecular observada.",
      "Observa cómo los pares solitarios empujan a los pares de enlace y cambian los ángulos de enlace y la forma general.",
      "Alterna entre construir y predecir para comprobar si la molécula que construyes coincide con la forma prevista.",
      "Pensado para los cursos 8.º–12.º, gratis para siempre y sin necesidad de registrarte.",
    ],
    kitEyebrow: "En este kit",
    kitTitle: "Los dos laboratorios",
    openLab: "Abrir laboratorio",
    faqEyebrow: "Respuestas rápidas",
    faqTitle: "Preguntas frecuentes",
    faq: [
      { q: "¿Qué incluye el Kit de Moléculas?", a: "El Kit de Moléculas combina dos laboratorios 3D gratuitos: Molecule Builder 3D, donde construyes moléculas siguiendo las reglas de valencia y enlace, y Molecular Geometry 3D Explorer, donde predices la forma molecular en 3D con el razonamiento VSEPR." },
      { q: "¿Necesito registrarme para usarlo?", a: "No. Los dos laboratorios del Kit de Moléculas funcionan gratis en tu navegador, sin necesidad de crear una cuenta." },
      { q: "¿Para qué nivel educativo es el Kit de Moléculas?", a: "El Kit de Moléculas está pensado para química de los cursos 8.º a 12.º, y cubre valencia, enlaces y geometría molecular VSEPR." },
      { q: "¿El Kit de Moléculas forma parte de una colección más amplia de química?", a: "Sí. Los dos laboratorios también forman parte de la materia completa de Química, que incluye 13 laboratorios interactivos sobre reacciones, disoluciones, gases y mucho más." },
    ],
    banner: { newLabel: "Nuevo", title: "Kit de Moléculas: construye y explora moléculas 3D", body: "Construye moléculas siguiendo las reglas de valencia y enlace, y luego predice su forma en 3D con el razonamiento VSEPR — dos laboratorios interactivos gratuitos en un solo kit.", cta: "Explorar el Kit de Moléculas" },
    chart: { eyebrow: "Referencia", title: "Tabla de formas VSEPR y biblioteca de moléculas 3D", body: "Consulta la geometría molecular, el ángulo de enlace, la hibridación y la polaridad de más de 100 moléculas e iones, cada uno con un modelo 3D giratorio (en inglés).", cta: "Abrir la tabla VSEPR" },
  },
  fr: {
    title: "Kit Molécules",
    metaTitle: "Kit Molécules : construire et explorer des molécules 3D gratuitement",
    metaDescription: "Construisez des molécules stables et prédisez leur forme en 3D avec le Kit Molécules, gratuit — deux laboratoires interactifs sur la valence, les liaisons, la géométrie VSEPR et les angles de liaison. Aucune inscription requise.",
    keywords: ["kit molécules", "construire des molécules 3D", "simulateur de géométrie moléculaire", "jeu de construction de molécules", "simulateur VSEPR"],
    partOfBadge: "Fait partie du Kit Molécules",
    heroEyebrowSuffix: "Kit de laboratoire 3D interactif",
    lede: "Construisez de vraies molécules atome par atome, puis prédisez comment leur forme se dessine. Le Kit Molécules réunit deux laboratoires 3D gratuits et interactifs sur la valence, les liaisons, le raisonnement VSEPR et les angles de liaison — sans inscription.",
    ctaPrimary: "Commencer à construire des molécules",
    ctaSecondary: (s) => `Voir tous les laboratoires de ${s}`,
    whatEyebrow: "Ce que vous pouvez faire dans le Kit Molécules",
    whatTitle: "Deux laboratoires, une seule idée : la structure prédit la forme",
    bullets: [
      "Construisez des molécules stables atome par atome en respectant la valence et les schémas de liaison courants.",
      "Prédisez la géométrie moléculaire en 3D à partir du nombre de groupes d’électrons grâce au raisonnement VSEPR.",
      "Faites pivoter et inspectez des modèles 3D pour comparer la géométrie des domaines électroniques à la forme moléculaire observée.",
      "Observez comment les doublets non liants repoussent les doublets liants et modifient les angles de liaison et la forme globale.",
      "Alternez entre construction et prédiction pour vérifier si une molécule que vous construisez correspond à sa forme prévue.",
      "Conçu pour les niveaux 8e–12e, gratuit pour toujours, sans inscription.",
    ],
    kitEyebrow: "Dans ce kit",
    kitTitle: "Les deux laboratoires",
    openLab: "Ouvrir le laboratoire",
    faqEyebrow: "Réponses rapides",
    faqTitle: "Questions fréquentes",
    faq: [
      { q: "Que contient le Kit Molécules ?", a: "Le Kit Molécules réunit deux laboratoires 3D gratuits : Molecule Builder 3D, où vous construisez des molécules à partir des règles de valence et de liaison, et Molecular Geometry 3D Explorer, où vous prédisez la forme moléculaire en 3D grâce au raisonnement VSEPR." },
      { q: "Dois-je m’inscrire pour l’utiliser ?", a: "Non. Les deux laboratoires du Kit Molécules fonctionnent gratuitement dans votre navigateur, sans compte requis." },
      { q: "Pour quel niveau scolaire est conçu le Kit Molécules ?", a: "Le Kit Molécules est conçu pour la chimie des niveaux 8e à 12e, et couvre la valence, les liaisons et la géométrie moléculaire VSEPR." },
      { q: "Le Kit Molécules fait-il partie d’une collection de chimie plus large ?", a: "Oui. Les deux laboratoires font aussi partie de la matière Chimie complète, qui comprend 13 laboratoires interactifs sur les réactions, les solutions, les gaz et bien plus." },
    ],
    banner: { newLabel: "Nouveau", title: "Kit Molécules : construire et explorer des molécules 3D", body: "Construisez des molécules à partir des règles de valence et de liaison, puis prédisez leur forme en 3D grâce au raisonnement VSEPR — deux laboratoires interactifs gratuits dans un seul kit.", cta: "Découvrir le Kit Molécules" },
    chart: { eyebrow: "Référence", title: "Tableau des formes VSEPR et bibliothèque de molécules 3D", body: "Consultez la géométrie moléculaire, l’angle de liaison, l’hybridation et la polarité de plus de 100 molécules et ions, chacun avec un modèle 3D orientable (en anglais).", cta: "Ouvrir le tableau VSEPR" },
  },
  de: {
    title: "Molekül-Kit",
    metaTitle: "Molekül-Kit: 3D-Moleküle kostenlos bauen und erkunden",
    metaDescription: "Baue stabile Moleküle und sage ihre 3D-Form voraus – mit dem kostenlosen Molekül-Kit, zwei interaktiven Laboren zu Valenz, Bindungen, VSEPR-Geometrie und Bindungswinkeln. Keine Anmeldung nötig.",
    keywords: ["molekül-kit", "moleküle 3D bauen", "simulator molekülgeometrie", "spiel moleküle bauen", "VSEPR simulator"],
    partOfBadge: "Teil des Molekül-Kits",
    heroEyebrowSuffix: "Interaktives 3D-Labor-Kit",
    lede: "Baue echte Moleküle Atom für Atom und sage dann voraus, wie ihre Form entsteht. Das Molekül-Kit vereint zwei kostenlose, interaktive 3D-Labore zu Valenz, Bindungen, VSEPR-Logik und Bindungswinkeln – ohne Anmeldung.",
    ctaPrimary: "Mit dem Molekülbau beginnen",
    ctaSecondary: (s) => `Alle ${s}-Labore ansehen`,
    whatEyebrow: "Was du im Molekül-Kit machen kannst",
    whatTitle: "Zwei Labore, eine verbundene Idee: Struktur sagt Form voraus",
    bullets: [
      "Baue stabile Moleküle Atom für Atom, indem du Valenz und gängige Bindungsmuster erfüllst.",
      "Sage die 3D-Molekülgeometrie anhand der Anzahl der Elektronengruppen mit VSEPR-Logik voraus.",
      "Drehe und untersuche 3D-Modelle, um die Elektronendomänen-Geometrie mit der beobachteten Molekülform zu vergleichen.",
      "Sieh, wie freie Elektronenpaare auf Bindungspaare drücken und Bindungswinkel sowie Gesamtform verändern.",
      "Wechsle zwischen Bauen und Vorhersagen, um zu testen, ob ein von dir gebautes Molekül seiner vorhergesagten Form entspricht.",
      "Für die Klassenstufen 8–12 konzipiert, für immer kostenlos, keine Anmeldung nötig.",
    ],
    kitEyebrow: "In diesem Kit",
    kitTitle: "Die beiden Labore",
    openLab: "Labor öffnen",
    faqEyebrow: "Kurz beantwortet",
    faqTitle: "Häufige Fragen",
    faq: [
      { q: "Was enthält das Molekül-Kit?", a: "Das Molekül-Kit vereint zwei kostenlose 3D-Labore: Molecule Builder 3D, in dem du Moleküle nach Valenz- und Bindungsregeln baust, und Molecular Geometry 3D Explorer, in dem du die 3D-Molekülform mit VSEPR-Logik vorhersagst." },
      { q: "Muss ich mich anmelden, um es zu nutzen?", a: "Nein. Beide Labore im Molekül-Kit laufen kostenlos im Browser, ganz ohne Konto." },
      { q: "Für welche Klassenstufe ist das Molekül-Kit gedacht?", a: "Das Molekül-Kit ist für den Chemieunterricht der Klassenstufen 8–12 konzipiert und behandelt Valenz, Bindungen und VSEPR-Molekülgeometrie." },
      { q: "Ist das Molekül-Kit Teil einer größeren Chemie-Sammlung?", a: "Ja. Beide Labore gehören auch zum vollständigen Fach Chemie mit 13 interaktiven Laboren zu Reaktionen, Lösungen, Gasen und mehr." },
    ],
    banner: { newLabel: "Neu", title: "Molekül-Kit: 3D-Moleküle bauen und erkunden", body: "Baue Moleküle nach Valenz- und Bindungsregeln und sage dann ihre 3D-Form mit VSEPR-Logik voraus – zwei kostenlose interaktive Labore in einem Kit.", cta: "Molekül-Kit entdecken" },
    chart: { eyebrow: "Nachschlagen", title: "VSEPR-Formentabelle und 3D-Molekülbibliothek", body: "Schlage Molekülgeometrie, Bindungswinkel, Hybridisierung und Polarität von über 100 Molekülen und Ionen nach – jeweils mit drehbarem 3D-Modell (auf Englisch).", cta: "VSEPR-Tabelle öffnen" },
  },
  pt: {
    title: "Kit de Moléculas",
    metaTitle: "Kit de Moléculas: construa e explore moléculas 3D grátis",
    metaDescription: "Construa moléculas estáveis e preveja sua forma em 3D com o Kit de Moléculas, gratuito — dois laboratórios interativos sobre valência, ligações, geometria VSEPR e ângulos de ligação. Sem necessidade de cadastro.",
    keywords: ["kit de moléculas", "construir moléculas 3D", "simulador de geometria molecular", "jogo de construir moléculas", "simulador VSEPR"],
    partOfBadge: "Parte do Kit de Moléculas",
    heroEyebrowSuffix: "Kit de laboratório 3D interativo",
    lede: "Construa moléculas reais átomo por átomo e depois preveja como sua forma se forma. O Kit de Moléculas reúne dois laboratórios 3D gratuitos e interativos sobre valência, ligações, raciocínio VSEPR e ângulos de ligação — sem necessidade de cadastro.",
    ctaPrimary: "Comece a construir moléculas",
    ctaSecondary: (s) => `Ver todos os laboratórios de ${s}`,
    whatEyebrow: "O que você pode fazer no Kit de Moléculas",
    whatTitle: "Dois laboratórios, uma ideia conectada: a estrutura prevê a forma",
    bullets: [
      "Construa moléculas estáveis átomo por átomo respeitando a valência e os padrões comuns de ligação.",
      "Preveja a geometria molecular em 3D a partir do número de grupos de elétrons usando o raciocínio VSEPR.",
      "Gire e inspecione modelos 3D para comparar a geometria dos domínios eletrônicos com a forma molecular observada.",
      "Veja como os pares isolados empurram os pares de ligação e mudam os ângulos de ligação e a forma geral.",
      "Alterne entre construir e prever para testar se a molécula que você monta corresponde à forma prevista.",
      "Feito para os anos 8 a 12, gratuito para sempre, sem necessidade de cadastro.",
    ],
    kitEyebrow: "Neste kit",
    kitTitle: "Os dois laboratórios",
    openLab: "Abrir laboratório",
    faqEyebrow: "Respostas rápidas",
    faqTitle: "Perguntas frequentes",
    faq: [
      { q: "O que está incluído no Kit de Moléculas?", a: "O Kit de Moléculas reúne dois laboratórios 3D gratuitos: Molecule Builder 3D, em que você constrói moléculas a partir das regras de valência e ligação, e Molecular Geometry 3D Explorer, em que você prevê a forma molecular em 3D usando o raciocínio VSEPR." },
      { q: "Preciso me cadastrar para usar?", a: "Não. Os dois laboratórios do Kit de Moléculas funcionam gratuitamente no navegador, sem necessidade de criar conta." },
      { q: "Para qual nível escolar o Kit de Moléculas é indicado?", a: "O Kit de Moléculas foi criado para a química dos anos 8 a 12, cobrindo valência, ligações e geometria molecular VSEPR." },
      { q: "O Kit de Moléculas faz parte de uma coleção maior de química?", a: "Sim. Os dois laboratórios também fazem parte da disciplina completa de Química, que inclui 13 laboratórios interativos sobre reações, soluções, gases e muito mais." },
    ],
    banner: { newLabel: "Novo", title: "Kit de Moléculas: construa e explore moléculas 3D", body: "Construa moléculas a partir das regras de valência e ligação, depois preveja sua forma em 3D com o raciocínio VSEPR — dois laboratórios interativos gratuitos em um só kit.", cta: "Explorar o Kit de Moléculas" },
    chart: { eyebrow: "Referência", title: "Tabela de formas VSEPR e biblioteca de moléculas 3D", body: "Consulte a geometria molecular, o ângulo de ligação, a hibridização e a polaridade de mais de 100 moléculas e íons, cada um com um modelo 3D giratório (em inglês).", cta: "Abrir a tabela VSEPR" },
  },
  ru: {
    title: "Молекулярный набор",
    metaTitle: "Молекулярный набор: бесплатно стройте и изучайте 3D-молекулы",
    metaDescription: "Стройте устойчивые молекулы и предсказывайте их 3D-форму с помощью бесплатного «Молекулярного набора» — две интерактивные лаборатории по валентности, связям, геометрии VSEPR и углам связей. Регистрация не требуется.",
    keywords: ["молекулярный набор", "конструктор молекул 3D", "симулятор молекулярной геометрии", "игра построй молекулу", "симулятор VSEPR"],
    partOfBadge: "Часть Молекулярного набора",
    heroEyebrowSuffix: "Интерактивный 3D-набор лабораторий",
    lede: "Стройте настоящие молекулы атом за атомом, а затем предсказывайте, как формируется их форма. «Молекулярный набор» объединяет две бесплатные интерактивные 3D-лаборатории по валентности, связям, логике VSEPR и углам связей — без регистрации.",
    ctaPrimary: "Начать собирать молекулы",
    ctaSecondary: (s) => `Все лаборатории по предмету «${s}»`,
    whatEyebrow: "Что можно делать в Молекулярном наборе",
    whatTitle: "Две лаборатории, одна общая идея: структура предсказывает форму",
    bullets: [
      "Стройте устойчивые молекулы атом за атомом, соблюдая валентность и типичные схемы связей.",
      "Предсказывайте 3D-геометрию молекулы по числу электронных групп с помощью логики VSEPR.",
      "Вращайте и изучайте 3D-модели, сравнивая электронно-доменную геометрию с наблюдаемой формой молекулы.",
      "Смотрите, как неподелённые пары отталкивают связывающие пары, меняя углы связей и общую форму.",
      "Переключайтесь между построением и предсказанием, чтобы проверить, совпадает ли построенная молекула с предсказанной формой.",
      "Создано для 8–12 классов, бесплатно навсегда, без регистрации.",
    ],
    kitEyebrow: "В этом наборе",
    kitTitle: "Две лаборатории",
    openLab: "Открыть лабораторию",
    faqEyebrow: "Короткие ответы",
    faqTitle: "Частые вопросы",
    faq: [
      { q: "Что входит в Молекулярный набор?", a: "Молекулярный набор объединяет две бесплатные 3D-лаборатории: Molecule Builder 3D, где вы строите молекулы по правилам валентности и связей, и Molecular Geometry 3D Explorer, где вы предсказываете 3D-форму молекулы с помощью логики VSEPR." },
      { q: "Нужна ли регистрация?", a: "Нет. Обе лаборатории Молекулярного набора работают бесплатно прямо в браузере, без создания аккаунта." },
      { q: "Для какого класса подходит Молекулярный набор?", a: "Молекулярный набор рассчитан на химию 8–12 классов и охватывает валентность, связи и молекулярную геометрию VSEPR." },
      { q: "Входит ли Молекулярный набор в более крупную коллекцию по химии?", a: "Да. Обе лаборатории также входят в полный курс химии, который включает 13 интерактивных лабораторий по реакциям, растворам, газам и другим темам." },
    ],
    banner: { newLabel: "Новинка", title: "Молекулярный набор: стройте и изучайте 3D-молекулы", body: "Стройте молекулы по правилам валентности и связей, а затем предсказывайте их 3D-форму с помощью логики VSEPR — две бесплатные интерактивные лаборатории в одном наборе.", cta: "Открыть Молекулярный набор" },
    chart: { eyebrow: "Справочник", title: "Таблица форм VSEPR и библиотека 3D-молекул", body: "Геометрия, валентный угол, гибридизация и полярность более 100 молекул и ионов — у каждой вращаемая 3D-модель (на английском).", cta: "Открыть таблицу VSEPR" },
  },
  ja: {
    title: "分子キット",
    metaTitle: "分子キット：3D分子を無料で組み立てて探索",
    metaDescription: "無料の「分子キット」で安定した分子を組み立て、3D形状を予測しよう。原子価、結合、VSEPR構造、結合角を扱う2つのインタラクティブラボ。登録不要。",
    keywords: ["分子キット", "分子ビルダー3D", "分子構造シミュレーター", "分子を作るゲーム", "VSEPRシミュレーター"],
    partOfBadge: "分子キットの一部",
    heroEyebrowSuffix: "インタラクティブ3Dラボキット",
    lede: "原子を1つずつ組み合わせて実際の分子を作り、その形がどう決まるかを予測しよう。分子キットは、原子価・結合・VSEPR推論・結合角を扱う2つの無料インタラクティブ3Dラボをまとめたものです。登録は不要です。",
    ctaPrimary: "分子作りを始める",
    ctaSecondary: (s) => `${s}のラボをすべて見る`,
    whatEyebrow: "分子キットでできること",
    whatTitle: "2つのラボ、1つのつながったアイデア：構造が形を予測する",
    bullets: [
      "原子価と一般的な結合パターンを満たしながら、原子を1つずつ組み合わせて安定した分子を作る。",
      "VSEPR推論を使って、電子グループの数から3D分子形状を予測する。",
      "3Dモデルを回転させて調べ、電子ドメイン形状と観察された分子形状を比較する。",
      "非共有電子対が共有電子対を押しのけ、結合角や全体の形を変える様子を確認する。",
      "組み立てと予測を行き来しながら、作った分子が予測した形と一致するかを検証する。",
      "8〜12年生向けに設計、永久無料、登録不要。",
    ],
    kitEyebrow: "このキットの内容",
    kitTitle: "2つのラボ",
    openLab: "ラボを開く",
    faqEyebrow: "クイック回答",
    faqTitle: "よくある質問",
    faq: [
      { q: "分子キットには何が含まれていますか？", a: "分子キットは2つの無料3Dラボをまとめたものです。原子価・結合ルールから分子を組み立てるMolecule Builder 3Dと、VSEPR推論で3D分子形状を予測するMolecular Geometry 3D Explorerです。" },
      { q: "利用に登録は必要ですか？", a: "いいえ。分子キットの両方のラボはブラウザ上で無料で動作し、アカウント登録は不要です。" },
      { q: "分子キットはどの学年向けですか？", a: "分子キットは8〜12年生の化学向けに設計されており、原子価、結合、VSEPR分子形状を扱います。" },
      { q: "分子キットはより大きな化学コレクションの一部ですか？", a: "はい。どちらのラボも、反応・溶液・気体などを扱う13のインタラクティブラボを含む化学科目全体の一部でもあります。" },
    ],
    banner: { newLabel: "新着", title: "分子キット：3D分子を組み立てて探索", body: "原子価と結合ルールから分子を組み立て、VSEPR推論でその3D形状を予測しよう。1つのキットに2つの無料インタラクティブラボ。", cta: "分子キットを見る" },
    chart: { eyebrow: "リファレンス", title: "VSEPR形状表と3D分子ライブラリ", body: "100種類以上の分子・イオンについて、分子の形、結合角、混成軌道、極性を調べられます。すべて回転できる3Dモデル付き（英語）。", cta: "VSEPR形状表を開く" },
  },
  zh: {
    title: "分子工具包",
    metaTitle: "分子工具包：免费搭建并探索3D分子",
    metaDescription: "使用免费的分子工具包搭建稳定分子并预测其3D形状——两个互动实验，涵盖化合价、化学键、VSEPR几何构型和键角。无需注册。",
    keywords: ["分子工具包", "3D分子构建器", "分子几何模拟器", "搭建分子游戏", "VSEPR模拟器"],
    partOfBadge: "分子工具包的一部分",
    heroEyebrowSuffix: "互动3D实验工具包",
    lede: "逐个原子搭建真实分子，然后预测其形状是如何形成的。分子工具包包含两个免费的互动3D实验，涵盖化合价、化学键、VSEPR推理和键角——无需注册。",
    ctaPrimary: "开始搭建分子",
    ctaSecondary: (s) => `浏览全部${s}实验`,
    whatEyebrow: "在分子工具包中你可以做什么",
    whatTitle: "两个实验，一个共同的理念：结构决定形状",
    bullets: [
      "逐个原子搭建分子，同时满足化合价和常见的成键规律，构建稳定分子。",
      "利用VSEPR推理，根据电子组数量预测3D分子几何构型。",
      "旋转并检查3D模型，比较电子域几何构型与实际观察到的分子形状。",
      "观察孤对电子如何推挤成键电子对，从而改变键角和整体形状。",
      "在搭建与预测之间切换，检验你搭建的分子是否与预测的形状一致。",
      "面向8至12年级设计，永久免费，无需注册。",
    ],
    kitEyebrow: "工具包内容",
    kitTitle: "两个实验",
    openLab: "打开实验",
    faqEyebrow: "快速问答",
    faqTitle: "常见问题",
    faq: [
      { q: "分子工具包包含哪些内容？", a: "分子工具包包含两个免费的3D实验：Molecule Builder 3D（按照化合价和成键规律搭建分子）和Molecular Geometry 3D Explorer（利用VSEPR推理预测3D分子形状）。" },
      { q: "使用需要注册吗？", a: "不需要。分子工具包中的两个实验都可在浏览器中免费使用，无需注册账号。" },
      { q: "分子工具包适合哪个年级？", a: "分子工具包面向8至12年级的化学课程设计，涵盖化合价、化学键和VSEPR分子几何构型。" },
      { q: "分子工具包是更大化学合集的一部分吗？", a: "是的。这两个实验也属于完整的化学学科，其中包含13个涵盖反应、溶液、气体等内容的互动实验。" },
    ],
    banner: { newLabel: "新上线", title: "分子工具包：搭建并探索3D分子", body: "按照化合价和成键规律搭建分子，然后用VSEPR推理预测其3D形状——一个工具包内含两个免费互动实验。", cta: "探索分子工具包" },
    chart: { eyebrow: "参考资料", title: "VSEPR构型表与3D分子库", body: "查阅100多种分子和离子的分子构型、键角、杂化方式和极性，每种都配有可旋转的3D模型（英文）。", cta: "打开VSEPR构型表" },
  },
  ar: {
    title: "مجموعة الجزيئات",
    metaTitle: "مجموعة الجزيئات: ابنِ واستكشف جزيئات ثلاثية الأبعاد مجانًا",
    metaDescription: "ابنِ جزيئات مستقرة وتوقّع شكلها ثلاثي الأبعاد باستخدام مجموعة الجزيئات المجانية — مختبران تفاعليان يغطيان التكافؤ والروابط وهندسة VSEPR وزوايا الروابط. لا حاجة لإنشاء حساب.",
    keywords: ["مجموعة الجزيئات", "بناء جزيئات ثلاثية الأبعاد", "محاكي الهندسة الجزيئية", "لعبة بناء الجزيئات", "محاكي VSEPR"],
    partOfBadge: "جزء من مجموعة الجزيئات",
    heroEyebrowSuffix: "مجموعة مختبر تفاعلي ثلاثي الأبعاد",
    lede: "ابنِ جزيئات حقيقية ذرة تلو الأخرى، ثم توقّع كيف يتشكل شكلها. تجمع مجموعة الجزيئات بين مختبرين مجانيين تفاعليين ثلاثيي الأبعاد يغطيان التكافؤ والروابط ومنطق VSEPR وزوايا الروابط — دون الحاجة لإنشاء حساب.",
    ctaPrimary: "ابدأ ببناء الجزيئات",
    ctaSecondary: (s) => `تصفّح كل مختبرات ${s}`,
    whatEyebrow: "ما يمكنك فعله في مجموعة الجزيئات",
    whatTitle: "مختبران، فكرة واحدة مترابطة: البنية تتنبأ بالشكل",
    bullets: [
      "ابنِ جزيئات مستقرة ذرة تلو الأخرى مع الالتزام بالتكافؤ وأنماط الترابط الشائعة.",
      "توقّع الهندسة الجزيئية ثلاثية الأبعاد من عدد المجموعات الإلكترونية باستخدام منطق VSEPR.",
      "أدر نماذج ثلاثية الأبعاد وافحصها لمقارنة هندسة المجالات الإلكترونية بالشكل الجزيئي الملاحظ.",
      "شاهد كيف تدفع الأزواج غير الرابطة الأزواج الرابطة، فتغيّر زوايا الروابط والشكل العام.",
      "تنقّل بين البناء والتوقّع لاختبار ما إذا كان الجزيء الذي بنيته يطابق الشكل المتوقع.",
      "مصممة لصفوف 8 إلى 12، مجانية للأبد، ولا تتطلب إنشاء حساب.",
    ],
    kitEyebrow: "في هذه المجموعة",
    kitTitle: "المختبران",
    openLab: "افتح المختبر",
    faqEyebrow: "إجابات سريعة",
    faqTitle: "أسئلة شائعة",
    faq: [
      { q: "ماذا تتضمن مجموعة الجزيئات؟", a: "تجمع مجموعة الجزيئات بين مختبرين مجانيين ثلاثيي الأبعاد: Molecule Builder 3D، حيث تبني الجزيئات وفق قواعد التكافؤ والترابط، وMolecular Geometry 3D Explorer، حيث تتوقّع الشكل الجزيئي ثلاثي الأبعاد باستخدام منطق VSEPR." },
      { q: "هل أحتاج إلى إنشاء حساب لاستخدامها؟", a: "لا. يعمل كلا المختبرين في مجموعة الجزيئات مجانًا في المتصفح دون الحاجة لإنشاء حساب." },
      { q: "لأي صف دراسي صُممت مجموعة الجزيئات؟", a: "صُممت مجموعة الجزيئات لكيمياء الصفوف 8 إلى 12، وتغطي التكافؤ والروابط والهندسة الجزيئية وفق VSEPR." },
      { q: "هل مجموعة الجزيئات جزء من مجموعة كيمياء أكبر؟", a: "نعم. يندرج كلا المختبرين أيضًا ضمن مادة الكيمياء الكاملة، التي تضم 13 مختبرًا تفاعليًا حول التفاعلات والمحاليل والغازات وغيرها." },
    ],
    banner: { newLabel: "جديد", title: "مجموعة الجزيئات: ابنِ واستكشف جزيئات ثلاثية الأبعاد", body: "ابنِ الجزيئات وفق قواعد التكافؤ والترابط، ثم توقّع شكلها ثلاثي الأبعاد باستخدام منطق VSEPR — مختبران تفاعليان مجانيان في مجموعة واحدة.", cta: "استكشف مجموعة الجزيئات" },
    chart: { eyebrow: "مرجع", title: "جدول أشكال VSEPR ومكتبة الجزيئات ثلاثية الأبعاد", body: "اطّلع على الشكل الهندسي وزاوية الرابطة والتهجين والقطبية لأكثر من 100 جزيء وأيون، لكلٍّ منها نموذج ثلاثي الأبعاد قابل للتدوير (بالإنجليزية).", cta: "افتح جدول VSEPR" },
  },
};

export function getMoleculeKitCopy(locale: Locale) {
  return moleculeKitCopy[locale];
}
