import Link from "next/link";
import { notFound } from "next/navigation";
import { breadcrumbJsonLd, jsonLd, localizedMetadata, siteName, siteUrl } from "@/lib/seo/metadata";
import { activities } from "@/lib/simulations/environmentalLabs/model";
import { buildTools } from "@/lib/simulations/environmentalLabs/builder";
import { subjectsCatalog } from "@/lib/subjects/catalog";
import { BuildIcon } from "@/components/subjects/environmental/BuildIcon";
import { GameControlIcon, type ControlKind } from "@/components/subjects/environmental/GameControlIcon";
import styles from "./guide.module.css";
const path="/guides/environmental-city-builder";
const title="Environmental City Builder: How to Play & Run an Experiment";
const description="Learn to build your environmental city, place projects on valid plots, run all ten science labs, and compare results with saved baselines.";
export function generateStaticParams(){return [{locale:"en"}];}
export async function generateMetadata({params}:{params:Promise<{locale:string}>}){const {locale}=await params;if(locale!=="en")return {};return localizedMetadata("en",path,title,description,{type:"article",englishOnly:true,keywords:["environmental city builder guide","science simulation game","environmental science labs","how to use LearnerKits"]});}
const controls:[ControlKind,string,string][]=[
 ["play","Run / pause","Advance model time or pause to inspect a result. Editing a project starts the new scenario at time zero."],
 ["step","Step","Advance by one recorded sample. A step is a model interval; its duration depends on the lab."],
 ["fast","Final result","Jump to the end of the experiment. This completes the data needed to save a baseline."],
 ["speed","Speed","Cycle between 1×, 2× and 4× playback. Speed changes viewing time, not the scientific results."],
 ["move","Move","Drag a project you built onto another available plot. Its contribution to the model stays the same."],
 ["remove","Remove","Select the bulldozer, then tap a project you built to reverse its contribution. Starting scenery is fixed."],
 ["undo","Undo / redo","Recover or reapply a recent edit, including a reset or a change of scenario."],
 ["reset","Reset city","Restore the lab’s starting inputs and remove your projects. Undo can recover that reset while the page stays open."],
 ["conditions","Conditions","Set weather and other background inputs, load a prepared scenario, or place projects using row and column numbers."],
 ["graphs","Graphs","Inspect measurements, finish a run, save a baseline for comparison, and download the complete experiment as CSV."],
 ["plus","Camera","Use the magnifiers to zoom, curved arrows to rotate, the house to restore the view, and corner brackets for fullscreen."],
 ["labs","More labs","Explore the other environmental worlds. Leaving the simulation clears its current in-memory build."],
];
const missions:Record<string,string>={
 "greenhouse-effect-simulator":"Run the starting climate, save its temperature curve, then add one CO₂ source. Keep methane and reflectivity fixed. Compare the temperature response at the same model year and explain why the response develops over time.",
 "carbon-cycle-simulator":"Save a baseline, then add forest restoration while keeping emissions unchanged. Compare atmospheric accumulation across the full run. Test whether a stronger sink slows growth or actually reverses it; those are different outcomes.",
 "sea-level-rise-simulator":"Add groundwater pumping to the baseline scenario and compare relative sea level. The pumping tool changes subsidence. Use the separate thermal, ice and land-motion contributions to explain why local relative sea level can differ from ocean rise alone.",
 "ocean-acidification-simulator":"Change one atmospheric CO₂ scenario at a time and compare pH and carbonate-related readings. Then restore the baseline and test runoff treatment separately. Distinguish the atmospheric input from the local respiration pressure.",
 "renewable-energy-grid-simulator":"Run a day with the starting grid. Add a solar park, inspect supply against demand, then try battery storage as a separate change. Look at when energy is missing, not just total capacity. The battery begins empty and needs surplus energy before it can discharge.",
 "air-pollution-smog-simulator":"Save the starting air-quality curve and add public transport. Hold wind and other conditions constant. Compare particle and ozone readings separately; a change in one pollutant does not prove the other changed by the same amount.",
 "deforestation-water-cycle-simulator":"Run the starting storm, then add a tree grove under the same rain conditions. Compare runoff and infiltration over time. Repeat with compacted soil and explain how vegetation and soil condition act as separate inputs.",
 "biodiversity-habitat-fragmentation":"Keep habitat area fixed and add a wildlife corridor. Compare the occupancy response over time. Next, reset and add habitat instead. Use the two comparisons to distinguish more habitat from better connectivity in this simplified model.",
 "urban-heat-island-simulator":"Complete the starting day, save it, then add one tree grove. Compare local temperature at the same hour. Reset and try a cool-roof district instead; hold regional weather fixed so you can attribute the change to the project.",
 "climate-resilience-city-builder":"Keep the hazard setting fixed and compare drainage with wetlands, one investment at a time. Inspect ponding and the other outcome measures. Then create a combined plan inside the 100-point budget and explain its trade-offs rather than looking for a universal best city.",
};
export default async function CityGuide({params}:{params:Promise<{locale:string}>}){
 const {locale}=await params;if(locale!=="en")notFound();
 const schema={"@context":"https://schema.org","@type":["Article","LearningResource"],headline:title,description,url:`${siteUrl}/en${path}`,inLanguage:"en",isAccessibleForFree:true,learningResourceType:"Game guide",educationalUse:["instruction","practice"],publisher:{"@type":"Organization",name:siteName,url:siteUrl},mainEntityOfPage:`${siteUrl}/en${path}`};
 const simulations=subjectsCatalog["environmental-science"].simulations;
 return <main className={`container topicGuidePage ${styles.guide}`}>
  <script type="application/ld+json" dangerouslySetInnerHTML={jsonLd(schema)}/>
  <script type="application/ld+json" dangerouslySetInnerHTML={jsonLd(breadcrumbJsonLd("en",[{name:"Science guides",path:"/guides"},{name:"Environmental city builder",path}]))}/>
  <article>
   <header className="topicGuideHero"><Link className="textLink" href="/en/guides">← All science guides</Link><div className="eyebrow">Environmental city builder · Player’s guide</div><h1>Build a city. Test an idea.</h1><p className="topicGuideLead">Your city is a place to investigate environmental science. Place a project, predict its effect, run the model, and use the evidence to explain what changed. This guide takes you from your first tree grove to a fair comparison between two scenarios.</p><div className="topicGuideHeroActions"><Link className="button primary" href="/en/simulations/urban-heat-island-simulator">Start with the urban heat lab</Link><Link className="textLink" href="/en/subjects/environmental-science">Choose another environmental world →</Link></div></header>
   <div className="topicGuideBody">
    <nav className={styles.contents} aria-label="Game guide contents">{[["first-build","First build"],["placement","Drag & drop"],["controls","Controls"],["compare","Compare results"],["missions","Lab missions"],["troubleshooting","Help"]].map(([id,label])=><a key={id} href={`#${id}`}>{label}</a>)}</nav>
    <section className="topicGuideSection" id="first-build"><div className="eyebrow">Your first five minutes</div><h2>Cool the city with a tree grove</h2><p>Open the Urban Heat Island lab. The top cards show the selected moment in model time; they are measurements, not points to collect. The city begins with existing buildings and environmental conditions. Projects in the bottom dock change the scenario.</p>
     <div className={styles.walkthrough}><div><BuildIcon kind="trees"/><strong>1. Choose a project</strong><span>Select Tree grove in the dock. Read its effect: canopy increases by 10 percentage points.</span></div><div><div className={styles.plotDemo}><span/><span/><span/><span/><BuildIcon kind="trees"/><span/></div><strong>2. Find a glowing plot</strong><span>Carry the grove to an open land square. The preview names the project and snaps into its future position.</span></div><div><GameControlIcon kind="play"/><strong>3. Run and inspect</strong><span>Release to build, then press Run. Open Graphs to follow the temperature through the day.</span></div></div>
     <p>For a meaningful experiment, run the original city first and save a baseline before building. If you already placed a grove, use Undo to return to the starting city. You can then compare both designs under the same weather conditions.</p></section>
    <section className="topicGuideSection" id="placement"><h2>Know what you are carrying—and where it fits</h2><p>Each dock item has its own miniature illustration and name. Selecting it highlights suitable empty plots. While you move across the city, a translucent 3D copy follows the chosen plot, and a small card identifies the project. A green preview is a valid location. A red preview includes the reason placement is blocked.</p><ul><li><strong>Mouse or trackpad:</strong> drag a dock item onto the city and release over a green plot. You can also select a tool and click its destination.</li><li><strong>Phone or tablet:</strong> drag the project with your finger, or tap its dock button and then tap a highlighted plot. The second method helps when your finger covers a small square.</li><li><strong>Keyboard:</strong> select a dock button, focus the city map, and use the arrow keys to choose a plot. Enter places the selected project; Delete or Backspace removes a project at that plot. Escape dismisses the preview.</li><li><strong>Plot controls:</strong> open Conditions and use “Place a project by plot number.” Choose the project, column and row, then press Place project. This method also works when the device cannot display the 3D city.</li></ul>
     <p>The expanded city has 16 columns and 16 rows. Water occupies columns 1–3; water projects such as hydropower belong there. Land projects need an empty land plot. Streets, fixed buildings, landscaped edges and your existing projects cannot be built over. Rotating the camera changes the view, while plot coordinates stay attached to the city.</p><p>Scientific limits also matter. A city cannot keep adding canopy beyond the lab’s allowed range. The climate-resilience world has a total investment limit of 100 points. When a limit is reached, the preview explains it; remove a relevant project, undo an edit, or load another starting scenario. An invalid drop leaves the city unchanged. Releasing outside the city cancels the drag.</p></section>
    <section className="topicGuideSection" id="controls"><h2>Meet the game controls</h2><p>The raised illustrated buttons keep the city in view. Hover for camera-control names, or navigate by keyboard to hear each accessible label. Graphs and Conditions open panels over the game.</p><dl className={styles.controls}>{controls.map(([kind,name,detail])=><div key={name}><GameControlIcon kind={kind}/><div><dt>{name}</dt><dd>{detail}</dd></div></div>)}</dl><p>The book button opens this guide in a new tab, preserving your game in the original tab. The current build and saved baseline stay in memory only while that simulation remains open. Download data before navigating away or refreshing if you want a lasting record.</p></section>
    <section className="topicGuideSection" id="compare"><div className="eyebrow">Predict → experiment → explain</div><h2>Make a fair comparison</h2><ol><li><strong>Ask a specific question.</strong> For example: “With the same regional weather, how does one canopy increase affect local temperature at the end of the modeled day?” Choose a measurement before changing the city.</li><li><strong>Complete the starting run.</strong> Press Run and wait, or use Final result. In Graphs, Show full run also reveals the complete experiment. Save baseline becomes available once the run is complete.</li><li><strong>Save the baseline.</strong> This keeps the starting inputs and results for comparison. The graph displays the saved run with dashed lines. Check “Saved baseline inputs” if you forget the conditions you used.</li><li><strong>Change one thing.</strong> Close Graphs and build one project. Construction restarts the new experiment at zero; it does not erase the saved comparison. Keep all other inputs fixed.</li><li><strong>Compare matching times and units.</strong> Finish the new run, open Graphs and select the measurement. Use “Inspect model time” to inspect the same moment in both scenarios. A peak temperature and an end-of-day temperature answer different questions.</li><li><strong>Explain the evidence.</strong> State what you changed, which measurement responded, and whether the direction matched your prediction. Include the model’s limits. Download the CSV to examine its numerical inputs and samples in a spreadsheet.</li></ol><p>Moving a project rearranges the city without changing model totals. It is useful for organizing your layout, but it is not a new scientific treatment. To test a different amount of tree cover or energy capacity, add or remove a project instead.</p></section>
    <section className="topicGuideSection" id="missions"><h2>A starter investigation for every world</h2><p>The same controls work across all ten labs, but each dock changes a different scientific system. Read the tool’s effect before placing it: a model project can represent a district or regional scenario rather than one physical building.</p><div className={styles.missions}>{activities.map(activity=><article key={activity.slug} id={activity.slug}><div className={styles.missionTitle}><BuildIcon kind={buildTools[activity.slug][0].kind}/><h3><Link href={`/en/simulations/${activity.slug}`}>{simulations.find(s=>s.slug===activity.slug)?.title}</Link></h3></div><p>{missions[activity.slug]}</p><details><summary>What this model can and cannot show</summary><p>{activity.limitations}</p><h4>Further reading</h4><ul>{activity.sources.map(([name,url])=><li key={url}><a href={url} target="_blank" rel="noopener noreferrer">{name}</a></li>)}</ul></details></article>)}</div></section>
    <section className="topicGuideSection" id="troubleshooting"><h2>When something does not work as expected</h2><h3>“The project will not drop.”</h3><p>Read the red preview card. Try an empty plot of the right terrain type, away from roads and the fixed city. If all suitable plots stop glowing, the project may have reached a model limit or the resilience budget may be full. Conditions shows the current inputs and offers a precise row-and-column placement option.</p><h3>“The graph is empty or shows only a point.”</h3><p>You may still be at time zero. Run the simulation or choose Show full run in Graphs. Measurements describe a changing system, so a single initial sample is not a completed experiment.</p><h3>“Nothing changed when I moved the trees.”</h3><p>That is expected. These models calculate from scenario totals, not each tree’s distance from a building. A grove represents the stated change in canopy or restoration. The detailed town helps you arrange your plan; it does not make the outputs a street-level forecast.</p><h3>“I removed the wrong project.”</h3><p>Use Undo immediately. Undo also recovers recent input changes and resets. Fixed starting buildings cannot be demolished; the move and remove tools act on projects you placed.</p><h3>“What counts as winning?”</h3><p>There is no single high score across the labs. Success is a prediction you can test, a controlled comparison, and an explanation supported by measurements. Different interventions can improve one outcome while leaving another unchanged. Describe those trade-offs rather than assuming the greenest-looking city always performs best.</p></section>
    <aside className="topicGuideModelNote"><h2>Use the city as a scientific model</h2><p>Buildings, trees and water are stylized representations. The calculations use simplified scenario-scale relationships, with different time units and assumptions for each world. They are learning tools, not forecasts for a real city or engineering designs. Read each lab’s model boundaries and linked science references before interpreting a result.</p><Link className="button primary" href="/en/subjects/environmental-science">Choose your next investigation</Link></aside>
   </div>
  </article>
 </main>;
}
