"use client";
import { SIMULATION_LEARNING_TOOLS_ENABLED } from "@/lib/settings/simulationFeatures";
import Link from "next/link";
import { useEffect, useId, useRef, useState, type ReactNode } from "react";
import type { SubjectDefinition, SimulationCard } from "@/lib/subjects/catalog";
import { activities, arrivals, front, hurricane, initialJourney, initialValues, mission, ocean, plate, river, rockEdges, stationData, travel, tsunami, volcano, waterEdges, type Values, type Journey } from "@/lib/simulations/geographyLabs/model";
import { TsunamiScene } from "./tsunami/TsunamiScene";
import { VolcanoScene } from "./volcano/VolcanoScene";
import { eruptionExamples } from "./volcano/volcanoModel";
import { GeographyScene } from "./GeographyScene";
import { FieldDisplay } from "./FieldDisplay";
import { GameControlIcon } from "../environmental/GameControlIcon";
import geo from "./geography.module.css";

const STORE="learnerkits-earth-expeditions-v1";
type Journal={completed:string[];observations:Record<string,string[]>};
function readJournal():Journal{try{const p=JSON.parse(localStorage.getItem(STORE)||"{}");return{completed:Array.isArray(p.completed)?p.completed.filter((s:unknown)=>typeof s==="string"&&activities.some(a=>a.slug===s)):[],observations:p.observations&&typeof p.observations==="object"&&!Array.isArray(p.observations)?Object.fromEntries(Object.entries(p.observations).filter((entry):entry is [string,string[]]=>{const [k,v]=entry;return activities.some(a=>a.slug===k)&&Array.isArray(v)&&v.every(s=>typeof s==="string");})):{}};}catch{return{completed:[],observations:{}};}}
const threeSlugs=["volcano-eruption-3d","plate-tectonics-3d","tsunami-3d","river-erosion","ocean-currents-3d"];
const fmt=(n:number,d=1)=>Number.isFinite(n)?n.toFixed(d):"—";
function readouts(slug:string,v:Values,t:number,j:Journey):[string,string][]{switch(slug){
 case"seismic-wave-lab":{const a=arrivals(v.distance);return[["P-wave speed","6 km/s"],["S-wave speed","3.5 km/s"],["S − P interval",t>=10?`${fmt(a.gap)} s`:"Awaiting record"]];}
 case"plate-motion-lab":{const p=plate(v);return[["Elapsed time",`${fmt(v.years*t/10)} Myr`],["East displacement",`${fmt(p.x*t/10,0)} km`],["North displacement",`${fmt(p.y*t/10,0)} km`]];}
 case"volcano-eruption-3d":{const e=volcano(v);return[["Eruption style",t>0?e.style:"Ready"],["Gas-retention index",`${fmt(e.index*100,0)} / 100`],["Viscosity",`${e.viscosity.toExponential(1)} Pa·s`]];}
 case"earthquake-epicenter-finder":return stationData(v.event).map(s=>[`${s.name} · S − P`,`${fmt(s.gap,2)} s`]);
 case"plate-tectonics-3d":return[["Boundary",["Divergent","Convergent","Transform"][v.boundary]],["Relative speed",`${v.rate} cm/year`],["Motion",["Apart","Together","Slide past"][v.boundary]]];
 case"tsunami-3d":{const a=tsunami(v);return[["Deep-water speed",`${fmt(a.speed*3.6,0)} km/h`],["Simulated elapsed",`${fmt(a.minutes*t/10)} min`],["20 m shelf amplitude",`${fmt(a.coastal)} m`]];}
 case"hurricane-simulator":{const h=hurricane(v);return[["Organization index",`${fmt(h.index*100,0)} / 100`],["Coriolis parameter",`${h.coriolis.toExponential(1)} s⁻¹`],["Environment",h.organized?"Favorable":h.index<=.1?"Hostile":"Marginal"]];}
 case"weather-front-simulator":{const f=front(v);return[["Approx. dew point",`${fmt(f.dew)} °C`],["Cloud base",`${fmt(f.base,0)} m`],["Lift above cloud base",`${fmt(f.cloud,0)} m`]];}
 case"river-erosion":{const r=river(v);return[["Flow velocity",`${fmt(r.velocity,2)} m/s`],["Bed shear",`${fmt(r.shear,2)} Pa`],["Discharge",`${fmt(r.flow)} m³/s`]];}
 case"ocean-currents-3d":{const o=ocean(v);return[["Warm-side density",`${fmt(o.warm,2)} kg/m³`],["Polar-side density",`${fmt(o.polar,2)} kg/m³`],["Density contrast",`${fmt(o.delta,2)} kg/m³`]];}
 default:return[["Current location",j.state],["Places visited",String(j.visited.length)],["Transformations",String(j.moves)]];
}}


type Panel="guide"|"results"|"passport"|"labs"|null;
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){
 const ref=useRef<HTMLDialogElement>(null),heading=useId();
 useEffect(()=>{const d=ref.current;d?.showModal();const before=document.body.style.overflow;document.body.style.overflow="hidden";return()=>{d?.close();document.body.style.overflow=before;};},[]);
 return <dialog ref={ref} className={geo.modal} aria-labelledby={heading} onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose();}}><header className={geo.modalHead}><h2 id={heading}>{title}</h2><button autoFocus onClick={onClose} aria-label="Close panel"><GameControlIcon kind="close"/></button></header><div className={geo.modalBody}>{children}</div></dialog>;
}
function NumberControl({id,value,min,max,step,onChange}:{id:string;value:number;min:number;max:number;step:number;onChange:(n:number)=>void}){
 const [draft,setDraft]=useState(String(value));
 useEffect(()=>{setDraft(String(value));},[value]);
 return <input id={id} type="number" inputMode="decimal" min={min} max={max} step={step} value={draft} onChange={e=>{const raw=e.target.value,n=e.target.valueAsNumber;setDraft(raw);if(raw!==""&&Number.isFinite(n)&&n>=min&&n<=max)onChange(n);}} onBlur={()=>{const n=Number(draft);if(draft!==""&&Number.isFinite(n))onChange(n);setDraft(String(draft===""||!Number.isFinite(n)?value:Number(Math.max(min,Math.min(max,min+Math.round((n-min)/step)*step)).toFixed(6))));}} onKeyDown={e=>{if(e.key==="Enter")e.currentTarget.blur();}}/>;
}
export function GeographyActivitiesClient({locale,subject,simulation}:{locale:string;subject:SubjectDefinition;simulation:SimulationCard}){
 const activity=activities.find(a=>a.slug===simulation.slug)!,slug=activity.slug,water=slug==="water-cycle-adventure",journeyGame=water||slug==="rock-cycle-challenge";
 const [values,setValues]=useState(()=>initialValues(activity)),[time,setTime]=useState(0),[running,setRunning]=useState(false),[speed,setSpeed]=useState(1),[journey,setJourney]=useState(()=>initialJourney(water));
 const [journal,setJournal]=useState<Journal>({completed:[],observations:{}}),[feedback,setFeedback]=useState<{ok:boolean;text:string}|null>(null),[saved,setSaved]=useState(true),[panel,setPanel]=useState<Panel>(null);
 const game=useRef<HTMLDivElement>(null),live=useRef({running,speed,panel});live.current={running,speed,panel};
 useEffect(()=>{setJournal(readJournal());},[]);
 useEffect(()=>{let last=performance.now();const timer=window.setInterval(()=>{const now=performance.now(),dt=Math.min(.1,(now-last)/1000);last=now;if(document.hidden||!live.current.running||live.current.panel)return;setTime(t=>Math.min(10,t+dt*live.current.speed));},50);return()=>clearInterval(timer);},[]);
 useEffect(()=>{if(time>=10)setRunning(false);},[time]);
 function update(key:string,value:number){
  const control=activity.controls.find(c=>c.key===key);if(!control||!Number.isFinite(value))return;
  const bounded=Math.min(control.max,Math.max(control.min,control.min+Math.round((value-control.min)/control.step)*control.step));
  setValues(v=>({...v,[key]:Number(bounded.toFixed(6))}));setFeedback(null);
  if(!["estimate","landform","x","y","rings","event"].includes(key)){setRunning(false);setTime(0);}
 }
 function reset(){setValues(initialValues(activity));setTime(0);setRunning(false);setJourney(initialJourney(water));setFeedback(null);}
 function journeyMove(action:string){setJourney(j=>travel(j,action,water));setFeedback(null);}
 function check(){const result=mission(slug,values,time>=10,journey);if(!result.ok){setFeedback(result);return;}
  const stored=readJournal(),steps=[...new Set([...(stored.observations[slug]||[]),...(journal.observations[slug]||[]),result.step])],complete=steps.length>=result.required;
  const next={completed:[...new Set([...stored.completed,...journal.completed,...(complete?[slug]:[])])],observations:{...stored.observations,...journal.observations,[slug]:steps}};setJournal(next);
  try{localStorage.setItem(STORE,JSON.stringify(next));setSaved(true);}catch{setSaved(false);}
  setFeedback({ok:true,text:`${complete?"Expedition complete · badge earned!":`${steps.length}/${result.required} evidence stamps collected.`} ${result.text}`});
 }
 const result=mission(slug,values,time>=10,journey),stamps=journal.observations[slug]||[],complete=journal.completed.includes(slug);
 const actions=Object.entries((water?waterEdges:rockEdges)[journey.state]||{}),readings=readouts(slug,values,time,journey),is3D=threeSlugs.includes(slug);
 const currentHint=slug==="earthquake-epicenter-finder"?"Drag the crosshair or tap the map. Arrow keys move the marker; Shift moves 10 km.":journeyGame?"Choose a process below, or select a reachable destination on the map.":is3D?"Drag to orbit · camera buttons zoom and restore your view.":"Change one input, run the experiment, then inspect the evidence.";
 return <main className={geo.page}>
  <header className={geo.header}><div><Link href={`/${locale}/subjects/geography`}>← Geography & Earth</Link><h1>{simulation.title}</h1></div><nav aria-label="Lab panels"><button aria-label="Field guide" title="Field guide" onClick={()=>setPanel("guide")}><GameControlIcon kind="guide"/><span>Guide</span></button><button aria-label="Measurements" title="Measurements and evidence" onClick={()=>setPanel("results")}><GameControlIcon kind="graphs"/><span>Measurements</span></button>{SIMULATION_LEARNING_TOOLS_ENABLED&&<button aria-label="Field passport" title="Saved field passport" onClick={()=>setPanel("passport")}><GameControlIcon kind="labs"/><span>{journal.completed.length}/12</span></button>}</nav></header>
  <div className={geo.game} ref={game}>
   {SIMULATION_LEARNING_TOOLS_ENABLED&&<div className={geo.mission}><div><span>{activity.tag}</span><strong>{activity.mission}</strong></div><button className={geo.badge} onClick={()=>setPanel("guide")} aria-label="Mission help">{complete?"Badge earned":`${Math.min(stamps.length,result.required)} / ${result.required} stamps`}</button></div>}
   <div className={geo.metrics}>{readings.map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>
   <section className={geo.stage} aria-label="Interactive Earth field station">
    {slug==="volcano-eruption-3d"?<VolcanoScene values={values} time={time} onExample={example=>{setValues({...eruptionExamples[example]});setTime(0);setRunning(true);setSpeed(1);setFeedback(null);}}/>:slug==="tsunami-3d"?<TsunamiScene values={values} time={time}/>:is3D?<GeographyScene slug={slug} values={values} time={time}/>:<FieldDisplay slug={slug} values={values} time={time} journey={journey} onTravel={journeyMove} onPin={(x,y)=>{setValues(v=>({...v,x,y}));setFeedback(null);}}/>}
    {slug!=="tsunami-3d"&&slug!=="volcano-eruption-3d"&&<span className={geo.sceneLabel}>{journeyGame?"CONNECTED EARTH SYSTEMS":is3D?"3D FIELD MODEL":"LIVE FIELD INSTRUMENT"}</span>}
   </section>
   <div className={geo.controlsPanel}>
    <div className={geo.controlHeading}><span>{journeyGame?`YOUR NEXT MOVE · ${journey.state}`:"EXPERIMENT CONTROLS"}</span><small>{journeyGame?`${journey.moves} transformations`:time>=10?"Record complete":running&&!panel?"Experiment running":"Ready to explore"}</small></div>
    {journeyGame?<div className={geo.journeyActions}>{actions.map(([action,destination])=><button key={action} onClick={()=>journeyMove(action)}><GameControlIcon kind={action==="Melt"||action==="Evaporate"?"conditions":"right"}/><span><strong>{action}</strong><small>To {destination}</small></span></button>)}</div>:<div className={geo.controls}>{activity.controls.map(c=><div key={c.key} className={geo.control}><label htmlFor={`geo-${c.key}`}>{c.label}{c.unit&&<small> · {c.unit}</small>}</label>{c.options?<select id={`geo-${c.key}`} value={values[c.key]} onChange={e=>update(c.key,Number(e.target.value))}>{c.options.map((option,i)=><option key={option} value={i}>{option}</option>)}</select>:<div className={geo.stepper}><button aria-label={`Decrease ${c.label}`} disabled={values[c.key]<=c.min} onClick={()=>update(c.key,values[c.key]-c.step)}><GameControlIcon kind="minus"/></button><NumberControl id={`geo-${c.key}`} min={c.min} max={c.max} step={c.step} value={values[c.key]} onChange={n=>update(c.key,n)}/><button aria-label={`Increase ${c.label}`} disabled={values[c.key]>=c.max} onClick={()=>update(c.key,values[c.key]+c.step)}><GameControlIcon kind="plus"/></button></div>}</div>)}</div>}
   </div>
   <footer className={geo.transport}><div>{activity.run&&<><button className={geo.play} aria-label={running?"Pause experiment":"Run experiment"} title={running?"Pause experiment":"Run experiment"} onClick={()=>{if(time>=10)setTime(0);setRunning(r=>!r);}}><GameControlIcon kind={running?"pause":"play"}/><span>{running?"Pause":"Run"}</span></button><button aria-label="Step experiment" title="Advance one step" disabled={time>=10} onClick={()=>{setRunning(false);setTime(t=>Math.min(10,t+.1));}}><GameControlIcon kind="step"/></button><button aria-label="Finish experiment" title="Show completed experiment" onClick={()=>{setRunning(false);setTime(10);}}><GameControlIcon kind="fast"/></button><button aria-label="Change playback speed" title="Change playback speed" onClick={()=>setSpeed(s=>s===1?2:s===2?.5:1)}><GameControlIcon kind="speed"/><span>{speed}×</span></button><progress value={time} max={10} aria-label="Experiment playback"/></>}<button aria-label="Reset experiment" title="Reset experiment" onClick={reset}><GameControlIcon kind="reset"/></button></div><div>{SIMULATION_LEARNING_TOOLS_ENABLED&&<button className={geo.record} aria-label="Record evidence" onClick={check}><GameControlIcon kind="graphs"/><span>Record evidence</span></button>}<button aria-label="Measurements" title="Measurements" className={geo.fullscreenOnly} onClick={()=>setPanel("results")}><GameControlIcon kind="graphs"/></button><button aria-label="Field guide" title="Field guide" className={geo.fullscreenOnly} onClick={()=>setPanel("guide")}><GameControlIcon kind="guide"/></button><button aria-label="Toggle fullscreen" title="Toggle fullscreen" onClick={()=>{if(document.fullscreenElement)void document.exitFullscreen();else void game.current?.requestFullscreen?.();}}><GameControlIcon kind="fullscreen"/></button><button aria-label="More Earth labs" title="More Earth labs" onClick={()=>setPanel("labs")}><GameControlIcon kind="labs"/></button></div></footer>
   <div className={geo.notice} role="status" data-success={feedback?.ok}>{feedback?.text??currentHint}{!saved&&<span> Progress is available for this session; browser storage is unavailable.</span>}</div>
   {panel&&<Modal title={{guide:"Field guide & science",results:"Measurements & evidence",passport:"Your field passport",labs:"Geography & Earth labs"}[panel]} onClose={()=>setPanel(null)}>
    {panel==="guide"&&<><p className={geo.kicker}>{activity.tag}</p>{SIMULATION_LEARNING_TOOLS_ENABLED&&<h3>{activity.mission}</h3>}<p>{simulation.outcome}</p><h3>How to explore</h3><ol><li>{journeyGame?"Read your current location and choose a process. You can also select a highlighted destination on the diagram.":slug==="earthquake-epicenter-finder"?"Use the three station records to estimate distances. Drag the marker, tap the map, or enter east and north coordinates.":"Make a prediction. Set one input using its illustrated step buttons or type a value directly."}</li><li>{activity.run?"Press Run to watch the system develop. Pause, step forward, or use Finish to inspect the completed experiment.":"Follow the connections and watch the measurements update as you explore."}</li><li>Open Measurements to inspect the readings and current settings.</li><li>Try a different event or contrasting setting, then compare the results.</li></ol><h3>A useful starting hint</h3><p>{activity.hint.replace("coordinate sliders","coordinate inputs")}</p><h3>What the model represents</h3><p>{activity.science}</p><p>Visual sizes and animation time are adjusted for learning. A ten-second playback represents the model’s experiment, not ten seconds of real Earth activity. Opening a panel pauses playback; closing it resumes a running experiment.</p>{activity.source&&<a href={activity.source[1]} target="_blank" rel="noopener noreferrer">{activity.source[0]} →</a>}<Link href="/en/guides">Browse science learning guides →</Link></>}
    {panel==="results"&&<><p>{journeyGame?"Your current journey":activity.run?`${fmt(time/10*100,0)}% of the experiment recorded`:"Live station evidence"}. {activity.run&&time<10?"Finish the run before recording experimental evidence.":"Compare these readings with your prediction."}</p><dl className={geo.readingList}>{readings.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>{slug==="earthquake-epicenter-finder"&&<><h3>Station arrival records</h3><div className={geo.tableWrap}><table><thead><tr><th>Station</th><th>P arrival (s)</th><th>S arrival (s)</th><th>S − P (s)</th></tr></thead><tbody>{stationData(values.event).map(s=><tr key={s.name}><th>{s.name}</th><td>{fmt(s.p,2)}</td><td>{fmt(s.s,2)}</td><td>{fmt(s.gap,2)}</td></tr>)}</tbody></table></div><p>Station radius = (S − P) ÷ (1/3.5 − 1/6), in kilometers. The map is a fictional local coordinate system.</p></>}{slug==="river-erosion"&&<p>Sand: {river(values).sand?"moving":"resting"}. Gravel: {river(values).gravel?"moving":"resting"}. Compare each particle class against the bed shear.</p>}{slug==="ocean-currents-3d"&&<p>Left: warm box. Right: polar box. {Math.abs(ocean(values).delta)<.01?"Equal density: no driven circulation.":ocean(values).delta>0?"Polar water sinks.":"Warm-side water sinks."}</p>}{journeyGame?<><h3>Places visited</h3><p>{journey.visited.join(" → ")}</p><p>This list shows first visits; repeated transformations count toward your total moves.</p></>:<><h3>Current inputs</h3><dl className={geo.readingList}>{activity.controls.map(c=><div key={c.key}><dt>{c.label}</dt><dd>{c.options?c.options[values[c.key]]:`${values[c.key]} ${c.unit??""}`}</dd></div>)}</dl></>}<div className={geo.panelActions}>{activity.run&&<button onClick={()=>{setTime(10);setRunning(false);}}>Show completed experiment</button>}{SIMULATION_LEARNING_TOOLS_ENABLED&&<button onClick={check}>Record evidence</button>}</div><p role="status">{feedback?.text}</p></>}
    {SIMULATION_LEARNING_TOOLS_ENABLED&&panel==="passport"&&<><p>{journal.completed.length} of 12 expeditions complete. Stamps are saved in this browser when storage is available. Resetting an experiment keeps your earned stamps.</p><div className={geo.labList}>{subject.simulations.map(s=><Link key={s.slug} href={`/${locale}/simulations/${s.slug}`}><strong>{s.title}</strong><span>{journal.completed.includes(s.slug)?"Badge earned":`${journal.observations[s.slug]?.length??0} evidence stamps`}</span></Link>)}</div></>}
    {panel==="labs"&&<nav className={geo.labList}>{subject.simulations.map(s=><Link key={s.slug} href={`/${locale}/simulations/${s.slug}`} aria-current={slug===s.slug?"page":undefined}><strong>{s.title}</strong><span>{s.concepts}</span></Link>)}</nav>}
   </Modal>}
  </div>
 </main>;
}
