export type Values = Record<string, number>;
export type Control = { key:string; label:string; min:number; max:number; step:number; initial:number; unit?:string; options?:string[] };
export type Activity = { slug:string; instrument:string; mission:string; hint:string; science:string; duration:number; controls:Control[] };
const slider=(key:string,label:string,min:number,max:number,step:number,initial:number,unit=""):Control=>({key,label,min,max,step,initial,unit});
const choice=(key:string,label:string,options:string[],initial=0):Control=>({key,label,options,initial,min:0,max:options.length-1,step:1});
export const activities:Activity[]=[
  {slug:"projectile-lab",instrument:"Ballistics range",mission:"Land the ball inside the target at 40 ± 2 metres.",hint:"At 45°, range = speed² / g. Try about 20 m/s on Earth, then launch.",science:"Projectile motion without air resistance: x = v₀ cosθ t; y = v₀ sinθ t − gt²/2. Launch and landing are at the same height. The dashed curve is a prediction.",duration:12,controls:[slider("speed","Launch speed",5,35,.5,16,"m/s"),slider("angle","Launch angle",10,80,1,40,"°"),slider("gravity","Gravity",1.62,15,.01,9.81,"m/s²")]},
  {slug:"circuit-builder",instrument:"Circuit workbench",mission:"Complete the circuit, close its switch, and deliver 0.50 ± 0.02 A through the lamp.",hint:"Install the resistor in the empty socket, select a connection, and close the switch. In series, 12 V with a 14 Ω resistor and 10 Ω lamp gives 0.5 A.",science:"Ideal DC supply, wires, and resistive lamp (10 Ω). Series resistances add; parallel branch currents add. Lamp brightness follows electrical power, not a calibrated optical model.",duration:0,controls:[slider("voltage","Battery voltage",1,24,.5,12,"V"),slider("resistance","Resistor",2,40,1,20,"Ω"),choice("connection","Connection",["Series","Parallel"])]},
  {slug:"inclined-plane-friction",instrument:"Friction ramp",mission:"Release the block and reach the end of the 6 m ramp at 3–5 m/s.",hint:"Gravity must first overcome static friction. Try a 20° slope and kinetic friction 0.20; static friction is 0.10 higher.",science:"At rest, friction balances mg sinθ until μₛmg cosθ is exceeded. Sliding acceleration = g(sinθ − μₖcosθ). Here μₛ = μₖ + 0.10. Motion ends at the ramp edge.",duration:12,controls:[slider("angle","Ramp angle",5,50,1,15,"°"),slider("mu","Kinetic friction μ",0,.6,.01,.2),slider("mass","Block mass",1,20,1,5,"kg")]},
  {slug:"momentum-collision",instrument:"Collision rail",mission:"Run a collision that stops cart A within ±0.10 m/s while cart B moves forward.",hint:"Use equal masses, a stationary cart B, and restitution 1. An elastic collision transfers cart A’s velocity to B.",science:"One-dimensional isolated carts conserve total momentum. Restitution e sets relative separation speed; e = 1 is elastic and e = 0 is perfectly inelastic. No external friction.",duration:10,controls:[slider("massA","Cart A mass",1,5,.5,2,"kg"),slider("massB","Cart B mass",1,5,.5,3,"kg"),slider("speedA","Cart A initial speed",1,5,.1,3,"m/s"),slider("speedB","Cart B initial speed",-2,0,.1,0,"m/s"),slider("restitution","Restitution",0,1,.05,.7)]},
  {slug:"ray-optics-lens",instrument:"Optical bench",mission:"Form a real, inverted image twice as tall as the object (magnification −2 ± 0.10).",hint:"Choose a converging lens. An object at 1.5 focal lengths makes a real image with magnification −2.",science:"Thin lens in air, paraxial rays: 1/f = 1/dₒ + 1/dᵢ; m = −dᵢ/dₒ. Diverging lenses have negative f. Dashed extensions locate virtual images. At dₒ = f the outgoing rays are parallel.",duration:0,controls:[choice("lens","Lens type",["Converging","Diverging"]),slider("focal","Focal length magnitude",10,30,1,20,"cm"),slider("distance","Object distance",8,90,1,45,"cm")]},
  {slug:"newtons-laws-force-lab",instrument:"Force & motion track",mission:"Accelerate the cart at 2.00 ± 0.10 m/s² and run it for at least 3 seconds.",hint:"Net force equals mass × acceleration. With a 10 kg cart and 5 N resistance, apply 25 N.",science:"A cart starts at rest. Resistance can balance the applied force up to its selected limit; above that, net force = applied force − resistance. Constant net force produces constant acceleration.",duration:5,controls:[slider("force","Applied force",0,60,1,15,"N"),slider("resistance","Resistance limit",0,20,1,5,"N"),slider("mass","Cart mass",1,20,1,10,"kg")]},
  {slug:"simple-machines-challenge",instrument:"Mechanical advantage bench",mission:"Lift the 400 N load with no more than 100 N of effort using both a lever and a pulley system.",hint:"An effort arm four times the load arm gives 4:1 advantage. Four supporting rope segments also give 4:1 advantage.",science:"Ideal frictionless machines trade force for distance. Lever advantage = effort arm / load arm. Pulley advantage = number of supporting rope segments. Input work equals output work.",duration:4,controls:[choice("machine","Machine",["Lever","Pulley"]),slider("advantage","Mechanical advantage",1,6,1,2,"×"),slider("effort","Applied effort",20,200,5,80,"N")]},
  {slug:"wave-interference",instrument:"Wave superposition bench",mission:"Create destructive interference with a resultant amplitude below 0.10 m.",hint:"Use equal amplitudes and equal frequencies, then shift wave B by 180°. Cancellation at just one instant is not enough.",science:"y = A₁ sin(kx − 2πf₁t) + A₂ sin(kx − 2πf₂t + φ), with equal wavelengths here. For equal frequencies, resultant amplitude = √(A₁² + A₂² + 2A₁A₂cosφ). Different frequencies create beats.",duration:0,controls:[slider("amplitudeA","Wave A amplitude",.2,2,.1,1,"m"),slider("amplitudeB","Wave B amplitude",.2,2,.1,.6,"m"),slider("frequencyA","Wave A frequency",.2,2,.1,1,"Hz"),slider("frequencyB","Wave B frequency",.2,2,.1,1,"Hz"),slider("phase","Wave B phase",0,360,5,60,"°")]},
  {slug:"pendulum-physics",instrument:"Pendulum timing stand",mission:"Tune the pendulum to a period of 2.00 ± 0.05 s, then measure three complete swings.",hint:"On Earth, a length near 0.994 m gives a two-second small-angle period. Three periods take about six seconds.",science:"Small-angle, undamped pendulum: T = 2π√(L/g), θ(t) = θ₀cos(2πt/T). Angles are limited to 15° for this approximation. Bob mass does not change the period.",duration:30,controls:[slider("length","Pendulum length",.2,2,.01,.65,"m"),slider("gravity","Gravity",1.62,15,.01,9.81,"m/s²"),slider("amplitude","Release angle",2,15,1,10,"°")]},
  {slug:"energy-track-challenge",instrument:"Energy transfer track",mission:"Launch the cart and reach the exit with a speed of 6.0 ± 0.3 m/s.",hint:"Exit speed comes from the remaining energy: v = √(2gh(1 − loss)). Try 3 m height with 40% energy lost.",science:"A smooth descent converts mgh to kinetic energy and thermal loss. The selected loss fraction is distributed with vertical descent. Exit speed follows energy conservation; time is integrated along the track.",duration:20,controls:[slider("height","Release height",1,8,.1,4,"m"),slider("loss","Energy converted to heat",0,70,1,15,"%"),slider("mass","Cart mass",1,10,1,3,"kg")]},
  {slug:"electromagnet-3d",instrument:"Solenoid field scanner",mission:"Energize the coil and reach 4.0 ± 0.2 mT while keeping current at or below 3 A.",hint:"Increase turns or shorten the coil. With 500 turns, 0.4 m length and 2.5 A, the field is about 3.93 mT.",science:"Ideal long air-core solenoid: B = μ₀NI/L. The helical wire is a visual sample of the winding; its actual turn count is shown numerically. Field lines are illustrative. No iron core, heating, or saturation model.",duration:0,controls:[slider("current","Current",0,5,.1,1,"A"),slider("turns","Coil turns",100,1000,25,300),slider("length","Coil length",.2,.8,.01,.5,"m"),choice("polarity","Current direction",["Forward","Reverse"])]},
  {slug:"bridge-builder-challenge",instrument:"Truss design & load test",mission:"Support at least 10 kN at the apex without failure, using at most 100 kg of steel.",hint:"Try a 6 m span, 1.5 m rise and 9 cm² members. Both compression buckling and tensile stress matter.",science:"A three-member pin-jointed triangular truss, pin/roller supports and vertical apex load. Side members are in compression; the bottom tie is in tension. Solid square steel members: E = 200 GPa, allowable stress 150 MPa, density 7850 kg/m³. Pinned Euler buckling is checked; joints and self-weight forces are omitted.",duration:4,controls:[slider("span","Span",4,10,.5,6,"m"),slider("rise","Truss rise",.5,4,.1,1,"m"),slider("area","Member cross-section",2,20,1,4,"cm²"),slider("load","Apex load",5,30,1,10,"kN")]},
];
export const initialValues=(a:Activity):Values=>Object.fromEntries(a.controls.map(c=>[c.key,c.initial]));
export const radians=(d:number)=>d*Math.PI/180;
export const projectile=(v:Values)=>{const vx=v.speed*Math.cos(radians(v.angle)),vy=v.speed*Math.sin(radians(v.angle)),flight=2*vy/v.gravity;return{vx,vy,flight,range:vx*flight,height:vy*vy/(2*v.gravity)};};
export const ramp=(v:Values)=>{const angle=radians(v.angle),normal=v.mass*9.81*Math.cos(angle),gravity=v.mass*9.81*Math.sin(angle),sliding=gravity>(v.mu+.1)*normal;const acceleration=sliding?(gravity-v.mu*normal)/v.mass:0;return{normal,gravity,friction:sliding?v.mu*normal:gravity,acceleration,sliding,finish:acceleration>0?Math.sqrt(12/acceleration):Infinity,speed:Math.sqrt(12*acceleration)};};
export function collision(v:Values){const {massA:a,massB:b,speedA:u,speedB:w,restitution:e}=v;const momentum=a*u+b*w;const speedA=(momentum-b*e*(u-w))/(a+b),speedB=(momentum+a*e*(u-w))/(a+b);return{speedA,speedB,momentum,energyBefore:.5*a*u*u+.5*b*w*w,energyAfter:.5*a*speedA**2+.5*b*speedB**2,at:4/(u-w)};}
export function circuit(v:Values,closed:boolean,installed:boolean){const series=v.connection===0,active=closed&&(installed||!series);const resistance=series?(installed?v.resistance+10:Infinity):1/((installed?1/v.resistance:0)+1/10),current=active?v.voltage/resistance:0,lampCurrent=active?(series?current:v.voltage/10):0;return{resistance,current,lampCurrent,power:lampCurrent**2*10};}
export function lens(v:Values){const f=v.focal*(v.lens===0?1:-1),denominator=1/f-1/v.distance;const image=Math.abs(denominator)<1e-9?Infinity:1/denominator;return{f,image,magnification:-image/v.distance};}
export const force=(v:Values)=>({net:Math.max(0,v.force-v.resistance),acceleration:Math.max(0,v.force-v.resistance)/v.mass});
export const period=(v:Values)=>2*Math.PI*Math.sqrt(v.length/v.gravity);
export const waveAmplitude=(v:Values)=>Math.sqrt(Math.max(0,v.amplitudeA**2+v.amplitudeB**2+2*v.amplitudeA*v.amplitudeB*Math.cos(radians(v.phase))));
export const field=(v:Values,closed:boolean)=>closed?4*Math.PI*1e-7*v.turns*v.current/v.length:0;
export function bridge(v:Values){const half=v.span/2,side=Math.hypot(half,v.rise),load=v.load*1000,area=v.area*1e-4;const compression=load*side/(2*v.rise),tension=load*half/(2*v.rise),buckling=Math.PI**2*200e9*(area**2/12)/side**2,allowable=150e6*area;return{side,compression,tension,buckling,mass:(2*side+v.span)*area*7850,utilization:Math.max(compression/buckling,compression/allowable,tension/allowable),reaction:load/2};}
// Precompute a time-parametrized descent on y=h(1-u)^2, x=8u.
// Integrate dt=ds/v at segment midpoints; the integrable release singularity is avoided.
export function energyTrack(v:Values){let elapsed=0;const samples=[{t:0,u:0}];for(let i=0;i<400;i++){const u=(i+.5)/400;const drop=v.height*(2*u-u*u),speed=Math.sqrt(2*9.81*drop*(1-v.loss/100));elapsed+=Math.hypot(8,2*v.height*(1-u))/400/speed;samples.push({t:elapsed,u:(i+1)/400});}return{samples,duration:elapsed,speed:Math.sqrt(2*9.81*v.height*(1-v.loss/100)),initial:v.mass*9.81*v.height};}
export function energyAt(v:Values,time:number){const track=energyTrack(v);let lo=0,hi=track.samples.length-1;while(lo+1<hi){const mid=(lo+hi)>>1;if(track.samples[mid].t<time)lo=mid;else hi=mid;}const a=track.samples[lo],b=track.samples[hi],u=time>=track.duration?1:a.u+(b.u-a.u)*Math.max(0,(time-a.t)/(b.t-a.t));const height=v.height*(1-u)**2,potential=v.mass*9.81*height,heat=(track.initial-potential)*v.loss/100;return{u,height,potential,heat,kinetic:track.initial-potential-heat,...track};}
export type Attempt={time:number;started:boolean;closed:boolean;installed:boolean;steps:string[]};
export function checkMission(slug:string,v:Values,a:Attempt):{ok:boolean;text:string;step?:string;required?:number}{
  switch(slug){
    case "projectile-lab":{const p=projectile(v);return{ok:a.started&&a.time>=p.flight&&Math.abs(p.range-40)<=2,text:!a.started?"Launch the ball to test your prediction.":a.time<p.flight?"The ball is still in flight.":`Touchdown at ${p.range.toFixed(1)} m. Target: 38–42 m. Adjust speed or angle for the next launch.`};}
    case "circuit-builder":{const c=circuit(v,a.closed,a.installed);return{ok:a.installed&&Math.abs(c.lampCurrent-.5)<=.02,text:!a.installed?"Install the resistor in the empty socket.":!a.closed?"Close the switch to complete the circuit.":`Lamp current: ${c.lampCurrent.toFixed(3)} A. Target: 0.48–0.52 A. Change the voltage or resistance.`};}
    case "inclined-plane-friction":{const r=ramp(v);return{ok:a.started&&a.time>=r.finish&&r.speed>=3&&r.speed<=5,text:!r.sliding?"Static friction holds the block. Increase the angle or lower friction.":!a.started||a.time<r.finish?"Release the block and let it reach the ramp edge.":`Exit speed: ${r.speed.toFixed(2)} m/s. Target: 3–5 m/s.`};}
    case "momentum-collision":{const c=collision(v);return{ok:a.started&&a.time>=c.at&&Math.abs(c.speedA)<=.1&&c.speedB>0,text:!a.started||a.time<c.at?"Run the carts until they collide.":`After impact: A ${c.speedA.toFixed(2)} m/s; B ${c.speedB.toFixed(2)} m/s. Momentum remains ${c.momentum.toFixed(2)} kg·m/s.`};}
    case "ray-optics-lens":{const l=lens(v);return{ok:l.image>0&&Number.isFinite(l.image)&&Math.abs(l.magnification+2)<=.1,text:!Number.isFinite(l.image)?"The object is at the focal point: no finite image forms.":`Magnification ${l.magnification.toFixed(2)}. Move the object until the real, inverted image is twice its height.`};}
    case "newtons-laws-force-lab":{const f=force(v);return{ok:a.started&&a.time>=3&&Math.abs(f.acceleration-2)<=.1,text:`Acceleration: ${f.acceleration.toFixed(2)} m/s². Run for at least 3 s at 1.90–2.10 m/s².`};}
    case "simple-machines-challenge":return{ok:a.started&&a.time>=4&&v.effort*v.advantage>=400&&v.effort<=100,step:String(v.machine),required:2,text:`Output force: ${(v.effort*v.advantage).toFixed(0)} N. Lift the 400 N load with effort ≤100 N, then try the other machine.`};
    case "wave-interference":return{ok:v.frequencyA===v.frequencyB&&waveAmplitude(v)<.1,text:v.frequencyA!==v.frequencyB?"Different frequencies do not maintain cancellation. Match the frequencies.":`Resultant amplitude: ${waveAmplitude(v).toFixed(3)} m. Match amplitudes and oppose their phases.`};
    case "pendulum-physics":{const t=period(v);return{ok:a.started&&a.time>=3*t&&Math.abs(t-2)<=.05,text:`Period: ${t.toFixed(3)} s. ${Math.floor(a.time/t)} complete swings measured. Target: 1.95–2.05 s and at least 3 swings.`};}
    case "energy-track-challenge":{const e=energyTrack(v);return{ok:a.started&&a.time>=e.duration&&Math.abs(e.speed-6)<=.3,text:!a.started||a.time<e.duration?"Release the cart and let it finish the track.":`Exit speed: ${e.speed.toFixed(2)} m/s. Target: 5.7–6.3 m/s. Adjust height or energy loss.`};}
    case "electromagnet-3d":{const b=field(v,a.closed)*1000;return{ok:a.closed&&Math.abs(b-4)<=.2&&v.current<=3,text:!a.closed?"Energize the coil with the power switch.":`Field: ${b.toFixed(2)} mT at ${v.current.toFixed(1)} A. Target 3.8–4.2 mT using at most 3 A.`};}
    case "bridge-builder-challenge":{const b=bridge(v);return{ok:a.started&&a.time>=4&&v.load>=10&&b.utilization<=1&&b.mass<=100,text:!a.started||a.time<4?"Run a load test on your design.":`${b.utilization>1?"Member capacity exceeded":"Members within capacity"}. Steel: ${b.mass.toFixed(1)} kg. Target ≥10 kN, ≤100 kg, and utilization ≤100%.`};}
    default:return{ok:false,text:"Activity not found."};
  }
}
