import type { Locale } from "./config";

type Prose = { eyebrow:string; headline:string; description:string; prompt:string; concepts:string[]; gradeBand:string; learningObjectives:string[] };
type Sim = { title:string; outcome:string; concepts:string; kind:string };
type L = Exclude<Locale,"en">;

const s=(title:string,outcome:string,concepts:string,kind:string):Sim=>({title,outcome,concepts,kind});

export const environmentalSubjectTranslations: Record<L, Prose> = {
  es:{eyebrow:"Ciencias ambientales y clima",headline:"Modela un planeta en cambio. Diseña soluciones que resistan.",description:"Investiga el clima, el carbono, los océanos, la contaminación, la biodiversidad, la energía limpia y las ciudades resilientes mediante simulaciones interactivas de ciencias ambientales con resultados medibles.",prompt:"¿Cómo responden los sistemas terrestres interconectados cuando las personas cambian sus emisiones, el uso del suelo, la energía y las medidas de adaptación?",concepts:["Sistemas climáticos","Contaminación","Ecosistemas","Sostenibilidad"],gradeBand:"Cursos 6–12",learningObjectives:["Seguir relaciones de causa y efecto en los sistemas ambientales","Interpretar evidencias de modelos cuantitativos simplificados","Comparar estrategias de mitigación, conservación y adaptación"]},
  fr:{eyebrow:"Sciences de l’environnement et climat",headline:"Modélisez une planète qui change. Concevez des solutions durables.",description:"Étudiez le climat, le carbone, les océans, la pollution, la biodiversité, l’énergie propre et les villes résilientes grâce à des simulations interactives de sciences de l’environnement aux résultats mesurables.",prompt:"Comment les systèmes terrestres interconnectés réagissent-ils lorsque l’humanité modifie ses émissions, l’usage des sols, l’énergie et ses choix d’adaptation ?",concepts:["Systèmes climatiques","Pollution","Écosystèmes","Durabilité"],gradeBand:"Niveaux 6–12",learningObjectives:["Suivre les relations de cause à effet dans les systèmes environnementaux","Interpréter les résultats de modèles quantitatifs simplifiés","Comparer des stratégies d’atténuation, de conservation et d’adaptation"]},
  de:{eyebrow:"Umweltwissenschaften und Klima",headline:"Modelliere einen Planeten im Wandel. Entwickle Lösungen, die bestehen.",description:"Untersuche Klima, Kohlenstoff, Ozeane, Umweltverschmutzung, Biodiversität, saubere Energie und widerstandsfähige Städte mit interaktiven Umwelt-Simulationen und messbaren Ergebnissen.",prompt:"Wie reagieren vernetzte Erdsysteme, wenn Menschen Emissionen, Landnutzung, Energie und Anpassungsmaßnahmen verändern?",concepts:["Klimasysteme","Umweltverschmutzung","Ökosysteme","Nachhaltigkeit"],gradeBand:"Klassen 6–12",learningObjectives:["Ursache-Wirkungs-Ketten in Umweltsystemen nachvollziehen","Belege aus vereinfachten quantitativen Modellen deuten","Strategien für Klimaschutz, Naturschutz und Anpassung vergleichen"]},
  pt:{eyebrow:"Ciências ambientais e clima",headline:"Modele um planeta em mudança. Projete soluções que funcionem.",description:"Investigue clima, carbono, oceanos, poluição, biodiversidade, energia limpa e cidades resilientes com simulações interativas de ciências ambientais e resultados mensuráveis.",prompt:"Como os sistemas terrestres interligados respondem quando as pessoas mudam emissões, uso da terra, energia e escolhas de adaptação?",concepts:["Sistemas climáticos","Poluição","Ecossistemas","Sustentabilidade"],gradeBand:"Anos 6–12",learningObjectives:["Rastrear relações de causa e efeito em sistemas ambientais","Interpretar evidências de modelos quantitativos simplificados","Comparar estratégias de mitigação, conservação e adaptação"]},
  ru:{eyebrow:"Экология и климат",headline:"Моделируйте меняющуюся планету. Находите надёжные решения.",description:"Исследуйте климат, углерод, океаны, загрязнение, биоразнообразие, чистую энергетику и устойчивые города с помощью интерактивных экологических симуляций с измеримыми результатами.",prompt:"Как реагируют взаимосвязанные системы Земли, когда люди меняют выбросы, землепользование, энергетику и меры адаптации?",concepts:["Климатические системы","Загрязнение","Экосистемы","Устойчивое развитие"],gradeBand:"6–12 классы",learningObjectives:["Прослеживать причинно-следственные связи в природных системах","Интерпретировать данные упрощённых количественных моделей","Сравнивать стратегии смягчения, охраны природы и адаптации"]},
  ja:{eyebrow:"環境科学・気候",headline:"変わりゆく地球をモデル化し、持続する解決策を設計する。",description:"測定可能な結果が得られるインタラクティブな環境科学シミュレーションで、気候、炭素、海洋、汚染、生物多様性、クリーンエネルギー、レジリエントな都市を調べます。",prompt:"人々が排出量、土地利用、エネルギー、適応策を変えると、つながり合う地球システムはどう応答するでしょうか？",concepts:["気候システム","汚染","生態系","持続可能性"],gradeBand:"6〜12年生",learningObjectives:["環境システムにおける原因と結果のつながりをたどる","簡略化した定量モデルから得られる証拠を読み取る","緩和策・保全策・適応策を比較する"]},
  zh:{eyebrow:"环境科学与气候",headline:"模拟变化中的地球，设计经得起考验的方案。",description:"通过具有可量化结果的交互式环境科学模拟，研究气候、碳、海洋、污染、生物多样性、清洁能源和韧性城市。",prompt:"当人类改变排放、土地利用、能源和适应措施时，相互关联的地球系统会如何响应？",concepts:["气候系统","污染","生态系统","可持续发展"],gradeBand:"6–12年级",learningObjectives:["追踪环境系统中的因果关系","解读简化定量模型给出的证据","比较减缓、保护和适应策略"]},
  ar:{eyebrow:"العلوم البيئية والمناخ",headline:"نمذج كوكبًا متغيرًا. صمّم حلولًا تصمد.",description:"استكشف المناخ والكربون والمحيطات والتلوث والتنوع البيولوجي والطاقة النظيفة والمدن القادرة على الصمود عبر محاكاة تفاعلية في العلوم البيئية بنتائج قابلة للقياس.",prompt:"كيف تستجيب أنظمة الأرض المترابطة عندما يغيّر البشر الانبعاثات واستخدام الأراضي والطاقة وخيارات التكيّف؟",concepts:["أنظمة المناخ","التلوث","الأنظمة البيئية","الاستدامة"],gradeBand:"الصفوف 6–12",learningObjectives:["تتبّع علاقات السبب والنتيجة عبر الأنظمة البيئية","تفسير الأدلة المستمدة من نماذج كمية مبسطة","مقارنة استراتيجيات التخفيف والحفاظ والتكيّف"]}
};

export const environmentalSimulationTranslations: Record<L, Record<string, Sim>> = {
  es:{
    "greenhouse-effect-simulator":s("Simulador del efecto invernadero","Explora cómo los gases de efecto invernadero y la reflectividad planetaria influyen en el balance energético de la Tierra y en el calentamiento modelado.","Dióxido de carbono · metano · albedo · forzamiento radiativo","Simulación climática"),
    "carbon-cycle-simulator":s("Simulador del ciclo del carbono","Equilibra las emisiones y los sumideros de carbono para ver cómo cambia el CO₂ atmosférico a lo largo de tres décadas.","Emisiones · sumideros de carbono · atmósfera · cero neto","Simulación de sistemas"),
    "sea-level-rise-simulator":s("Simulador del aumento del nivel del mar","Compara la expansión térmica, el deshielo continental y el hundimiento local en un escenario simplificado del nivel del mar.","Expansión térmica · deshielo · calentamiento · riesgo costero","Simulación costera"),
    "ocean-acidification-simulator":s("Simulador de acidificación del océano","Relaciona el aumento del dióxido de carbono con el pH del océano, la disponibilidad de carbonato y la salud de los organismos que forman conchas.","pH oceánico · dióxido de carbono · carbonato · salud de las conchas","Laboratorio de química oceánica"),
    "renewable-energy-grid-simulator":s("Simulador de red de energías renovables","Construye una combinación eléctrica fiable y baja en carbono equilibrando demanda, generación renovable, almacenamiento y respaldo.","Solar · eólica · almacenamiento · fiabilidad · emisiones","Juego de energía limpia"),
    "air-pollution-smog-simulator":s("Simulador de contaminación del aire y smog","Comprueba cómo las emisiones y las condiciones meteorológicas cambian la contaminación por partículas, el ozono y un índice aproximado de calidad del aire.","PM2.5 · ozono · emisiones · viento · inversión térmica","Simulación de calidad del aire"),
    "deforestation-water-cycle-simulator":s("Simulador de deforestación y ciclo del agua","Observa cómo la pérdida de bosque, la lluvia, la pendiente y la compactación del suelo afectan a la escorrentía, la infiltración y la erosión.","Cobertura forestal · infiltración · escorrentía · erosión del suelo","Simulación de cuencas"),
    "biodiversity-habitat-fragmentation":s("Juego de biodiversidad y fragmentación del hábitat","Diseña una red de hábitats conectados que sostenga la biodiversidad bajo presiones del uso del suelo y la contaminación.","Pérdida de hábitat · fragmentación · corredores · viabilidad","Juego de conservación"),
    "urban-heat-island-simulator":s("Simulador de isla de calor urbana","Rediseña un barrio urbano para reducir la exposición al calor y la escorrentía de aguas pluviales.","Arbolado · techos frescos · pavimento · aguas pluviales","Laboratorio de ciudad sostenible"),
    "climate-resilience-city-builder":s("Constructor de ciudades resilientes al clima","Asigna un presupuesto limitado de adaptación para reducir los riesgos de inundación, calor y tormentas en una ciudad.","Adaptación · inundaciones · calor · tormentas · presupuesto","Juego de estrategia de resiliencia")
  },
  fr:{
    "greenhouse-effect-simulator":s("Simulateur de l’effet de serre","Explorez comment les gaz à effet de serre et la réflectivité planétaire influencent le bilan énergétique de la Terre et le réchauffement modélisé.","Dioxyde de carbone · méthane · albédo · forçage radiatif","Simulation climatique"),
    "carbon-cycle-simulator":s("Simulateur du cycle du carbone","Équilibrez émissions et puits de carbone pour voir comment le CO₂ atmosphérique évolue sur trois décennies.","Émissions · puits de carbone · atmosphère · neutralité carbone","Simulation de systèmes"),
    "sea-level-rise-simulator":s("Simulateur de montée du niveau de la mer","Comparez la dilatation thermique, la fonte des glaces continentales et l’affaissement local dans un scénario simplifié du niveau de la mer.","Dilatation thermique · fonte des glaces · réchauffement · risque côtier","Simulation côtière"),
    "ocean-acidification-simulator":s("Simulateur d’acidification des océans","Reliez la hausse du dioxyde de carbone au pH de l’océan, à la disponibilité des carbonates et à la santé des organismes à coquille.","pH océanique · dioxyde de carbone · carbonates · santé des coquilles","Laboratoire de chimie océanique"),
    "renewable-energy-grid-simulator":s("Simulateur de réseau d’énergies renouvelables","Construisez un mix électrique fiable et bas carbone en équilibrant demande, production renouvelable, stockage et secours.","Solaire · éolien · stockage · fiabilité · émissions","Jeu sur l’énergie propre"),
    "air-pollution-smog-simulator":s("Simulateur de pollution de l’air et de smog","Testez comment les émissions et la météo modifient la pollution aux particules, l’ozone et un indice approché de qualité de l’air.","PM2.5 · ozone · émissions · vent · inversion thermique","Simulation de qualité de l’air"),
    "deforestation-water-cycle-simulator":s("Simulateur de déforestation et cycle de l’eau","Observez comment la perte de forêt, les précipitations, la pente et le tassement du sol influencent le ruissellement, l’infiltration et l’érosion.","Couvert forestier · infiltration · ruissellement · érosion des sols","Simulation de bassin versant"),
    "biodiversity-habitat-fragmentation":s("Jeu de biodiversité et fragmentation des habitats","Concevez un réseau d’habitats connectés qui soutient la biodiversité face aux pressions foncières et à la pollution.","Perte d’habitat · fragmentation · corridors · viabilité","Jeu de conservation"),
    "urban-heat-island-simulator":s("Simulateur d’îlot de chaleur urbain","Réaménagez un quartier urbain pour réduire l’exposition à la chaleur et le ruissellement des eaux pluviales.","Canopée · toits frais · revêtements · eaux pluviales","Laboratoire de ville durable"),
    "climate-resilience-city-builder":s("Bâtisseur de ville résiliente au climat","Répartissez un budget d’adaptation limité pour réduire les risques d’inondation, de chaleur et de tempêtes dans une ville.","Adaptation · inondations · chaleur · tempêtes · budget","Jeu de stratégie de résilience")
  },
  de:{
    "greenhouse-effect-simulator":s("Treibhauseffekt-Simulator","Erkunde, wie Treibhausgase und das Rückstrahlvermögen des Planeten die Energiebilanz der Erde und die modellierte Erwärmung beeinflussen.","Kohlendioxid · Methan · Albedo · Strahlungsantrieb","Klimasimulation"),
    "carbon-cycle-simulator":s("Kohlenstoffkreislauf-Simulator","Bringe Emissionen und Kohlenstoffsenken ins Gleichgewicht und beobachte, wie sich das atmosphärische CO₂ über drei Jahrzehnte verändert.","Emissionen · Kohlenstoffsenken · Atmosphäre · Netto-Null","Systemsimulation"),
    "sea-level-rise-simulator":s("Meeresspiegelanstieg-Simulator","Vergleiche thermische Ausdehnung, Landeisschmelze und lokale Absenkung in einem vereinfachten Meeresspiegel-Szenario.","Thermische Ausdehnung · Eisschmelze · Erwärmung · Küstenrisiko","Küstensimulation"),
    "ocean-acidification-simulator":s("Ozeanversauerung-Simulator","Verknüpfe steigendes Kohlendioxid mit dem pH-Wert des Ozeans, der Verfügbarkeit von Carbonat und der Gesundheit schalenbildender Organismen.","Ozean-pH · Kohlendioxid · Carbonat · Schalengesundheit","Meereschemie-Labor"),
    "renewable-energy-grid-simulator":s("Stromnetz-Simulator für erneuerbare Energien","Baue einen zuverlässigen, CO₂-armen Strommix, indem du Nachfrage, erneuerbare Erzeugung, Speicher und Reserve ausbalancierst.","Solar · Wind · Speicher · Versorgungssicherheit · Emissionen","Spiel zu sauberer Energie"),
    "air-pollution-smog-simulator":s("Luftverschmutzung- und Smog-Simulator","Teste, wie Emissionen und Wetterbedingungen Feinstaub, Ozon und einen vereinfachten Luftqualitätsindex verändern.","PM2.5 · Ozon · Emissionen · Wind · Inversionswetterlage","Luftqualitätssimulation"),
    "deforestation-water-cycle-simulator":s("Simulator zu Abholzung und Wasserkreislauf","Beobachte, wie Waldverlust, Niederschlag, Hangneigung und Bodenverdichtung Oberflächenabfluss, Versickerung und Erosion beeinflussen.","Waldbedeckung · Versickerung · Oberflächenabfluss · Bodenerosion","Einzugsgebiet-Simulation"),
    "biodiversity-habitat-fragmentation":s("Spiel zu Biodiversität und Lebensraumzerschneidung","Entwirf ein vernetztes Lebensraumnetz, das die Biodiversität trotz Landnutzungs- und Verschmutzungsdruck erhält.","Lebensraumverlust · Zerschneidung · Korridore · Überlebensfähigkeit","Naturschutzspiel"),
    "urban-heat-island-simulator":s("Simulator für städtische Wärmeinseln","Gestalte ein Stadtviertel um, damit Hitzebelastung und Regenwasserabfluss sinken.","Baumkronen · kühle Dächer · Versiegelung · Regenwasser","Labor für nachhaltige Städte"),
    "climate-resilience-city-builder":s("Klimaresiliente Stadt bauen","Verteile ein begrenztes Anpassungsbudget, um Überschwemmungs-, Hitze- und Sturmrisiken in einer Stadt zu senken.","Anpassung · Überschwemmung · Hitze · Stürme · Budget","Resilienz-Strategiespiel")
  },
  pt:{
    "greenhouse-effect-simulator":s("Simulador do efeito estufa","Explore como os gases de efeito estufa e a refletividade planetária influenciam o balanço energético da Terra e o aquecimento modelado.","Dióxido de carbono · metano · albedo · forçante radiativa","Simulação climática"),
    "carbon-cycle-simulator":s("Simulador do ciclo do carbono","Equilibre emissões e sumidouros de carbono para ver como o CO₂ atmosférico muda ao longo de três décadas.","Emissões · sumidouros de carbono · atmosfera · emissões líquidas zero","Simulação de sistemas"),
    "sea-level-rise-simulator":s("Simulador de aumento do nível do mar","Compare expansão térmica, derretimento do gelo continental e subsidência local em um cenário simplificado do nível do mar.","Expansão térmica · derretimento do gelo · aquecimento · risco costeiro","Simulação costeira"),
    "ocean-acidification-simulator":s("Simulador de acidificação dos oceanos","Relacione o aumento do dióxido de carbono ao pH do oceano, à disponibilidade de carbonato e à saúde de organismos formadores de conchas.","pH do oceano · dióxido de carbono · carbonato · saúde das conchas","Laboratório de química oceânica"),
    "renewable-energy-grid-simulator":s("Simulador de rede de energia renovável","Monte uma matriz elétrica confiável e de baixo carbono equilibrando demanda, geração renovável, armazenamento e reserva.","Solar · eólica · armazenamento · confiabilidade · emissões","Jogo de energia limpa"),
    "air-pollution-smog-simulator":s("Simulador de poluição do ar e smog","Teste como emissões e condições do tempo alteram a poluição por partículas, o ozônio e um índice aproximado de qualidade do ar.","PM2.5 · ozônio · emissões · vento · inversão térmica","Simulação de qualidade do ar"),
    "deforestation-water-cycle-simulator":s("Simulador de desmatamento e ciclo da água","Observe como a perda de floresta, a chuva, a declividade e a compactação do solo afetam o escoamento, a infiltração e a erosão.","Cobertura florestal · infiltração · escoamento · erosão do solo","Simulação de bacia hidrográfica"),
    "biodiversity-habitat-fragmentation":s("Jogo de biodiversidade e fragmentação de habitat","Projete uma rede de habitats conectados que sustente a biodiversidade sob pressões do uso da terra e da poluição.","Perda de habitat · fragmentação · corredores · viabilidade","Jogo de conservação"),
    "urban-heat-island-simulator":s("Simulador de ilha de calor urbana","Redesenhe um bairro urbano para reduzir a exposição ao calor e o escoamento de águas pluviais.","Arborização · telhados frios · pavimento · águas pluviais","Laboratório de cidade sustentável"),
    "climate-resilience-city-builder":s("Construtor de cidades resilientes ao clima","Distribua um orçamento limitado de adaptação para reduzir os riscos de enchentes, calor e tempestades em uma cidade.","Adaptação · enchentes · calor · tempestades · orçamento","Jogo de estratégia de resiliência")
  },
  ru:{
    "greenhouse-effect-simulator":s("Симулятор парникового эффекта","Исследуйте, как парниковые газы и отражательная способность планеты влияют на энергетический баланс Земли и моделируемое потепление.","Углекислый газ · метан · альбедо · радиационное воздействие","Климатическая симуляция"),
    "carbon-cycle-simulator":s("Симулятор круговорота углерода","Сбалансируйте выбросы и поглотители углерода и посмотрите, как меняется содержание CO₂ в атмосфере за три десятилетия.","Выбросы · поглотители углерода · атмосфера · нулевой баланс","Симуляция систем"),
    "sea-level-rise-simulator":s("Симулятор повышения уровня моря","Сравните тепловое расширение, таяние материковых льдов и местное опускание суши в упрощённом сценарии уровня моря.","Тепловое расширение · таяние льдов · потепление · риски для побережья","Прибрежная симуляция"),
    "ocean-acidification-simulator":s("Симулятор закисления океана","Свяжите рост содержания углекислого газа с pH океана, доступностью карбонатов и состоянием организмов, строящих раковины.","pH океана · углекислый газ · карбонаты · состояние раковин","Лаборатория химии океана"),
    "renewable-energy-grid-simulator":s("Симулятор энергосети на возобновляемых источниках","Соберите надёжный низкоуглеродный энергобаланс, уравновешивая спрос, возобновляемую генерацию, накопители и резерв.","Солнце · ветер · накопители · надёжность · выбросы","Игра о чистой энергии"),
    "air-pollution-smog-simulator":s("Симулятор загрязнения воздуха и смога","Проверьте, как выбросы и погодные условия меняют загрязнение твёрдыми частицами, уровень озона и приближённый индекс качества воздуха.","PM2.5 · озон · выбросы · ветер · температурная инверсия","Симуляция качества воздуха"),
    "deforestation-water-cycle-simulator":s("Симулятор вырубки лесов и круговорота воды","Наблюдайте, как потеря леса, осадки, уклон и уплотнение почвы влияют на сток, инфильтрацию и эрозию.","Лесной покров · инфильтрация · поверхностный сток · эрозия почвы","Симуляция водосбора"),
    "biodiversity-habitat-fragmentation":s("Игра о биоразнообразии и фрагментации местообитаний","Спроектируйте связанную сеть местообитаний, поддерживающую биоразнообразие под давлением землепользования и загрязнения.","Утрата местообитаний · фрагментация · экологические коридоры · жизнеспособность","Природоохранная игра"),
    "urban-heat-island-simulator":s("Симулятор городского острова тепла","Перепланируйте городской квартал, чтобы снизить тепловую нагрузку и сток ливневых вод.","Древесный покров · «холодные» крыши · покрытия · ливневые воды","Лаборатория устойчивого города"),
    "climate-resilience-city-builder":s("Строитель климатически устойчивого города","Распределите ограниченный бюджет на адаптацию, чтобы снизить риски наводнений, жары и штормов в городе.","Адаптация · наводнения · жара · штормы · бюджет","Стратегическая игра об устойчивости")
  },
  ja:{
    "greenhouse-effect-simulator":s("温室効果シミュレーター","温室効果ガスと惑星の反射率が、地球のエネルギー収支とモデル上の温暖化にどう影響するかを調べます。","二酸化炭素 · メタン · アルベド · 放射強制力","気候シミュレーション"),
    "carbon-cycle-simulator":s("炭素循環シミュレーター","排出量と炭素吸収源のバランスをとり、30年間で大気中のCO₂がどう変化するかを確かめます。","排出 · 炭素吸収源 · 大気 · ネットゼロ","システムシミュレーション"),
    "sea-level-rise-simulator":s("海面上昇シミュレーター","簡略化した海面シナリオで、熱膨張、陸氷の融解、局所的な地盤沈下の影響を比較します。","熱膨張 · 氷の融解 · 温暖化 · 沿岸リスク","沿岸シミュレーション"),
    "ocean-acidification-simulator":s("海洋酸性化シミュレーター","二酸化炭素の増加を、海水のpH、炭酸塩の量、殻をつくる生物の健康と結びつけます。","海洋pH · 二酸化炭素 · 炭酸塩 · 殻の健康","海洋化学ラボ"),
    "renewable-energy-grid-simulator":s("再生可能エネルギー電力網シミュレーター","需要、再生可能エネルギーの発電、蓄電、バックアップを調整し、安定した低炭素の電源構成を作ります。","太陽光 · 風力 · 蓄電 · 供給安定性 · 排出","クリーンエネルギーゲーム"),
    "air-pollution-smog-simulator":s("大気汚染・スモッグシミュレーター","排出量と気象条件によって、粒子状物質、オゾン、簡易的な大気質指数がどう変わるかを試します。","PM2.5 · オゾン · 排出 · 風 · 逆転層","大気質シミュレーション"),
    "deforestation-water-cycle-simulator":s("森林破壊と水循環シミュレーター","森林の減少、降雨、傾斜、土壌の締め固めが、流出、浸透、侵食にどう影響するかを観察します。","森林被覆 · 浸透 · 表面流出 · 土壌侵食","流域シミュレーション"),
    "biodiversity-habitat-fragmentation":s("生物多様性と生息地分断ゲーム","土地利用や汚染の圧力の中でも生物多様性を支える、つながった生息地ネットワークを設計します。","生息地の消失 · 分断化 · 生態回廊 · 存続可能性","保全ゲーム"),
    "urban-heat-island-simulator":s("ヒートアイランド現象シミュレーター","都市の街区を再設計し、暑熱へのさらされ方と雨水の流出を減らします。","樹冠 · クールルーフ · 舗装 · 雨水","持続可能な都市ラボ"),
    "climate-resilience-city-builder":s("気候レジリエンス都市ビルダー","限られた適応予算を配分し、都市全体の洪水・猛暑・暴風のリスクを減らします。","適応 · 洪水 · 猛暑 · 暴風 · 予算","レジリエンス戦略ゲーム")
  },
  zh:{
    "greenhouse-effect-simulator":s("温室效应模拟器","探索温室气体和行星反照率如何影响地球的能量平衡以及模型中的变暖程度。","二氧化碳 · 甲烷 · 反照率 · 辐射强迫","气候模拟"),
    "carbon-cycle-simulator":s("碳循环模拟器","平衡排放与碳汇，观察大气中的CO₂在三十年间如何变化。","排放 · 碳汇 · 大气 · 净零","系统模拟"),
    "sea-level-rise-simulator":s("海平面上升模拟器","在简化的海平面情景中比较热膨胀、陆地冰融化和局部地面沉降的影响。","热膨胀 · 冰川融化 · 变暖 · 海岸风险","海岸模拟"),
    "ocean-acidification-simulator":s("海洋酸化模拟器","把二氧化碳上升与海洋pH、碳酸盐可用量以及造壳生物的健康联系起来。","海洋pH · 二氧化碳 · 碳酸盐 · 贝壳健康","海洋化学实验室"),
    "renewable-energy-grid-simulator":s("可再生能源电网模拟器","平衡用电需求、可再生能源发电、储能和备用电源，构建可靠的低碳电力结构。","太阳能 · 风能 · 储能 · 可靠性 · 排放","清洁能源游戏"),
    "air-pollution-smog-simulator":s("空气污染与雾霾模拟器","测试排放和气象条件如何改变颗粒物污染、臭氧以及近似空气质量指数。","PM2.5 · 臭氧 · 排放 · 风 · 逆温","空气质量模拟"),
    "deforestation-water-cycle-simulator":s("森林砍伐与水循环模拟器","观察森林减少、降雨、坡度和土壤压实如何影响地表径流、下渗和侵蚀。","森林覆盖 · 下渗 · 径流 · 土壤侵蚀","流域模拟"),
    "biodiversity-habitat-fragmentation":s("生物多样性与栖息地破碎化游戏","在土地利用和污染压力下，设计能支撑生物多样性的连通栖息地网络。","栖息地丧失 · 破碎化 · 生态廊道 · 种群存续","保护游戏"),
    "urban-heat-island-simulator":s("城市热岛效应模拟器","重新设计城市街区，降低高温暴露和雨水径流。","树冠覆盖 · 冷屋顶 · 路面铺装 · 雨水","可持续城市实验室"),
    "climate-resilience-city-builder":s("气候韧性城市建造","分配有限的适应预算，降低城市面临的洪水、高温和风暴风险。","适应 · 洪水 · 高温 · 风暴 · 预算","韧性策略游戏")
  },
  ar:{
    "greenhouse-effect-simulator":s("محاكي ظاهرة الاحتباس الحراري","استكشف كيف تؤثر غازات الدفيئة وانعكاسية الكوكب في توازن الطاقة على الأرض وفي الاحترار الذي يقدّره النموذج.","ثاني أكسيد الكربون · الميثان · الألبيدو · التأثير الإشعاعي","محاكاة مناخية"),
    "carbon-cycle-simulator":s("محاكي دورة الكربون","وازن بين الانبعاثات ومصارف الكربون لترى كيف يتغير CO₂ في الغلاف الجوي على مدى ثلاثة عقود.","الانبعاثات · مصارف الكربون · الغلاف الجوي · الحياد الكربوني","محاكاة أنظمة"),
    "sea-level-rise-simulator":s("محاكي ارتفاع مستوى سطح البحر","قارن بين التمدد الحراري وذوبان الجليد القاري والهبوط المحلي لليابسة في سيناريو مبسّط لمستوى سطح البحر.","التمدد الحراري · ذوبان الجليد · الاحترار · المخاطر الساحلية","محاكاة ساحلية"),
    "ocean-acidification-simulator":s("محاكي تحمّض المحيطات","اربط ارتفاع ثاني أكسيد الكربون بدرجة pH في المحيط وتوافر الكربونات وصحة الكائنات التي تبني الأصداف.","pH المحيط · ثاني أكسيد الكربون · الكربونات · صحة الأصداف","مختبر كيمياء المحيطات"),
    "renewable-energy-grid-simulator":s("محاكي شبكة الطاقة المتجددة","ابنِ مزيجًا كهربائيًا موثوقًا منخفض الكربون بالموازنة بين الطلب وتوليد الطاقة المتجددة والتخزين والطاقة الاحتياطية.","الطاقة الشمسية · الرياح · التخزين · الموثوقية · الانبعاثات","لعبة الطاقة النظيفة"),
    "air-pollution-smog-simulator":s("محاكي تلوث الهواء والضباب الدخاني","اختبر كيف تغيّر الانبعاثات والظروف الجوية تلوث الجسيمات والأوزون ومؤشرًا تقريبيًا لجودة الهواء.","PM2.5 · الأوزون · الانبعاثات · الرياح · الانقلاب الحراري","محاكاة جودة الهواء"),
    "deforestation-water-cycle-simulator":s("محاكي إزالة الغابات ودورة المياه","لاحظ كيف يؤثر فقدان الغابات والأمطار والانحدار وانضغاط التربة في الجريان السطحي والتسرب والتعرية.","الغطاء الحرجي · التسرب · الجريان السطحي · تعرية التربة","محاكاة مستجمعات المياه"),
    "biodiversity-habitat-fragmentation":s("لعبة التنوع البيولوجي وتجزؤ الموائل","صمّم شبكة موائل مترابطة تدعم التنوع البيولوجي في ظل ضغوط استخدام الأراضي والتلوث.","فقدان الموائل · التجزؤ · الممرات البيئية · القدرة على البقاء","لعبة الحفاظ على الطبيعة"),
    "urban-heat-island-simulator":s("محاكي الجزر الحرارية الحضرية","أعد تصميم حي حضري لتقليل التعرض للحرارة وجريان مياه الأمطار.","الغطاء الشجري · الأسطح الباردة · الرصف · مياه الأمطار","مختبر المدينة المستدامة"),
    "climate-resilience-city-builder":s("باني المدينة القادرة على الصمود أمام المناخ","وزّع ميزانية تكيّف محدودة لتقليل مخاطر الفيضانات والحرارة والعواصف في أنحاء المدينة.","التكيّف · الفيضانات · الحرارة · العواصف · الميزانية","لعبة استراتيجية للصمود")
  }
};
