import { isLocale, type Locale } from "./config";
import { translatedControlLabel } from "./controlTranslations";
import { translatedPhrase } from "./phraseTranslations";

const exact: Partial<Record<Locale, Record<string, string>>> = {
  es: {
    "horizontal distance (m)":"distancia horizontal (m)","height (m)":"altura (m)","Launch speed":"Velocidad de lanzamiento","Launch angle":"Ángulo de lanzamiento","Gravity":"Gravedad","Range":"Alcance","Max height":"Altura máxima","Flight time":"Tiempo de vuelo",
    "Voltage":"Voltaje","Resistance":"Resistencia","Current":"Corriente","Power":"Potencia","Electron-flow proxy":"Indicador de flujo de electrones",
    "P-wave":"Onda P","S-wave":"Onda S","Station distance":"Distancia a la estación","P-wave speed":"Velocidad de onda P","S-wave speed":"Velocidad de onda S","P arrival":"Llegada de P","S arrival":"Llegada de S","Arrival gap":"Diferencia de llegada",
    "Plate speed":"Velocidad de la placa","Time":"Tiempo","Boundary type":"Tipo de límite","Convergent":"Convergente","Divergent":"Divergente","Transform":"Transformante","Relative displacement":"Desplazamiento relativo","Boundary":"Límite","Scale":"Escala","geologic time":"tiempo geológico",
    "time":"tiempo","population":"población","Initial population":"Población inicial","Growth rate":"Tasa de crecimiento","Carrying capacity":"Capacidad de carga","Population at t=20":"Población en t=20","Growth model":"Modelo de crecimiento","Logistic":"Logístico",
    "Prey":"Presas","Predators":"Depredadores","Prey growth":"Crecimiento de presas","Predator loss":"Pérdida de depredadores","Interaction strength":"Intensidad de interacción","Model":"Modelo","Prey start":"Presas iniciales","Predator start":"Depredadores iniciales",
    "Amount":"Cantidad","Temperature":"Temperatura","Volume":"Volumen","Pressure":"Presión","Molar density":"Densidad molar","concentration":"concentración","Activation energy":"Energía de activación","Initial concentration":"Concentración inicial","Rate constant k":"Constante de velocidad k","Half-life":"Semivida","First-order":"Primer orden",
    "Vector A":"Vector A","Vector B":"Vector B","Resultant":"Resultante","A magnitude":"Magnitud de A","A angle":"Ángulo de A","B magnitude":"Magnitud de B","B angle":"Ángulo de B","Resultant magnitude":"Magnitud resultante","Resultant angle":"Ángulo resultante","Components":"Componentes","Vertex":"Vértice","Discriminant":"Discriminante","Roots":"Raíces","no real roots":"sin raíces reales",
    "Earth":"Tierra","Moon":"Luna","Mars":"Marte","Jupiter":"Júpiter","Mercury":"Mercurio","Venus":"Venus","Saturn":"Saturno","Uranus":"Urano","Neptune":"Neptuno","Convex":"Convexa","Concave":"Cóncava","Lever":"Palanca","Pulley":"Polea","Inclined plane":"Plano inclinado","Cube":"Cubo","Cylinder":"Cilindro","Sphere":"Esfera","Yes":"Sí","No":"No","Real":"Real","Virtual":"Virtual","Positive":"Positiva","Negative":"Negativa","Up":"Arriba","Down":"Abajo","Low":"Baja","Higher":"Mayor","Neutral":"Neutro","Acidic":"Ácido","Basic":"Básico"
  },
  fr: {
    "horizontal distance (m)":"distance horizontale (m)","height (m)":"hauteur (m)","Launch speed":"Vitesse de lancement","Launch angle":"Angle de lancement","Gravity":"Gravité","Range":"Portée","Max height":"Hauteur maximale","Flight time":"Temps de vol",
    "Voltage":"Tension","Resistance":"Résistance","Current":"Courant","Power":"Puissance","Electron-flow proxy":"Indicateur du flux d’électrons",
    "P-wave":"Onde P","S-wave":"Onde S","Station distance":"Distance à la station","P-wave speed":"Vitesse de l’onde P","S-wave speed":"Vitesse de l’onde S","P arrival":"Arrivée P","S arrival":"Arrivée S","Arrival gap":"Écart d’arrivée",
    "Plate speed":"Vitesse de la plaque","Time":"Temps","Boundary type":"Type de limite","Convergent":"Convergente","Divergent":"Divergente","Transform":"Transformante","Relative displacement":"Déplacement relatif","Boundary":"Limite","Scale":"Échelle","geologic time":"temps géologique",
    "time":"temps","population":"population","Initial population":"Population initiale","Growth rate":"Taux de croissance","Carrying capacity":"Capacité de charge","Population at t=20":"Population à t=20","Growth model":"Modèle de croissance","Logistic":"Logistique",
    "Prey":"Proies","Predators":"Prédateurs","Prey growth":"Croissance des proies","Predator loss":"Perte des prédateurs","Interaction strength":"Intensité de l’interaction","Model":"Modèle","Prey start":"Proies au départ","Predator start":"Prédateurs au départ",
    "Amount":"Quantité","Temperature":"Température","Volume":"Volume","Pressure":"Pression","Molar density":"Densité molaire","concentration":"concentration","Activation energy":"Énergie d’activation","Initial concentration":"Concentration initiale","Rate constant k":"Constante de vitesse k","Half-life":"Demi-vie","First-order":"Premier ordre",
    "Vector A":"Vecteur A","Vector B":"Vecteur B","Resultant":"Résultante","A magnitude":"Norme de A","A angle":"Angle de A","B magnitude":"Norme de B","B angle":"Angle de B","Resultant magnitude":"Norme de la résultante","Resultant angle":"Angle de la résultante","Components":"Composantes","Vertex":"Sommet","Discriminant":"Discriminant","Roots":"Racines","no real roots":"aucune racine réelle",
    "Earth":"Terre","Moon":"Lune","Mars":"Mars","Jupiter":"Jupiter","Mercury":"Mercure","Venus":"Vénus","Saturn":"Saturne","Uranus":"Uranus","Neptune":"Neptune","Convex":"Convexe","Concave":"Concave","Lever":"Levier","Pulley":"Poulie","Inclined plane":"Plan incliné","Cube":"Cube","Cylinder":"Cylindre","Sphere":"Sphère","Yes":"Oui","No":"Non","Real":"Réelle","Virtual":"Virtuelle","Positive":"Positive","Negative":"Négative","Up":"Vers le haut","Down":"Vers le bas","Low":"Faible","Higher":"Plus élevée","Neutral":"Neutre","Acidic":"Acide","Basic":"Basique"
  },
  de: {
    "horizontal distance (m)":"horizontale Entfernung (m)","height (m)":"Höhe (m)","Launch speed":"Startgeschwindigkeit","Launch angle":"Startwinkel","Gravity":"Gravitation","Range":"Reichweite","Max height":"Maximale Höhe","Flight time":"Flugzeit",
    "Voltage":"Spannung","Resistance":"Widerstand","Current":"Stromstärke","Power":"Leistung","Electron-flow proxy":"Indikator für Elektronenfluss",
    "P-wave":"P-Welle","S-wave":"S-Welle","Station distance":"Stationsentfernung","P-wave speed":"P-Wellen-Geschwindigkeit","S-wave speed":"S-Wellen-Geschwindigkeit","P arrival":"P-Ankunft","S arrival":"S-Ankunft","Arrival gap":"Ankunftsdifferenz",
    "Plate speed":"Plattengeschwindigkeit","Time":"Zeit","Boundary type":"Grenztyp","Convergent":"Konvergent","Divergent":"Divergent","Transform":"Transform","Relative displacement":"Relative Verschiebung","Boundary":"Grenze","Scale":"Skala","geologic time":"geologische Zeit",
    "time":"Zeit","population":"Population","Initial population":"Anfangspopulation","Growth rate":"Wachstumsrate","Carrying capacity":"Tragfähigkeit","Population at t=20":"Population bei t=20","Growth model":"Wachstumsmodell","Logistic":"Logistisch",
    "Prey":"Beute","Predators":"Räuber","Prey growth":"Beutewachstum","Predator loss":"Räuberverlust","Interaction strength":"Interaktionsstärke","Model":"Modell","Prey start":"Beute zu Beginn","Predator start":"Räuber zu Beginn",
    "Amount":"Stoffmenge","Temperature":"Temperatur","Volume":"Volumen","Pressure":"Druck","Molar density":"Molare Dichte","concentration":"Konzentration","Activation energy":"Aktivierungsenergie","Initial concentration":"Anfangskonzentration","Rate constant k":"Geschwindigkeitskonstante k","Half-life":"Halbwertszeit","First-order":"Erster Ordnung",
    "Vector A":"Vektor A","Vector B":"Vektor B","Resultant":"Resultierende","A magnitude":"Betrag A","A angle":"Winkel A","B magnitude":"Betrag B","B angle":"Winkel B","Resultant magnitude":"Betrag der Resultierenden","Resultant angle":"Winkel der Resultierenden","Components":"Komponenten","Vertex":"Scheitelpunkt","Discriminant":"Diskriminante","Roots":"Nullstellen","no real roots":"keine reellen Nullstellen",
    "Earth":"Erde","Moon":"Mond","Mars":"Mars","Jupiter":"Jupiter","Mercury":"Merkur","Venus":"Venus","Saturn":"Saturn","Uranus":"Uranus","Neptune":"Neptun","Convex":"Konvex","Concave":"Konkav","Lever":"Hebel","Pulley":"Flaschenzug","Inclined plane":"Schiefe Ebene","Cube":"Würfel","Cylinder":"Zylinder","Sphere":"Kugel","Yes":"Ja","No":"Nein","Real":"Reell","Virtual":"Virtuell","Positive":"Positiv","Negative":"Negativ","Up":"Nach oben","Down":"Nach unten","Low":"Niedrig","Higher":"Höher","Neutral":"Neutral","Acidic":"Sauer","Basic":"Basisch"
  },
  pt: {
    "horizontal distance (m)":"distância horizontal (m)","height (m)":"altura (m)","Launch speed":"Velocidade de lançamento","Launch angle":"Ângulo de lançamento","Gravity":"Gravidade","Range":"Alcance","Max height":"Altura máxima","Flight time":"Tempo de voo",
    "Voltage":"Tensão","Resistance":"Resistência","Current":"Corrente","Power":"Potência","Electron-flow proxy":"Indicador de fluxo de elétrons",
    "P-wave":"Onda P","S-wave":"Onda S","Station distance":"Distância da estação","P-wave speed":"Velocidade da onda P","S-wave speed":"Velocidade da onda S","P arrival":"Chegada P","S arrival":"Chegada S","Arrival gap":"Diferença de chegada",
    "Plate speed":"Velocidade da placa","Time":"Tempo","Boundary type":"Tipo de limite","Convergent":"Convergente","Divergent":"Divergente","Transform":"Transformante","Relative displacement":"Deslocamento relativo","Boundary":"Limite","Scale":"Escala","geologic time":"tempo geológico",
    "time":"tempo","population":"população","Initial population":"População inicial","Growth rate":"Taxa de crescimento","Carrying capacity":"Capacidade de suporte","Population at t=20":"População em t=20","Growth model":"Modelo de crescimento","Logistic":"Logístico",
    "Prey":"Presas","Predators":"Predadores","Prey growth":"Crescimento das presas","Predator loss":"Perda de predadores","Interaction strength":"Intensidade da interação","Model":"Modelo","Prey start":"Presas iniciais","Predator start":"Predadores iniciais",
    "Amount":"Quantidade","Temperature":"Temperatura","Volume":"Volume","Pressure":"Pressão","Molar density":"Densidade molar","concentration":"concentração","Activation energy":"Energia de ativação","Initial concentration":"Concentração inicial","Rate constant k":"Constante de velocidade k","Half-life":"Meia-vida","First-order":"Primeira ordem",
    "Vector A":"Vetor A","Vector B":"Vetor B","Resultant":"Resultante","A magnitude":"Magnitude de A","A angle":"Ângulo de A","B magnitude":"Magnitude de B","B angle":"Ângulo de B","Resultant magnitude":"Magnitude resultante","Resultant angle":"Ângulo resultante","Components":"Componentes","Vertex":"Vértice","Discriminant":"Discriminante","Roots":"Raízes","no real roots":"sem raízes reais",
    "Earth":"Terra","Moon":"Lua","Mars":"Marte","Jupiter":"Júpiter","Mercury":"Mercúrio","Venus":"Vênus","Saturn":"Saturno","Uranus":"Urano","Neptune":"Netuno","Convex":"Convexa","Concave":"Côncava","Lever":"Alavanca","Pulley":"Polia","Inclined plane":"Plano inclinado","Cube":"Cubo","Cylinder":"Cilindro","Sphere":"Esfera","Yes":"Sim","No":"Não","Real":"Real","Virtual":"Virtual","Positive":"Positiva","Negative":"Negativa","Up":"Para cima","Down":"Para baixo","Low":"Baixa","Higher":"Maior","Neutral":"Neutro","Acidic":"Ácido","Basic":"Básico"
  },
  ru: {
    "horizontal distance (m)":"горизонтальное расстояние (м)","height (m)":"высота (м)","Launch speed":"Начальная скорость","Launch angle":"Угол запуска","Gravity":"Гравитация","Range":"Дальность","Max height":"Максимальная высота","Flight time":"Время полёта",
    "Voltage":"Напряжение","Resistance":"Сопротивление","Current":"Ток","Power":"Мощность","Electron-flow proxy":"Индикатор потока электронов",
    "P-wave":"P-волна","S-wave":"S-волна","Station distance":"Расстояние до станции","P-wave speed":"Скорость P-волны","S-wave speed":"Скорость S-волны","P arrival":"Приход P-волны","S arrival":"Приход S-волны","Arrival gap":"Разница времени прихода",
    "Plate speed":"Скорость плиты","Time":"Время","Boundary type":"Тип границы","Convergent":"Сходящаяся","Divergent":"Расходящаяся","Transform":"Трансформная","Relative displacement":"Относительное смещение","Boundary":"Граница","Scale":"Масштаб","geologic time":"геологическое время",
    "time":"время","population":"популяция","Initial population":"Начальная популяция","Growth rate":"Темп роста","Carrying capacity":"Ёмкость среды","Population at t=20":"Популяция при t=20","Growth model":"Модель роста","Logistic":"Логистическая",
    "Prey":"Жертвы","Predators":"Хищники","Prey growth":"Рост жертв","Predator loss":"Убыль хищников","Interaction strength":"Сила взаимодействия","Model":"Модель","Prey start":"Жертв в начале","Predator start":"Хищников в начале",
    "Amount":"Количество вещества","Temperature":"Температура","Volume":"Объём","Pressure":"Давление","Molar density":"Молярная плотность","concentration":"концентрация","Activation energy":"Энергия активации","Initial concentration":"Начальная концентрация","Rate constant k":"Константа скорости k","Half-life":"Период полураспада","First-order":"Первый порядок",
    "Vector A":"Вектор A","Vector B":"Вектор B","Resultant":"Результирующий вектор","A magnitude":"Модуль A","A angle":"Угол A","B magnitude":"Модуль B","B angle":"Угол B","Resultant magnitude":"Модуль результирующего","Resultant angle":"Угол результирующего","Components":"Компоненты","Vertex":"Вершина","Discriminant":"Дискриминант","Roots":"Корни","no real roots":"нет действительных корней",
    "Earth":"Земля","Moon":"Луна","Mars":"Марс","Jupiter":"Юпитер","Mercury":"Меркурий","Venus":"Венера","Saturn":"Сатурн","Uranus":"Уран","Neptune":"Нептун","Convex":"Выпуклая","Concave":"Вогнутая","Lever":"Рычаг","Pulley":"Блок","Inclined plane":"Наклонная плоскость","Cube":"Куб","Cylinder":"Цилиндр","Sphere":"Сфера","Yes":"Да","No":"Нет","Real":"Действительное","Virtual":"Мнимое","Positive":"Положительное","Negative":"Отрицательное","Up":"Вверх","Down":"Вниз","Low":"Низкая","Higher":"Выше","Neutral":"Нейтральная","Acidic":"Кислая","Basic":"Щелочная"
  },
  ja: {
    "horizontal distance (m)":"水平距離 (m)","height (m)":"高さ (m)","Launch speed":"初速度","Launch angle":"投射角","Gravity":"重力","Range":"到達距離","Max height":"最大高度","Flight time":"飛行時間",
    "Voltage":"電圧","Resistance":"抵抗","Current":"電流","Power":"電力","Electron-flow proxy":"電子流の指標",
    "P-wave":"P波","S-wave":"S波","Station distance":"観測点までの距離","P-wave speed":"P波速度","S-wave speed":"S波速度","P arrival":"P波到達","S arrival":"S波到達","Arrival gap":"到達時間差",
    "Plate speed":"プレート速度","Time":"時間","Boundary type":"境界タイプ","Convergent":"収束型","Divergent":"発散型","Transform":"横ずれ型","Relative displacement":"相対変位","Boundary":"境界","Scale":"スケール","geologic time":"地質学的時間",
    "time":"時間","population":"個体数","Initial population":"初期個体数","Growth rate":"成長率","Carrying capacity":"環境収容力","Population at t=20":"t=20 の個体数","Growth model":"成長モデル","Logistic":"ロジスティック",
    "Prey":"被食者","Predators":"捕食者","Prey growth":"被食者の成長率","Predator loss":"捕食者の減少率","Interaction strength":"相互作用の強さ","Model":"モデル","Prey start":"初期被食者数","Predator start":"初期捕食者数",
    "Amount":"物質量","Temperature":"温度","Volume":"体積","Pressure":"圧力","Molar density":"モル密度","concentration":"濃度","Activation energy":"活性化エネルギー","Initial concentration":"初期濃度","Rate constant k":"速度定数 k","Half-life":"半減期","First-order":"一次反応",
    "Vector A":"ベクトル A","Vector B":"ベクトル B","Resultant":"合成ベクトル","A magnitude":"A の大きさ","A angle":"A の角度","B magnitude":"B の大きさ","B angle":"B の角度","Resultant magnitude":"合成ベクトルの大きさ","Resultant angle":"合成ベクトルの角度","Components":"成分","Vertex":"頂点","Discriminant":"判別式","Roots":"解","no real roots":"実数解なし",
    "Earth":"地球","Moon":"月","Mars":"火星","Jupiter":"木星","Mercury":"水星","Venus":"金星","Saturn":"土星","Uranus":"天王星","Neptune":"海王星","Convex":"凸レンズ","Concave":"凹レンズ","Lever":"てこ","Pulley":"滑車","Inclined plane":"斜面","Cube":"立方体","Cylinder":"円柱","Sphere":"球","Yes":"はい","No":"いいえ","Real":"実像","Virtual":"虚像","Positive":"正","Negative":"負","Up":"上向き","Down":"下向き","Low":"低い","Higher":"高い","Neutral":"中性","Acidic":"酸性","Basic":"塩基性"
  },
  zh: {
    "horizontal distance (m)":"水平距离（m）","height (m)":"高度（m）","Launch speed":"发射速度","Launch angle":"发射角","Gravity":"重力","Range":"射程","Max height":"最大高度","Flight time":"飞行时间",
    "Voltage":"电压","Resistance":"电阻","Current":"电流","Power":"功率","Electron-flow proxy":"电子流指标",
    "P-wave":"P波","S-wave":"S波","Station distance":"台站距离","P-wave speed":"P波速度","S-wave speed":"S波速度","P arrival":"P波到达","S arrival":"S波到达","Arrival gap":"到时差",
    "Plate speed":"板块速度","Time":"时间","Boundary type":"边界类型","Convergent":"汇聚型","Divergent":"离散型","Transform":"转换型","Relative displacement":"相对位移","Boundary":"边界","Scale":"尺度","geologic time":"地质时间",
    "time":"时间","population":"种群数量","Initial population":"初始种群","Growth rate":"增长率","Carrying capacity":"环境容纳量","Population at t=20":"t=20 时的种群数量","Growth model":"增长模型","Logistic":"逻辑斯蒂",
    "Prey":"猎物","Predators":"捕食者","Prey growth":"猎物增长率","Predator loss":"捕食者损失率","Interaction strength":"相互作用强度","Model":"模型","Prey start":"初始猎物数","Predator start":"初始捕食者数",
    "Amount":"物质的量","Temperature":"温度","Volume":"体积","Pressure":"压强","Molar density":"摩尔密度","concentration":"浓度","Activation energy":"活化能","Initial concentration":"初始浓度","Rate constant k":"速率常数 k","Half-life":"半衰期","First-order":"一级反应",
    "Vector A":"向量 A","Vector B":"向量 B","Resultant":"合向量","A magnitude":"A 的模","A angle":"A 的角度","B magnitude":"B 的模","B angle":"B 的角度","Resultant magnitude":"合向量的模","Resultant angle":"合向量角度","Components":"分量","Vertex":"顶点","Discriminant":"判别式","Roots":"根","no real roots":"没有实根",
    "Earth":"地球","Moon":"月球","Mars":"火星","Jupiter":"木星","Mercury":"水星","Venus":"金星","Saturn":"土星","Uranus":"天王星","Neptune":"海王星","Convex":"凸透镜","Concave":"凹透镜","Lever":"杠杆","Pulley":"滑轮","Inclined plane":"斜面","Cube":"立方体","Cylinder":"圆柱体","Sphere":"球体","Yes":"是","No":"否","Real":"实像","Virtual":"虚像","Positive":"正","Negative":"负","Up":"向上","Down":"向下","Low":"低","Higher":"较高","Neutral":"中性","Acidic":"酸性","Basic":"碱性"
  },
  ar: {
    "horizontal distance (m)":"المسافة الأفقية (م)","height (m)":"الارتفاع (م)","Launch speed":"سرعة الإطلاق","Launch angle":"زاوية الإطلاق","Gravity":"الجاذبية","Range":"المدى","Max height":"أقصى ارتفاع","Flight time":"زمن الطيران",
    "Voltage":"الجهد الكهربائي","Resistance":"المقاومة","Current":"التيار","Power":"القدرة","Electron-flow proxy":"مؤشر تدفق الإلكترونات",
    "P-wave":"موجة P","S-wave":"موجة S","Station distance":"المسافة إلى المحطة","P-wave speed":"سرعة موجة P","S-wave speed":"سرعة موجة S","P arrival":"وصول موجة P","S arrival":"وصول موجة S","Arrival gap":"فرق زمن الوصول",
    "Plate speed":"سرعة الصفيحة","Time":"الزمن","Boundary type":"نوع الحد","Convergent":"تقاربي","Divergent":"تباعدي","Transform":"انزلاقي","Relative displacement":"الإزاحة النسبية","Boundary":"الحد","Scale":"المقياس","geologic time":"الزمن الجيولوجي",
    "time":"الزمن","population":"الجماعة الحيوية","Initial population":"الجماعة الابتدائية","Growth rate":"معدل النمو","Carrying capacity":"السعة الحاملة","Population at t=20":"حجم الجماعة عند t=20","Growth model":"نموذج النمو","Logistic":"لوجستي",
    "Prey":"الفرائس","Predators":"المفترسات","Prey growth":"نمو الفرائس","Predator loss":"فقد المفترسات","Interaction strength":"قوة التفاعل","Model":"النموذج","Prey start":"الفرائس في البداية","Predator start":"المفترسات في البداية",
    "Amount":"كمية المادة","Temperature":"درجة الحرارة","Volume":"الحجم","Pressure":"الضغط","Molar density":"الكثافة المولية","concentration":"التركيز","Activation energy":"طاقة التنشيط","Initial concentration":"التركيز الابتدائي","Rate constant k":"ثابت السرعة k","Half-life":"زمن النصف","First-order":"من الرتبة الأولى",
    "Vector A":"المتجه A","Vector B":"المتجه B","Resultant":"المحصلة","A magnitude":"مقدار A","A angle":"زاوية A","B magnitude":"مقدار B","B angle":"زاوية B","Resultant magnitude":"مقدار المحصلة","Resultant angle":"زاوية المحصلة","Components":"المركبات","Vertex":"الرأس","Discriminant":"المميز","Roots":"الجذور","no real roots":"لا توجد جذور حقيقية",
    "Earth":"الأرض","Moon":"القمر","Mars":"المريخ","Jupiter":"المشتري","Mercury":"عطارد","Venus":"الزهرة","Saturn":"زحل","Uranus":"أورانوس","Neptune":"نبتون","Convex":"محدبة","Concave":"مقعرة","Lever":"رافعة","Pulley":"بكرة","Inclined plane":"سطح مائل","Cube":"مكعب","Cylinder":"أسطوانة","Sphere":"كرة","Yes":"نعم","No":"لا","Real":"حقيقية","Virtual":"افتراضية","Positive":"موجب","Negative":"سالب","Up":"إلى أعلى","Down":"إلى أسفل","Low":"منخفض","Higher":"أعلى","Neutral":"متعادل","Acidic":"حمضي","Basic":"قاعدي"
  }
};

const wordMaps: Partial<Record<Locale, Record<string,string>>> = {
  es:{"Starting":"Inicial","Initial":"Inicial","Relative":"Relativo","Horizontal":"Horizontal","Vertical":"Vertical","orbital":"orbital","Orbit":"Órbita","angle":"ángulo","Angle":"Ángulo","speed":"velocidad","Speed":"Velocidad","Mass":"Masa","mass":"masa","Pressure":"Presión","pressure":"presión","Temperature":"Temperatura","temperature":"temperatura","Distance":"Distancia","distance":"distancia","Altitude":"Altitud","altitude":"altitud","Inclination":"Inclinación","inclination":"inclinación","Energy":"Energía","energy":"energía","Force":"Fuerza","force":"fuerza","Friction":"Fricción","friction":"fricción","Coefficient":"Coeficiente","coefficient":"coeficiente","Rate":"Tasa","rate":"tasa","Concentration":"Concentración","concentration":"concentración","Volume":"Volumen","volume":"volumen","Current":"Corriente","current":"corriente","Length":"Longitud","length":"longitud","Radius":"Radio","radius":"radio","Density":"Densidad","density":"densidad","Period":"Período","period":"período","Frequency":"Frecuencia","frequency":"frecuencia","Displacement":"Desplazamiento","displacement":"desplazamiento","Heat":"Calor","Humidity":"Humedad","Wind":"Viento","Water":"Agua","Air":"Aire","Ocean":"Océano","Solar":"Solar","Lunar":"Lunar","Moon":"Luna","Planet":"Planeta","World":"Mundo","Selection":"Selección","Generations":"Generaciones","Efficiency":"Eficiencia","Probability":"Probabilidad","Trials":"Ensayos","Rotation":"Rotación","Translation":"Traslación","Slope":"Pendiente","Upper":"Superior","Lower":"Inferior","Number":"Número","Atomic":"Atómico","Electron":"Electrónico","groups":"grupos","Lone":"Solitarios","pairs":"pares","Cell":"Celular","DNA":"ADN","Protein":"Proteína","Heart":"Cardíaca","Oxygen":"Oxígeno","Light":"Luz","Carbon":"Carbono","Hydrogen":"Hidrógeno","Acid":"Ácido","Base":"Base","Reactant":"Reactivo","Solute":"Soluto","Solubility":"Solubilidad","Matrix":"Matriz","Vector":"Vector","Result":"Resultado","Experimental":"Experimental","Theoretical":"Teórica","Error":"Error","Exact":"Exacta","Area":"Área","Tangent":"Tangente","Derivative":"Derivada","Orientation":"Orientación","Preserved":"Conservada","Reflected":"Reflejada","Collapsed":"Colapsada"},
  fr:{"Starting":"Initial","Initial":"Initial","Relative":"Relatif","Horizontal":"Horizontal","Vertical":"Vertical","Orbit":"Orbite","angle":"angle","Angle":"Angle","speed":"vitesse","Speed":"Vitesse","Mass":"Masse","mass":"masse","Pressure":"Pression","pressure":"pression","Temperature":"Température","temperature":"température","Distance":"Distance","distance":"distance","Altitude":"Altitude","altitude":"altitude","Inclination":"Inclinaison","inclination":"inclinaison","Energy":"Énergie","energy":"énergie","Force":"Force","force":"force","Friction":"Frottement","friction":"frottement","Coefficient":"Coefficient","coefficient":"coefficient","Rate":"Taux","rate":"taux","Concentration":"Concentration","concentration":"concentration","Volume":"Volume","volume":"volume","Current":"Courant","current":"courant","Length":"Longueur","length":"longueur","Radius":"Rayon","radius":"rayon","Density":"Densité","density":"densité","Period":"Période","period":"période","Frequency":"Fréquence","frequency":"fréquence","Displacement":"Déplacement","displacement":"déplacement","Heat":"Chaleur","Humidity":"Humidité","Wind":"Vent","Water":"Eau","Air":"Air","Ocean":"Océan","Solar":"Solaire","Lunar":"Lunaire","Moon":"Lune","Planet":"Planète","World":"Monde","Selection":"Sélection","Generations":"Générations","Efficiency":"Rendement","Probability":"Probabilité","Trials":"Essais","Rotation":"Rotation","Translation":"Translation","Slope":"Pente","Upper":"Supérieure","Number":"Nombre","Atomic":"Atomique","Electron":"Électron","groups":"groupes","Lone":"Non liantes","pairs":"paires","Cell":"Cellule","Protein":"Protéine","Heart":"Cardiaque","Oxygen":"Oxygène","Light":"Lumière","Carbon":"Carbone","Hydrogen":"Hydrogène","Acid":"Acide","Base":"Base","Reactant":"Réactif","Solute":"Soluté","Solubility":"Solubilité","Matrix":"Matrice","Vector":"Vecteur","Result":"Résultat","Experimental":"Expérimentale","Theoretical":"Théorique","Error":"Erreur","Exact":"Exacte","Area":"Aire","Tangent":"Tangente","Derivative":"Dérivée","Orientation":"Orientation","Preserved":"Conservée","Reflected":"Réfléchie","Collapsed":"Aplatie"},
  de:{"Starting":"Start","Initial":"Anfangs","Relative":"Relativ","Horizontal":"Horizontal","Vertical":"Vertikal","Orbit":"Orbit","angle":"Winkel","Angle":"Winkel","speed":"Geschwindigkeit","Speed":"Geschwindigkeit","Mass":"Masse","mass":"Masse","Pressure":"Druck","pressure":"Druck","Temperature":"Temperatur","temperature":"Temperatur","Distance":"Entfernung","distance":"Entfernung","Altitude":"Höhe","altitude":"Höhe","Inclination":"Neigung","inclination":"Neigung","Energy":"Energie","energy":"Energie","Force":"Kraft","force":"Kraft","Friction":"Reibung","friction":"Reibung","Coefficient":"Koeffizient","coefficient":"Koeffizient","Rate":"Rate","rate":"Rate","Concentration":"Konzentration","concentration":"Konzentration","Volume":"Volumen","volume":"Volumen","Current":"Strom","current":"Strom","Length":"Länge","length":"Länge","Radius":"Radius","radius":"Radius","Density":"Dichte","density":"Dichte","Period":"Periode","period":"Periode","Frequency":"Frequenz","frequency":"Frequenz","Displacement":"Verschiebung","displacement":"Verschiebung","Heat":"Wärme","Humidity":"Feuchtigkeit","Wind":"Wind","Water":"Wasser","Air":"Luft","Ocean":"Ozean","Solar":"Sonnen","Lunar":"Mond","Moon":"Mond","Planet":"Planet","World":"Himmelskörper","Selection":"Selektion","Generations":"Generationen","Efficiency":"Wirkungsgrad","Probability":"Wahrscheinlichkeit","Trials":"Versuche","Rotation":"Rotation","Translation":"Verschiebung","Slope":"Steigung","Upper":"Obere","Number":"Zahl","Atomic":"Atom","Electron":"Elektronen","groups":"Gruppen","Lone":"Freie","pairs":"Paare","Cell":"Zell","Protein":"Protein","Heart":"Herz","Oxygen":"Sauerstoff","Light":"Licht","Carbon":"Kohlenstoff","Hydrogen":"Wasserstoff","Acid":"Säure","Base":"Base","Reactant":"Reaktant","Solute":"Gelöster Stoff","Solubility":"Löslichkeit","Matrix":"Matrix","Vector":"Vektor","Result":"Ergebnis","Experimental":"Experimentell","Theoretical":"Theoretisch","Error":"Fehler","Exact":"Exakt","Area":"Fläche","Tangent":"Tangente","Derivative":"Ableitung","Orientation":"Orientierung","Preserved":"Erhalten","Reflected":"Gespiegelt","Collapsed":"Kollabiert"},
  pt:{"Starting":"Inicial","Initial":"Inicial","Relative":"Relativo","Horizontal":"Horizontal","Vertical":"Vertical","Orbit":"Órbita","angle":"ângulo","Angle":"Ângulo","speed":"velocidade","Speed":"Velocidade","Mass":"Massa","mass":"massa","Pressure":"Pressão","pressure":"pressão","Temperature":"Temperatura","temperature":"temperatura","Distance":"Distância","distance":"distância","Altitude":"Altitude","altitude":"altitude","Inclination":"Inclinação","inclination":"inclinação","Energy":"Energia","energy":"energia","Force":"Força","force":"força","Friction":"Atrito","friction":"atrito","Coefficient":"Coeficiente","coefficient":"coeficiente","Rate":"Taxa","rate":"taxa","Concentration":"Concentração","concentration":"concentração","Volume":"Volume","volume":"volume","Current":"Corrente","current":"corrente","Length":"Comprimento","length":"comprimento","Radius":"Raio","radius":"raio","Density":"Densidade","density":"densidade","Period":"Período","period":"período","Frequency":"Frequência","frequency":"frequência","Displacement":"Deslocamento","displacement":"deslocamento","Heat":"Calor","Humidity":"Umidade","Wind":"Vento","Water":"Água","Air":"Ar","Ocean":"Oceano","Solar":"Solar","Lunar":"Lunar","Moon":"Lua","Planet":"Planeta","World":"Mundo","Selection":"Seleção","Generations":"Gerações","Efficiency":"Eficiência","Probability":"Probabilidade","Trials":"Ensaios","Rotation":"Rotação","Translation":"Translação","Slope":"Inclinação","Upper":"Superior","Number":"Número","Atomic":"Atômico","Electron":"Eletrônico","groups":"grupos","Lone":"Solitários","pairs":"pares","Cell":"Celular","Protein":"Proteína","Heart":"Cardíaca","Oxygen":"Oxigênio","Light":"Luz","Carbon":"Carbono","Hydrogen":"Hidrogênio","Acid":"Ácido","Base":"Base","Reactant":"Reagente","Solute":"Soluto","Solubility":"Solubilidade","Matrix":"Matriz","Vector":"Vetor","Result":"Resultado","Experimental":"Experimental","Theoretical":"Teórica","Error":"Erro","Exact":"Exata","Area":"Área","Tangent":"Tangente","Derivative":"Derivada","Orientation":"Orientação","Preserved":"Preservada","Reflected":"Refletida","Collapsed":"Colapsada"},
  ru:{"Starting":"Начальная","Initial":"Начальная","Relative":"Относительная","Horizontal":"Горизонтальная","Vertical":"Вертикальная","Orbit":"Орбита","angle":"угол","Angle":"Угол","speed":"скорость","Speed":"Скорость","Mass":"Масса","mass":"масса","Pressure":"Давление","pressure":"давление","Temperature":"Температура","temperature":"температура","Distance":"Расстояние","distance":"расстояние","Altitude":"Высота","altitude":"высота","Inclination":"Наклон","inclination":"наклон","Energy":"Энергия","energy":"энергия","Force":"Сила","force":"сила","Friction":"Трение","friction":"трение","Coefficient":"Коэффициент","coefficient":"коэффициент","Rate":"Скорость","rate":"скорость","Concentration":"Концентрация","concentration":"концентрация","Volume":"Объём","volume":"объём","Current":"Ток","current":"ток","Length":"Длина","length":"длина","Radius":"Радиус","radius":"радиус","Density":"Плотность","density":"плотность","Period":"Период","period":"период","Frequency":"Частота","frequency":"частота","Displacement":"Смещение","displacement":"смещение","Heat":"Нагрев","Humidity":"Влажность","Wind":"Ветер","Water":"Вода","Air":"Воздух","Ocean":"Океан","Solar":"Солнечная","Lunar":"Лунная","Moon":"Луна","Planet":"Планета","World":"Мир","Selection":"Отбор","Generations":"Поколения","Efficiency":"Эффективность","Probability":"Вероятность","Trials":"Испытания","Rotation":"Поворот","Translation":"Перенос","Slope":"Наклон","Upper":"Верхняя","Number":"Число","Atomic":"Атомный","Electron":"Электронные","groups":"группы","Lone":"Неподелённые","pairs":"пары","Cell":"Клетка","Protein":"Белок","Heart":"Сердечный","Oxygen":"Кислород","Light":"Свет","Carbon":"Углерод","Hydrogen":"Водород","Acid":"Кислота","Base":"Основание","Reactant":"Реагент","Solute":"Растворённое вещество","Solubility":"Растворимость","Matrix":"Матрица","Vector":"Вектор","Result":"Результат","Experimental":"Экспериментальная","Theoretical":"Теоретическая","Error":"Ошибка","Exact":"Точный","Area":"Площадь","Tangent":"Касательная","Derivative":"Производная","Orientation":"Ориентация","Preserved":"Сохранена","Reflected":"Отражена","Collapsed":"Вырождена"},
  ja:{"Starting":"開始","Initial":"初期","Relative":"相対","Horizontal":"水平","Vertical":"垂直","Orbit":"軌道","angle":"角度","Angle":"角度","speed":"速度","Speed":"速度","Mass":"質量","mass":"質量","Pressure":"圧力","pressure":"圧力","Temperature":"温度","temperature":"温度","Distance":"距離","distance":"距離","Altitude":"高度","altitude":"高度","Inclination":"傾斜","inclination":"傾斜","Energy":"エネルギー","energy":"エネルギー","Force":"力","force":"力","Friction":"摩擦","friction":"摩擦","Coefficient":"係数","coefficient":"係数","Rate":"速度","rate":"速度","Concentration":"濃度","concentration":"濃度","Volume":"体積","volume":"体積","Current":"電流","current":"電流","Length":"長さ","length":"長さ","Radius":"半径","radius":"半径","Density":"密度","density":"密度","Period":"周期","period":"周期","Frequency":"周波数","frequency":"周波数","Displacement":"変位","displacement":"変位","Heat":"熱","Humidity":"湿度","Wind":"風","Water":"水","Air":"空気","Ocean":"海洋","Solar":"太陽","Lunar":"月","Moon":"月","Planet":"惑星","World":"天体","Selection":"選択","Generations":"世代","Efficiency":"効率","Probability":"確率","Trials":"試行","Rotation":"回転","Translation":"平行移動","Slope":"傾き","Upper":"上限","Number":"番号","Atomic":"原子","Electron":"電子","groups":"グループ","Lone":"孤立","pairs":"電子対","Cell":"細胞","Protein":"タンパク質","Heart":"心臓","Oxygen":"酸素","Light":"光","Carbon":"炭素","Hydrogen":"水素","Acid":"酸","Base":"塩基","Reactant":"反応物","Solute":"溶質","Solubility":"溶解度","Matrix":"行列","Vector":"ベクトル","Result":"結果","Experimental":"実験","Theoretical":"理論","Error":"誤差","Exact":"厳密","Area":"面積","Tangent":"接線","Derivative":"導関数","Orientation":"向き","Preserved":"保持","Reflected":"反転","Collapsed":"退化"},
  zh:{"Starting":"起始","Initial":"初始","Relative":"相对","Horizontal":"水平","Vertical":"垂直","Orbit":"轨道","angle":"角度","Angle":"角度","speed":"速度","Speed":"速度","Mass":"质量","mass":"质量","Pressure":"压力","pressure":"压力","Temperature":"温度","temperature":"温度","Distance":"距离","distance":"距离","Altitude":"高度","altitude":"高度","Inclination":"倾角","inclination":"倾角","Energy":"能量","energy":"能量","Force":"力","force":"力","Friction":"摩擦","friction":"摩擦","Coefficient":"系数","coefficient":"系数","Rate":"速率","rate":"速率","Concentration":"浓度","concentration":"浓度","Volume":"体积","volume":"体积","Current":"电流","current":"电流","Length":"长度","length":"长度","Radius":"半径","radius":"半径","Density":"密度","density":"密度","Period":"周期","period":"周期","Frequency":"频率","frequency":"频率","Displacement":"位移","displacement":"位移","Heat":"热量","Humidity":"湿度","Wind":"风","Water":"水","Air":"空气","Ocean":"海洋","Solar":"太阳","Lunar":"月球","Moon":"月球","Planet":"行星","World":"天体","Selection":"选择","Generations":"世代","Efficiency":"效率","Probability":"概率","Trials":"试验次数","Rotation":"旋转","Translation":"平移","Slope":"斜率","Upper":"上限","Number":"编号","Atomic":"原子","Electron":"电子","groups":"组","Lone":"孤","pairs":"对","Cell":"细胞","Protein":"蛋白质","Heart":"心脏","Oxygen":"氧","Light":"光","Carbon":"碳","Hydrogen":"氢","Acid":"酸","Base":"碱","Reactant":"反应物","Solute":"溶质","Solubility":"溶解度","Matrix":"矩阵","Vector":"向量","Result":"结果","Experimental":"实验","Theoretical":"理论","Error":"误差","Exact":"精确","Area":"面积","Tangent":"切线","Derivative":"导数","Orientation":"方向","Preserved":"保持","Reflected":"反射","Collapsed":"退化"},
  ar:{"Starting":"ابتدائي","Initial":"ابتدائي","Relative":"نسبي","Horizontal":"أفقي","Vertical":"رأسي","Orbit":"مدار","angle":"زاوية","Angle":"زاوية","speed":"سرعة","Speed":"سرعة","Mass":"كتلة","mass":"كتلة","Pressure":"ضغط","pressure":"ضغط","Temperature":"درجة الحرارة","temperature":"درجة الحرارة","Distance":"مسافة","distance":"مسافة","Altitude":"ارتفاع","altitude":"ارتفاع","Inclination":"ميل","inclination":"ميل","Energy":"طاقة","energy":"طاقة","Force":"قوة","force":"قوة","Friction":"احتكاك","friction":"احتكاك","Coefficient":"معامل","coefficient":"معامل","Rate":"معدل","rate":"معدل","Concentration":"تركيز","concentration":"تركيز","Volume":"حجم","volume":"حجم","Current":"تيار","current":"تيار","Length":"طول","length":"طول","Radius":"نصف القطر","radius":"نصف القطر","Density":"كثافة","density":"كثافة","Period":"فترة","period":"فترة","Frequency":"تردد","frequency":"تردد","Displacement":"إزاحة","displacement":"إزاحة","Heat":"حرارة","Humidity":"رطوبة","Wind":"رياح","Water":"ماء","Air":"هواء","Ocean":"محيط","Solar":"شمسي","Lunar":"قمري","Moon":"القمر","Planet":"كوكب","World":"عالم","Selection":"انتخاب","Generations":"أجيال","Efficiency":"كفاءة","Probability":"احتمال","Trials":"تجارب","Rotation":"دوران","Translation":"إزاحة","Slope":"ميل","Upper":"علوي","Number":"رقم","Atomic":"ذري","Electron":"إلكترون","groups":"مجموعات","Lone":"منفردة","pairs":"أزواج","Cell":"خلية","Protein":"بروتين","Heart":"قلب","Oxygen":"أكسجين","Light":"ضوء","Carbon":"كربون","Hydrogen":"هيدروجين","Acid":"حمض","Base":"قاعدة","Reactant":"متفاعل","Solute":"مذاب","Solubility":"ذوبانية","Matrix":"مصفوفة","Vector":"متجه","Result":"نتيجة","Experimental":"تجريبي","Theoretical":"نظري","Error":"خطأ","Exact":"دقيق","Area":"مساحة","Tangent":"مماس","Derivative":"مشتقة","Orientation":"اتجاه","Preserved":"محفوظ","Reflected":"معكوس","Collapsed":"منهار"}
};

function replaceWords(text: string, locale: Locale) {
  const map = wordMaps[locale];
  if (!map) return text;
  let out = text;
  for (const [from,to] of Object.entries(map).sort((a,b)=>b[0].length-a[0].length)) {
    const escaped=from.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");
    out=out.replace(new RegExp(`\\b${escaped}\\b`,"g"),to);
  }
  if (locale === "zh" || locale === "ja") out=out.replace(/\s+/g, "");
  return out;
}

export function runtimeText(localeValue: string, text: string): string {
  const locale = isLocale(localeValue) ? localeValue : "en";
  if (locale === "en" || !text) return text;
  const control = translatedControlLabel(locale, text);
  if (control) return control;
  const phrase = translatedPhrase(locale, text);
  if (phrase) return phrase;
  const direct=exact[locale]?.[text];
  if (direct) return direct;
  return replaceWords(text,locale);
}

export function runtimeMetricValue(localeValue: string, text: string): string {
  const locale = isLocale(localeValue) ? localeValue : "en";
  if (locale === "en" || !text) return text;
  const phrase = translatedPhrase(locale, text);
  if (phrase) return phrase;
  const direct=exact[locale]?.[text];
  if (direct) return direct;
  let out=replaceWords(text,locale);
  const dayWord:Record<Exclude<Locale,"en">,string>={es:"días",fr:"jours",de:"Tage",pt:"dias",ru:"дн.",ja:"日",zh:"天",ar:"يوم"};
  out=out.replace(/\b(\d+(?:\.\d+)?) days\b/g,(_,n)=>locale==="ja"||locale==="zh"?`${n}${dayWord[locale as Exclude<Locale,"en">]}`:`${n} ${dayWord[locale as Exclude<Locale,"en">]}`);
  const millionYear:Record<Exclude<Locale,"en">,string>={es:"millones de años",fr:"millions d’années",de:"Mio. Jahre",pt:"milhões de anos",ru:"млн лет",ja:"百万年",zh:"百万年",ar:"مليون سنة"};
  out=out.replace(/\b(\d+(?:\.\d+)?) million yr\b/g,(_,n)=>locale==="ja"||locale==="zh"?`${n}${millionYear[locale as Exclude<Locale,"en">]}`:`${n} ${millionYear[locale as Exclude<Locale,"en">]}`);
  return out;
}

export function runtimeFormula(localeValue: string, formula: string, localizedFallback: string): string {
  const locale = isLocale(localeValue) ? localeValue : "en";
  if (locale === "en") return formula;

  // Equations and symbols stay unchanged. Prose-heavy model shorthand is replaced by the
  // already translated learning outcome so non-English pages never expose English sentences.
  const clauses = formula.split(/[·;]/).map((part) => part.trim()).filter(Boolean);
  const mathClauses = clauses.flatMap((part) => {
    const withoutNote = part.replace(/\([^)]*[A-Za-z]{3,}[^)]*\)/g, "").trim();
    if (!/[=≈√∝]/.test(withoutNote)) return [];
    const words = (withoutNote.match(/[A-Za-z]{3,}/g) ?? []).filter((word) => !["sin","cos","tan","sqrt","log","exp","VSEPR"].includes(word));
    return words.length <= 2 ? [withoutNote] : [];
  });
  return mathClauses.length ? `${localizedFallback} · ${mathClauses.join(" · ")}` : localizedFallback;
}
