import Link from "next/link";
import { ContactForm } from "@/components/contact/ContactForm";
import { CookieSettingsButton } from "@/components/privacy/ConsentManager";
import { siteName } from "@/lib/seo/metadata";

export type InfoPageKey = "about" | "contact" | "privacy" | "cookies" | "terms" | "disclaimer" | "editorial-policy" | "faq" | "accessibility";
export const contactEmail = process.env.NEXT_PUBLIC_CONTACT_EMAIL || "contactus@leanerkits.com";
export const informationUpdatedAt = "2026-10-03";
export const infoMeta: Record<InfoPageKey, { title: string; description: string }> = {
  about: { title: `About ${siteName}`, description: "Meet the people behind LearnerKits and discover our approach to free, interactive science education." },
  contact: { title: `Contact ${siteName}`, description: "Send LearnerKits a question, report a science correction, or get help with accessibility, privacy, and classroom use." },
  privacy: { title: "Privacy Policy", description: "How LearnerKits handles contact messages, browser storage, analytics, advertising, and your privacy choices." },
  cookies: { title: "Cookie Policy", description: "Understand essential browser storage, optional analytics, advertising cookies, and how to change your choices." },
  terms: { title: "Terms and Conditions", description: "Terms for using LearnerKits simulations, articles, classroom resources, and contact services." },
  disclaimer: { title: "Educational Disclaimer", description: "The scope and limitations of LearnerKits science models, learning materials, and external references." },
  "editorial-policy": { title: "Editorial Policy", description: "Our approach to educational content, scientific sources, corrections, AI assistance, and advertising independence." },
  faq: { title: "Frequently Asked Questions", description: "Help with free access, classroom use, saved progress, browser requirements, and reporting problems." },
  accessibility: { title: "Accessibility", description: "Accessibility features, known limitations of interactive simulations, and how to request help." },
};
const Updated = () => <p className="legalUpdated">Last updated: <time dateTime={informationUpdatedAt}>October 3, 2026</time></p>;
const ContactLink = () => <a href={`mailto:${contactEmail}`}>{contactEmail}</a>;

function About({ locale }: { locale: string }) {
  return <>
    <p className="legalLead">Science makes more sense when you can change something and see what happens. LearnerKits is an independent educational website built around that idea: predict, experiment, and explain.</p>
    <section><h2>What you can learn here</h2><p>Our browser-based activities cover space and astronomy, physics and engineering, geography and Earth science, environmental science, chemistry, and mathematics. Move a slider, compare two trials, or build a model to explore how variables affect an outcome.</p><p>Science guides and articles add explanations, investigation prompts, and links to supporting sources. Together, these resources give learners a starting point for asking better questions, rather than simply memorizing an answer.</p></section>
    <section><h2>Who is behind LearnerKits?</h2><p>LearnerKits is owned by Shafaq Sheikh, Abbas Haider, and Ali Faraz. The owners share responsibility for the website and welcome questions about its content and operation.</p><ul><li><a href="https://www.linkedin.com/in/shafaq-shaikh/" target="_blank" rel="noreferrer">Shafaq Sheikh — LinkedIn</a></li><li><a href="https://www.linkedin.com/in/abbashaider-n/" target="_blank" rel="noreferrer">Abbas Haider — LinkedIn</a></li><li><a href="https://www.linkedin.com/in/ali-faraz-358162209/" target="_blank" rel="noreferrer">Ali Faraz — LinkedIn</a></li></ul><p>For website enquiries, use our <Link href={`/${locale}/contact`}>contact form</Link> or email <ContactLink/>.</p></section>
    <section><h2>For learners, families, and teachers</h2><p>Many activities are designed around middle- and secondary-school concepts, with suggested grade bands on individual labs. Curious learners of any age can explore. Teachers and guardians should choose activities that fit the learner’s needs and supervise younger children.</p><p>Try one investigation at a time: write down a prediction, change one variable, record an observation, and explain the result. Teachers can project a lab, share a link, or use a guide alongside a lesson. The site does not award qualifications or replace a school curriculum.</p></section>
    <section><h2>Our approach to accuracy</h2><p>A useful learning model is not a complete copy of the real world. We explain assumptions and limitations and welcome corrections with a page link and supporting reference. Our <Link href={`/${locale}/editorial-policy`}>editorial policy</Link> describes how we approach sources and updates.</p></section>
    <section><h2>Free access and support</h2><p>Public learning activities do not require a learner account or paid subscription. Optional donations help support the project. Advertising, when enabled, may also support its operation; it does not determine scientific explanations or activity outcomes. A donation does not purchase a grade, certificate, or additional learning access.</p></section>
    <section><h2>Start with a question</h2><div className="legalActions"><Link className="button primary" href={`/${locale}/subjects`}>Browse subjects</Link><Link className="button" href={`/${locale}/simulations`}>Explore simulations</Link><Link className="button" href={`/${locale}/faq`}>Read common questions</Link></div></section>
  </>;
}

function Contact({ locale }: { locale: string }) {
  return <>
    <p className="legalLead">Have a question, found an error, or need help using a lab? Send the LearnerKits team a message.</p>
    <section><h2>Send us a message</h2><p>Choose the topic that best matches your enquiry. For a technical problem, include the page link, browser or device, and what you expected to happen. For a scientific correction, include the explanation in question and a supporting source if available.</p><ContactForm locale={locale}/></section>
    <section className="contactCard"><span aria-hidden="true">✉</span><div><h2>Prefer email?</h2><p><ContactLink/></p><small>This address also handles privacy requests, accessibility feedback, licensing enquiries, and donation questions.</small></div></section>
    <section><h2>What happens next?</h2><p>Your message is saved for the LearnerKits team to review. We may reply to the email address you provide if we need more details or have an answer. Response times vary; this is not an emergency or live-support service.</p><p>For donation support, include the payment date and amount or receipt reference. Do not send complete card details. Contact messages are used to handle your enquiry, not to sign you up for marketing. See our <Link href={`/${locale}/privacy`}>Privacy Policy</Link> for details.</p></section>
  </>;
}

function Privacy({ locale }: { locale: string }) {
  return <><Updated/>
    <p className="legalLead">This policy explains the information processed when you use LearnerKits, send an enquiry, or choose optional services.</p>
    <section><h2>Who is responsible</h2><p>LearnerKits is operated by its owners, Shafaq Sheikh, Abbas Haider, and Ali Faraz. Contact <ContactLink/> or use the <Link href={`/${locale}/contact`}>contact form</Link> for questions about this policy or your information.</p></section>
    <section><h2>Learning without an account</h2><p>You can browse public learning resources without creating a learner account. Language, theme, accessibility preferences, and supported activity progress may be saved in your browser using local storage or a preference cookie. These settings are not a cloud learner profile and do not automatically sync across devices.</p></section>
    <section><h2>Contact messages</h2><p>When you submit the contact form, we collect your name or preferred name, email address, topic, message, page language, submission time, and the version of the privacy notice you acknowledged. We use this information to respond, investigate issues, handle rights requests, and protect the form against abuse.</p><p>Messages are stored in a Supabase-hosted database. Access is restricted to the service and authorized people handling enquiries. The form does not deliberately store your IP address or browser user agent with your message. Hosting and security services may separately process request information.</p><p>We keep correspondence for as long as it is needed to handle the enquiry, follow-up, or relevant legal obligations, and review it for removal when no longer needed. You may ask us to delete a message using the contact details above. Email correspondence may also remain with our email provider. Do not include sensitive personal information or other people’s student records.</p></section>
    <section><h2>Hosting and security</h2><p>Our hosting provider, Cloudflare, processes requests to deliver the website and protect it from abuse. This can include IP addresses, requested URLs, timestamps, browser information, and technical logs. Read <a href="https://www.cloudflare.com/privacypolicy/" target="_blank" rel="noreferrer">Cloudflare’s privacy policy</a> and <a href="https://supabase.com/privacy" target="_blank" rel="noreferrer">Supabase’s privacy policy</a> for provider information.</p></section>
    <section><h2>Optional analytics</h2><p>If you select “Allow analytics,” Google Analytics and Microsoft Clarity can process usage and interaction information, device and browser details, referral information, approximate location, and identifiers. Clarity may provide recordings of interactions to help us understand usability problems. Contact-form fields are marked for masking in Clarity.</p><p>Our consent manager does not load these analytics scripts before your choice or when you select “Essential only.” You can reopen your choices through the <Link href={`/${locale}/cookies`}>Cookie Policy</Link>. Withdrawing permission stops future loading; it does not automatically erase data already collected by providers.</p><p>See <a href="https://policies.google.com/privacy" target="_blank" rel="noreferrer">Google’s Privacy Policy</a> and <a href="https://privacy.microsoft.com/privacystatement" target="_blank" rel="noreferrer">Microsoft’s Privacy Statement</a>.</p></section>
    <section><h2>Advertising and Google AdSense</h2><p>When advertising is enabled, third-party vendors, including Google, may place or read cookies, use web beacons, and process IP addresses or other identifiers to serve, measure, and, where permitted, personalize ads. Google’s use of advertising cookies enables it and its partners to serve ads based on visits to this website and other websites.</p><p>You can manage personalized advertising through <a href="https://adssettings.google.com/" target="_blank" rel="noreferrer">Google Ads Settings</a> and participating vendors through <a href="https://www.aboutads.info/choices/" target="_blank" rel="noreferrer">YourAdChoices</a>. Learn <a href="https://policies.google.com/technologies/partner-sites" target="_blank" rel="noreferrer">how Google uses information from sites that use its services</a>. Advertising consent, when requested, is separate from this site’s optional analytics choice. Non-personalized ads may still involve cookies or other data processing.</p></section>
    <section><h2>Donations</h2><p>If you choose to donate, the amount and language are used to prepare a hosted checkout. Stripe processes payment details under <a href="https://stripe.com/privacy" target="_blank" rel="noreferrer">its privacy policy</a>. We do not collect full payment-card details through our contact form or store them in the contact database. Donation records may be retained for payment support and accounting obligations.</p></section>
    <section><h2>Purposes, providers, and international processing</h2><p>We process enquiries to respond to requests and maintain the service, rely on your consent for optional analytics where required, and may retain information to meet legal obligations. Where applicable, legitimate interests include protecting the website and resolving support issues. We do not use contact messages as advertising mailing lists or sell them to advertisers.</p><p>Hosting, database, analytics, advertising, and payment providers may process information in countries other than your own. Applicable protections depend on the service and relevant law; their privacy notices describe their practices.</p></section>
    <section><h2>Children and classroom use</h2><p>The learning activities do not require children to submit personal information. Children under 13 should ask a parent, guardian, or teacher to contact us instead of using the form. Please tell us if you believe a child has sent personal information so we can review and remove it where appropriate. Teachers should avoid including identifiable student work or records in enquiries.</p></section>
    <section><h2>Your choices and rights</h2><p>You can clear browser storage, decline optional analytics, manage advertising preferences, and contact us about your messages. Depending on your location, you may have rights to access, correct, erase, restrict, object to processing, request portability, withdraw consent, or complain to your local data-protection authority. We may need reasonable information to verify a request; please do not send identity documents unless a necessary secure process has been agreed.</p></section>
    <section><h2>Updates</h2><p>We will revise this page when our practices change. The date above identifies the current policy.</p></section>
  </>;
}

function Cookies() {
  return <><Updated/><p className="legalLead">LearnerKits uses browser storage to remember your choices. Optional analytics and advertising have separate purposes.</p>
    <section><h2>Essential preferences and local progress</h2><div className="legalTable"><div><b>Language preference</b><span>The science-sim-locale cookie and local storage remember the language you select.</span><em>Cookie: up to 1 year</em></div><div><b>Settings and progress</b><span>science-sim-settings-v1 and science-sim-progress-v1 store display preferences and supported activity progress on your device.</span><em>Until cleared</em></div><div><b>Analytics choice</b><span>learnerkits-cookie-consent-v1 remembers whether you chose optional analytics or essential storage only.</span><em>Until reset or cleared</em></div></div></section>
    <section><h2>Optional analytics</h2><p>Google Analytics and Microsoft Clarity load after “Allow analytics” is selected. They may use cookies and similar technologies to understand visits, navigation, interactions, and technical issues. Provider cookie lifetimes vary by configuration. Choosing “Essential only” allows you to keep using the learning activities.</p></section>
    <section><h2>Advertising technologies</h2><p>When advertising is enabled, Google and its partners may use cookies or similar identifiers to deliver and measure ads. Advertising choices are handled separately through the advertising privacy message where available. The “Allow analytics” button does not grant advertising consent. You can also manage personalization in <a href="https://adssettings.google.com/" target="_blank" rel="noreferrer">Google Ads Settings</a>.</p></section>
    <section><h2>Change your analytics choice</h2><p>The button below resets your choice and reopens the notice. If analytics was already running, the page reloads to stop it. Browser privacy settings can remove existing cookies and storage; clearing all site data also removes saved settings and activity progress.</p><CookieSettingsButton/></section>
  </>;
}

function Terms({ locale }: { locale: string }) {
  return <><Updated/><p className="legalLead">These terms apply to the LearnerKits website, simulations, guides, articles, and contact services. By using the website, you agree to these terms.</p>
    <section><h2>About the service</h2><p>LearnerKits is an educational project owned by Shafaq Sheikh, Abbas Haider, and Ali Faraz. Public activities are available for personal learning and ordinary classroom teaching. You may share links to public pages. The site does not provide accredited qualifications, professional advice, or guaranteed learning outcomes.</p></section>
    <section><h2>Responsible use</h2><p>Use the site lawfully and respect other people’s rights. Do not attempt unauthorized access, introduce malicious software, disrupt activities, submit abusive or deceptive messages, or send other people’s private information without permission. Automated access must not overload the service or bypass access restrictions.</p><p>Do not generate artificial ad impressions or clicks, encourage others to click ads to support the site, or misrepresent an advertisement as learning content. You never need to click an advertisement to complete an activity.</p></section>
    <section><h2>Content and intellectual property</h2><p>Original text, code, designs, and visualizations belong to their respective owners. Third-party sources, assets, and libraries retain their own licenses and attribution requirements. Ordinary classroom use does not transfer ownership or grant permission to resell, republish substantial parts of the site, or remove attribution. Contact us about broader reuse; rights provided by applicable law remain unaffected.</p></section>
    <section><h2>Messages and feedback</h2><p>Only submit information you are entitled to share. You allow us to use a message to respond, investigate a reported issue, and improve the service. Sending feedback does not transfer ownership of your unrelated work. Personal information is handled as described in the <Link href={`/${locale}/privacy`}>Privacy Policy</Link>.</p></section>
    <section><h2>Donations and third-party services</h2><p>Donations are voluntary and do not buy a subscription or access advantage. Payment processing is subject to the checkout provider’s terms. Contact us about a duplicate or mistaken payment; any applicable statutory rights remain in place. We do not represent donations as tax-deductible charitable contributions.</p><p>External references and advertisements lead to services we do not control. A link or advertisement is not an endorsement or a promise about an external service.</p></section>
    <section><h2>Availability and model limitations</h2><p>Activities may be changed, corrected, or withdrawn. Browser compatibility and saved local progress are not guaranteed. Content is provided “as is” and “as available” to the extent allowed by law. Read the <Link href={`/${locale}/disclaimer`}>Educational Disclaimer</Link> before applying a model’s results outside a learning exercise.</p></section>
    <section><h2>Liability and your legal rights</h2><p>To the extent permitted by applicable law, LearnerKits and its owners are not liable for indirect or consequential loss from use of the website. Nothing in these terms excludes liability or consumer rights that cannot legally be excluded.</p></section>
    <section><h2>Changes and questions</h2><p>We may update these terms as the service changes; the date above identifies the current version. Questions about these terms or use of content can be sent to <ContactLink/>.</p></section>
  </>;
}

function Disclaimer({ locale }: { locale: string }) {
  return <><Updated/><p className="legalLead">LearnerKits simulations explain concepts. They are educational models, not professional calculators or systems for real-world decisions.</p>
    <section><h2>Why a simulation differs from reality</h2><p>A model may omit friction, simplify materials, assume ideal conditions, compress time, rescale objects, or use a representative relationship instead of a full scientific forecast. Attractive 3D visuals do not establish physical precision. Read each activity’s model assumptions, units, and explanation before interpreting its output.</p></section>
    <section><h2>Learning and safety</h2><p>Do not use this website to make medical, engineering, environmental-safety, emergency, financial, legal, or other professional decisions. Earthquake, tsunami, weather, and climate activities are not live warnings or forecasts. Chemistry demonstrations do not authorize mixing real substances; practical work requires suitable supervision and safety procedures.</p></section>
    <section><h2>Accuracy and sources</h2><p>Errors and outdated explanations can occur. Sources are provided for further study, and a link does not imply endorsement of every statement on another site. Compare important claims with appropriate authoritative references.</p></section>
    <section><h2>Help us correct a problem</h2><p>Send the page link, the settings or steps that produced the result, and a supporting source through the <Link href={`/${locale}/contact`}>contact page</Link>. Our <Link href={`/${locale}/editorial-policy`}>editorial policy</Link> explains how we approach corrections.</p></section>
  </>;
}

function Editorial({ locale }: { locale: string }) {
  return <><Updated/><p className="legalLead">Our goal is to make interactive science understandable and transparent about what a model can and cannot show.</p>
    <section><h2>Responsibility for content</h2><p>The LearnerKits owners are responsible for the website’s educational content and its updates. Content is not represented as independently peer-reviewed or certified by a scientific institution unless a specific resource explicitly states that and provides evidence.</p></section>
    <section><h2>How we approach a learning resource</h2><ol><li><b>Start with a question.</b> Identify a concept a learner can investigate.</li><li><b>Choose a model.</b> Make the variables, relationships, and useful range of the model clear.</li><li><b>Connect controls with observations.</b> Give learners a way to compare outcomes and test a prediction.</li><li><b>Check the explanation against the activity.</b> Review calculations, units, controls, and representative cases as changes are made.</li><li><b>Describe limitations.</b> Explain omitted factors and distinguish illustrative models from predictive tools.</li></ol></section>
    <section><h2>Sources and original work</h2><p>We prefer primary and authoritative references, such as scientific agencies, universities, official documentation, and relevant research. Guides and articles include source links for further reading. A list of references is not a claim that those organizations endorse LearnerKits. Third-party material should retain its required attribution.</p></section>
    <section><h2>AI-assisted development and writing</h2><p>Automated tools may help draft text, develop simulations, translate interface content, create illustrations, and test code. AI output is not a scientific authority and may contain mistakes. Readers should use the linked references and report unclear or inconsistent explanations. Translations may vary in completeness; information and policy pages are currently written in English.</p></section>
    <section><h2>Corrections and updates</h2><p>Use the <Link href={`/${locale}/contact`}>contact form</Link> and select “Science correction.” Include the page link, the statement or result in question, and a reliable reference if available. We assess reports against the activity’s intended scope and supporting material, then revise the model, text, or explanation of limitations when a correction is needed. Article dates and policy revision dates identify updates where shown.</p></section>
    <section><h2>Advertising and editorial independence</h2><p>Advertising and voluntary donations may support running the site. They do not determine scientific conclusions, simulation outcomes, or source selection. Sponsored editorial material or affiliate relationships, if introduced, should be clearly disclosed alongside the relevant content. Advertisements are separate from learning instructions.</p></section>
  </>;
}

function FAQ({ locale }: { locale: string }) {
  return <><p className="legalLead">A few practical answers before you start experimenting.</p>
    <section><h2>Is LearnerKits free? Do I need an account?</h2><p>Public simulations, guides, and articles are free to explore without a learner account. Donations are optional.</p></section>
    <section><h2>Can I use a simulation in my classroom?</h2><p>Yes. Share a public link or display an activity during ordinary classroom teaching. Choose activities that match your learners and review model limitations with them. Contact us about republishing material, commercial licensing, or other uses beyond ordinary teaching.</p></section>
    <section><h2>Where should I start?</h2><p>Choose a topic in the <Link href={`/${locale}/subjects`}>subject library</Link>. Make a prediction, change one setting, and explain what you observe. A short comparison of two trials is often more useful than changing every setting at once.</p></section>
    <section><h2>Why does a 3D activity look blank or run slowly?</h2><p>Interactive labs need JavaScript and a modern browser; 3D scenes also need WebGL support. Try an updated browser, close other graphics-heavy tabs, and check whether your browser allows hardware acceleration. Some school-managed devices restrict these features. Tell us the page link and device/browser if a problem continues.</p></section>
    <section><h2>Will my progress follow me to another device?</h2><p>No. Supported progress and settings are saved in the current browser. Private browsing, clearing site data, or switching devices can remove or separate those records. The site does not provide cloud progress synchronization.</p></section>
    <section><h2>Are simulation results exact?</h2><p>They depend on the model and its assumptions. Some activities use idealized equations; others use illustrative relationships. Read the activity’s explanation and our <Link href={`/${locale}/disclaimer`}>Educational Disclaimer</Link>.</p></section>
    <section><h2>How do I report an error or change privacy choices?</h2><p>Use the <Link href={`/${locale}/contact`}>contact form</Link> to report an error, request help, or ask about personal information. Open the <Link href={`/${locale}/cookies`}>Cookie Policy</Link> to change optional analytics choices.</p></section>
  </>;
}

function Accessibility({ locale }: { locale: string }) {
  return <><Updated/><p className="legalLead">We want more people to be able to explore science. Accessibility feedback helps us identify barriers in both reading pages and interactive activities.</p>
    <section><h2>Available options</h2><p>The <Link href={`/${locale}/settings`}>settings page</Link> includes display and motion preferences. Browser zoom can enlarge text and controls. The contact form uses visible labels, keyboard-accessible fields, and status messages for submission results.</p></section>
    <section><h2>Known limitations</h2><p>Some simulations depend on visual canvas or 3D WebGL scenes, color, motion, or precise pointer interaction. These experiences may not convey all information to screen readers or offer an equivalent keyboard-only interaction. Written explanations provide context but may not fully replace an interactive scene. We do not claim complete conformance with an accessibility standard.</p></section>
    <section><h2>Tell us what would help</h2><p>Choose “Accessibility” on the <Link href={`/${locale}/contact`}>contact form</Link> or email <ContactLink/>. Include the page link, the task you were trying to complete, and, if useful, the browser or assistive technology involved. You do not need to disclose a medical condition. We will review the barrier and consider a correction or alternative explanation.</p></section>
  </>;
}

export function InfoPage({ page, locale }: { page: InfoPageKey; locale: string }) {
  const meta = infoMeta[page];
  const content = { about: <About locale={locale}/>, contact: <Contact locale={locale}/>, privacy: <Privacy locale={locale}/>, cookies: <Cookies/>, terms: <Terms locale={locale}/>, disclaimer: <Disclaimer locale={locale}/>, "editorial-policy": <Editorial locale={locale}/>, faq: <FAQ locale={locale}/>, accessibility: <Accessibility locale={locale}/> };
  return <main className="container legalPage" lang="en" dir="ltr">
    <header className="legalHero"><span className="eyebrow">LearnerKits information</span><h1>{meta.title}</h1><p>{meta.description}</p></header>
    <nav className="legalNav" aria-label="Information pages">{(Object.keys(infoMeta) as InfoPageKey[]).map(key => <Link key={key} href={`/${locale}/${key}`} aria-current={page === key ? "page" : undefined}>{key === "about" ? "About" : key === "contact" ? "Contact" : key === "faq" ? "FAQ" : infoMeta[key].title}</Link>)}</nav>
    <article className="legalArticle">{content[page]}</article>
    <aside className="legalHelp"><strong>{page === "contact" ? "Looking for help getting started?" : "Need clarification or want to report a correction?"}</strong><Link href={`/${locale}/${page === "contact" ? "faq" : "contact"}`}>{page === "contact" ? "Read common questions" : "Contact LearnerKits"} →</Link></aside>
  </main>;
}
