export type Values=Record<string,number>;
export type Control={key:string;label:string;min:number;max:number;step:number;initial:number;unit?:string;options?:string[]};
export type Activity={slug:string;tag:string;mission:string;hint:string;science:string;controls:Control[];run?:boolean;source?:[string,string]};
const r=(key:string,label:string,min:number,max:number,step:number,initial:number,unit=""):Control=>({key,label,min,max,step,initial,unit});
const s=(key:string,label:string,options:string[],initial=0):Control=>({key,label,min:0,max:options.length-1,step:1,initial,options});
export const activities:Activity[]=[
 {slug:"seismic-wave-lab",tag:"SIGNAL DETECTIVE",mission:"Record the waves, then estimate the source distance to within 10 km using the S–P arrival gap.",hint:"Distance = (S arrival − P arrival) ÷ (1/3.5 − 1/6). Read both arrivals after running the recording.",science:"Straight ray paths through a uniform medium: P speed 6 km/s, S speed 3.5 km/s. Waveforms are illustrative; arrival times are calculated. Real Earth has layered, varying wave speeds.",run:true,controls:[r("distance","Source distance",100,500,10,280,"km"),r("estimate","Your distance estimate",0,600,5,150,"km")],source:["USGS: earthquake science","https://www.usgs.gov/programs/earthquake-hazards/science-earthquakes"]},
 {slug:"plate-motion-lab",tag:"DEEP-TIME ENGINEER",mission:"Move a plate 500 ± 20 km east while keeping its northward displacement below 20 km.",hint:"Displacement in km = speed in cm/year × time in million years × 10. Try 5 cm/year, 10 million years, heading 0°.",science:"Constant velocity on a local flat map. Heading 0° is east; 90° is north. The motion is greatly accelerated and does not predict actual future plate positions.",run:true,controls:[r("speed","Plate speed",1,12,.5,4,"cm/year"),r("years","Elapsed geologic time",1,20,.5,8,"million years"),r("heading","Heading from east",0,360,5,30,"°")]},
 {slug:"volcano-eruption-3d",tag:"MAGMA LAB",mission:"Run and record one effusive eruption and one explosive eruption.",hint:"Try gas 1% and viscosity 10² Pa·s for flowing lava. Then use gas 6% and viscosity 10⁶ Pa·s for an ash-rich eruption.",science:"Qualitative teaching model: a gas-retention index combines gas fraction and log viscosity. Higher viscosity traps gas; more retained gas favors explosive activity. The index and visuals are not a pressure forecast or a real volcano hazard assessment.",run:true,controls:[r("gas","Dissolved gas",0,8,.5,2,"%"),r("viscosity","Log₁₀ magma viscosity",2,7,.5,3,"Pa·s exponent")],source:["USGS: volcanoes","https://pubs.usgs.gov/gip/volcus/ustext.html"]},
 {slug:"earthquake-epicenter-finder",tag:"EPICENTER HUNT",mission:"Use three station arrival gaps to place the epicenter within 12 km. Solve all three events.",hint:"Show distance rings. Their common intersection locates the source. Click the map or use the coordinate sliders.",science:"Planar epicenter triangulation with a surface source and constant P/S velocities (6 and 3.5 km/s). Each ring radius is calculated from its station's S–P time difference. Real location methods include depth and heterogeneous Earth structure.",controls:[s("event","Earthquake event",["Event A","Event B","Event C"]),s("rings","Distance rings",["Show rings","Hide rings"]),r("x","Marker east coordinate",0,600,1,300,"km"),r("y","Marker north coordinate",0,350,1,150,"km")]},
 {slug:"plate-tectonics-3d",tag:"BOUNDARY BUILDER",mission:"Run all three boundaries and correctly identify the resulting landform at each.",hint:"Divergent → spreading ridge; convergent → trench and volcanic arc; transform → offset fault.",science:"Kinematic cross-section, not a mantle convection solver. The convergent example is oceanic subduction; not all convergent boundaries produce this geometry. Movement and vertical scales are exaggerated.",run:true,controls:[s("boundary","Plate boundary",["Divergent","Convergent","Transform"]),r("rate","Relative motion",1,10,1,5,"cm/year"),s("landform","Identify the landform",["Choose a landform","Spreading ridge","Trench and volcanic arc","Offset fault"])]},
 {slug:"tsunami-3d",tag:"WAVE TRACKER",mission:"Run the wave and estimate its travel time to the coast to within 2 minutes.",hint:"Deep-water speed = √(9.81 × depth). Divide offshore distance by that speed, then convert seconds to minutes.",science:"Long-wave speed c = √(gh) in constant-depth water. Coastal amplitude uses idealized Green's-law shoaling to a 20 m shelf, not a run-up calculation. Reflection, breaking, coastal shape and flooding are omitted. Educational only: never use this for evacuation decisions.",run:true,controls:[r("depth","Offshore water depth",500,6000,100,4000,"m"),r("distance","Distance to coast",50,500,10,200,"km"),r("uplift","Initial wave amplitude",.2,3,.1,1,"m"),r("estimate","Your travel-time estimate",0,120,1,30,"min")],source:["NOAA: tsunami propagation","https://www.ncei.noaa.gov/products/natural-hazards/tsunamis-earthquakes-volcanoes/tsunamis/global-historical-data"]},
 {slug:"hurricane-simulator",tag:"STORM LAB",mission:"Record both an organized and a disrupted storm by changing its environment.",hint:"Warm water (29°C), low shear (5 m/s), and latitude 20° support organization. Increase shear to 30 m/s to disrupt it.",science:"Qualitative organization index, not a wind-speed or intensity forecast. Warm water, low vertical shear and sufficient Coriolis rotation favor organization; moisture, ocean heat depth and many other real factors are omitted. Rotation reverses across the equator.",run:true,controls:[r("temperature","Sea-surface temperature",22,32,.5,27,"°C"),r("shear","Vertical wind shear",0,35,1,15,"m/s"),r("latitude","Latitude",-35,35,1,20,"°")],source:["NOAA: hurricane formation","https://oceanservice.noaa.gov/facts/how-hurricanes-form.html"]},
 {slug:"weather-front-simulator",tag:"FORECAST STUDIO",mission:"Create a rain-producing cold front and a rain-producing warm front. Record both.",hint:"Use warm air 25°C, cold air 5°C, and relative humidity 85%. Run each front type.",science:"Parcel teaching model: cloud base ≈ 125(T − Td) meters; dew point ≈ T − (100 − RH)/5. A cold front lifts the parcel 3 km and a warm front 1.5 km here. Cloud depth indicates precipitation potential, not a rainfall forecast.",run:true,controls:[s("front","Advancing air mass",["Cold front","Warm front"]),r("warm","Warm air temperature",15,35,1,25,"°C"),r("cold","Cold air temperature",-5,14,1,8,"°C"),r("humidity","Warm air relative humidity",20,100,5,50,"%") ]},
 {slug:"river-erosion",tag:"RIVER ENGINEER",mission:"Transport sand while keeping gravel on the bed: bed shear must be between 0.4 and 4 Pa.",hint:"Bed shear τ = ρghS. Try depth 0.5 m and slope 0.03%. Run the stream and inspect the sediment.",science:"Uniform wide-channel model: velocity follows Manning's equation with roughness 0.035; bed shear τ = ρghS. Fixed entrainment thresholds (sand 0.4 Pa, gravel 4 Pa) are illustrative. The changing riverbed is qualitative, not a calibrated erosion-rate prediction.",run:true,controls:[r("depth","Flow depth",.2,3,.1,1,"m"),r("slope","Channel slope",.01,.2,.01,.08,"%"),r("width","Channel width",5,40,1,15,"m")]},
 {slug:"rock-cycle-challenge",tag:"ROCK QUEST",mission:"Start as magma, visit all three rock families, and finish as igneous rock.",hint:"Cool → weather → compact → heat & pressure → melt → cool. Heat & pressure does not melt the rock.",science:"A state-transition model of valid rock transformations. Rock cycles have many paths, not a required universal sequence; the mission chooses one tour. Geologic durations are not represented.",controls:[]},
 {slug:"water-cycle-adventure",tag:"DROPLET ODYSSEY",mission:"Travel from ocean through vapor, cloud, land, groundwater and a river, then return to the ocean.",hint:"Evaporate → condense → precipitate → infiltrate → groundwater discharge → river outflow.",science:"Follow one water parcel through connected reservoirs. Choices represent processes, not literal pipes or equal residence times. Alternative routes include ice and plants; the mission highlights a groundwater route.",controls:[],source:["USGS: hydrologic cycle","https://www.usgs.gov/centers/new-york-water-science-center/science/hydrologic-cycle"]},
 {slug:"ocean-currents-3d",tag:"DENSITY DRIVER",mission:"Make the polar water sink, then add enough freshwater to reverse the density contrast. Record both circulations.",hint:"Warm side: 22°C and salinity 35. Polar side: 2°C and 35 to sink; change polar salinity to 27 to reverse.",science:"Two-box density model: ρ = 1027 − 0.2(T − 10) + 0.8(S − 35) kg/m³. Flow direction follows the density difference; animation speed is rescaled. This local illustrative circulation omits wind, mixing, pressure effects and geography and is not a forecast of global circulation.",run:true,controls:[r("warm","Warm-side temperature",10,30,1,22,"°C"),r("salty","Warm-side salinity",30,38,.5,35,"g/kg"),r("cold","Polar-side temperature",0,15,1,2,"°C"),r("fresh","Polar-side salinity",25,38,.5,35,"g/kg")],source:["NOAA: thermohaline circulation","https://oceanservice.noaa.gov/education/tutorial_currents/05conveyor1.html"]},
];
export const initialValues=(a:Activity):Values=>Object.fromEntries(a.controls.map(c=>[c.key,c.initial]));
export const clamp=(n:number,a=0,b=1)=>Math.max(a,Math.min(b,n));
export const arrivals=(distance:number)=>({p:distance/6,s:distance/3.5,gap:distance*(1/3.5-1/6)});
export const distanceFromGap=(gap:number)=>gap/(1/3.5-1/6);
export function plate(v:Values){const distance=v.speed*v.years*10,a=v.heading*Math.PI/180;return{distance,x:distance*Math.cos(a),y:distance*Math.sin(a)};}
export function volcano(v:Values){const index=clamp(v.gas/8*(v.viscosity-1)/6);return{index,style:index>.5?"Explosive":index<.2?"Effusive":"Mixed",viscosity:10**v.viscosity};}
export const events=[{x:350,y:220},{x:205,y:115},{x:430,y:140}];
export const stations=[{name:"ALPHA",x:100,y:70,color:"#8cb5f9"},{name:"BRAVO",x:500,y:80,color:"#e5b783"},{name:"CHARLIE",x:270,y:300,color:"#c5b5ec"}];
export const stationData=(event:number)=>stations.map(s=>({...s,...arrivals(Math.hypot(s.x-events[event].x,s.y-events[event].y)),distance:Math.hypot(s.x-events[event].x,s.y-events[event].y)}));
export function tsunami(v:Values){const speed=Math.sqrt(9.81*v.depth);return{speed,minutes:v.distance*1000/speed/60,coastal:v.uplift*(v.depth/20)**.25};}
export function hurricane(v:Values){const heat=clamp((v.temperature-26)/4),rotation=clamp(Math.abs(v.latitude)/10),shear=clamp(1-v.shear/30),index=heat*rotation*shear;return{index,organized:index>=.5,spin:Math.sign(v.latitude),coriolis:2*7.2921e-5*Math.sin(v.latitude*Math.PI/180)};}
export function front(v:Values){const dew=v.warm-(100-v.humidity)/5,base=125*(v.warm-dew),lift=v.front===0?3000:1500,cloud=Math.max(0,lift-base);return{dew,base,lift,cloud,rain:cloud>=800&&v.warm-v.cold>=10};}
export function river(v:Values){const slope=v.slope/100,velocity=v.depth**(2/3)*Math.sqrt(slope)/.035,shear=1000*9.81*v.depth*slope;return{velocity,shear,flow:velocity*v.depth*v.width,sand:shear>=.4,gravel:shear>=4};}
export const density=(temperature:number,salinity:number)=>1027-.2*(temperature-10)+.8*(salinity-35);
export function ocean(v:Values){const warm=density(v.warm,v.salty),polar=density(v.cold,v.fresh);return{warm,polar,delta:polar-warm};}
export type Journey={state:string;visited:string[];moves:number};
export const rockNodes=["Magma","Igneous","Sediment","Sedimentary","Metamorphic"];
export const waterNodes=["Ocean","Vapor","Cloud","Land","Groundwater","River","Plant","Ice"];
export const rockEdges:Record<string,Record<string,string>>={Magma:{Cool:"Igneous"},Igneous:{Weather:"Sediment","Heat & pressure":"Metamorphic",Melt:"Magma"},Sediment:{"Compact & cement":"Sedimentary"},Sedimentary:{Weather:"Sediment","Heat & pressure":"Metamorphic",Melt:"Magma"},Metamorphic:{Weather:"Sediment",Melt:"Magma"}};
export const waterEdges:Record<string,Record<string,string>>={Ocean:{Evaporate:"Vapor"},Vapor:{Condense:"Cloud"},Cloud:{Precipitate:"Land",Snow:"Ice"},Land:{Infiltrate:"Groundwater",Runoff:"River","Plant uptake":"Plant",Evaporate:"Vapor"},Groundwater:{"Groundwater discharge":"River","Plant uptake":"Plant"},River:{"River outflow":"Ocean",Evaporate:"Vapor"},Plant:{Transpire:"Vapor"},Ice:{Melt:"Land",Sublimate:"Vapor"}};
export const initialJourney=(water=false):Journey=>({state:water?"Ocean":"Magma",visited:[water?"Ocean":"Magma"],moves:0});
export function travel(j:Journey,action:string,water=false):Journey{const next=(water?waterEdges:rockEdges)[j.state]?.[action];return next?{state:next,visited:[...new Set([...j.visited,next])],moves:j.moves+1}:j;}
export function mission(slug:string,v:Values,ran:boolean,j:Journey){let ok=false,step="done",required=1,text="Run your experiment before recording the result.";switch(slug){
 case"seismic-wave-lab":ok=ran&&Math.abs(v.distance-v.estimate)<=10;text=ok?"Arrival-time evidence matches your distance estimate.":"Finish the recording, then convert the S–P gap into distance. Target tolerance: 10 km.";break;
 case"plate-motion-lab":{const p=plate(v);ok=ran&&Math.abs(p.x-500)<=20&&Math.abs(p.y)<20;text=`East ${p.x.toFixed(0)} km · north ${p.y.toFixed(0)} km. Target 500 km east with less than 20 km northward motion.`;break;}
 case"volcano-eruption-3d":{const e=volcano(v);ok=ran&&e.style!=="Mixed";step=e.style;required=2;text=`${e.style} behavior. Record both low-retention lava flow and high-retention explosive activity.`;break;}
 case"earthquake-epicenter-finder":{const error=Math.hypot(v.x-events[v.event].x,v.y-events[v.event].y);ok=error<=12;step=String(v.event);required=3;text=ok?`Located within ${error.toFixed(1)} km. Switch to the next event.`:"The marker does not match all three station distances yet. Look for their common ring intersection.";break;}
 case"plate-tectonics-3d":ok=ran&&v.landform===v.boundary+1;step=String(v.boundary);required=3;text=ok?"Boundary and landform match. Try the next boundary.":"Run the boundary and match the motion to its landform.";break;
 case"tsunami-3d":ok=ran&&Math.abs(v.estimate-tsunami(v).minutes)<=2;text=ok?"Your travel-time estimate matches the long-wave calculation.":"Finish the wave run and estimate distance ÷ speed. Check seconds versus minutes.";break;
 case"hurricane-simulator":{const h=hurricane(v);ok=ran&&(h.index>=.5||h.index<=.1);step=h.organized?"organized":"disrupted";required=2;text=`Organization index ${(h.index*100).toFixed(0)}/100. Record ≥50 and ≤10 to compare favorable and hostile conditions.`;break;}
 case"weather-front-simulator":ok=ran&&front(v).rain;step=String(v.front);required=2;text=ok?"Moist air lifted enough for precipitation potential. Repeat with the other front.":"Increase humidity and temperature contrast, then run the front.";break;
 case"river-erosion":{const r=river(v);ok=ran&&r.sand&&!r.gravel;text=`Bed shear ${r.shear.toFixed(2)} Pa. Target 0.4 ≤ τ < 4 Pa to move sand but leave gravel.`;break;}
 case"rock-cycle-challenge":ok=j.state==="Igneous"&&["Igneous","Sedimentary","Metamorphic"].every(n=>j.visited.includes(n));text=ok?"All three rock families visited. You returned to igneous rock.":"Visit igneous, sedimentary and metamorphic rock, then return to igneous.";break;
 case"water-cycle-adventure":ok=j.state==="Ocean"&&["Vapor","Cloud","Land","Groundwater","River"].every(n=>j.visited.includes(n));text=ok?"Your droplet completed its atmosphere–groundwater–ocean journey.":"Visit the atmosphere, land, groundwater and river, then return to ocean.";break;
 case"ocean-currents-3d":{const d=ocean(v).delta;ok=ran&&Math.abs(d)>.5;step=d>0?"polar sinks":"warm side sinks";required=2;text=`Polar minus warm density: ${d.toFixed(2)} kg/m³. Record contrasts above +0.5 and below −0.5.`;break;}
 }return{ok,step,required,text};}
