export type Values=Record<string,number>;
export type Control={key:string;label:string;min:number;max:number;step:number;initial:number;unit?:string;options?:string[]};
export type Activity={slug:string;tag:string;mission:string;hint:string;science:string;controls:Control[];run?:boolean;source?:[string,string]};
const r=(key:string,label:string,min:number,max:number,step:number,initial:number,unit=""):Control=>({key,label,min,max,step,initial,unit});
const s=(key:string,label:string,options:string[],initial=0):Control=>({key,label,min:0,max:options.length-1,step:1,initial,options});
export const organelles=[
 {name:"Nucleus",function:"Stores DNA",color:0x9c8bd5},{name:"Mitochondrion",function:"Releases usable energy",color:0xe29878},{name:"Golgi apparatus",function:"Modifies and sorts proteins",color:0xe5bc78},
 {name:"Ribosome",function:"Builds proteins",color:0x88afd9},{name:"Lysosome",function:"Digests and recycles materials",color:0xc286a7},{name:"Cell membrane",function:"Controls entry and exit",color:0x79a7cf},
];
export const activities:Activity[]=[
 {slug:"population-growth",tag:"POPULATION PLANNER",mission:"Grow a population from below 100 to at least 90% of carrying capacity without exceeding it.",hint:"Start near 50, choose K = 500 and growth rate around 0.35. Run all 20 generations.",science:"Logistic model dN/dt = rN(1 − N/K), with constant intrinsic rate r and carrying capacity K. It demonstrates density dependence, not a forecast: age structure, migration, delays and changing resources are omitted.",run:true,controls:[r("initial","Starting population",10,300,10,50),r("rate","Intrinsic growth rate",.05,.8,.05,.35,"/ generation"),r("capacity","Carrying capacity",200,1000,50,500)],source:["OpenStax: limits to population growth","https://openstax.org/books/biology-2e/pages/45-3-environmental-limits-to-population-growth"]},
 {slug:"predator-prey",tag:"ECOSYSTEM BALANCER",mission:"Create a persistent predator–prey cycle: both populations must survive and visibly fluctuate through 60 years.",hint:"The starting settings form a cycle. If one population collapses, reduce attack rate or predator mortality.",science:"A predator–prey model with logistic prey growth: dR/dt = rR(1−R/K)−aRP and dP/dt = eaRP−mP. Parameters remain fixed and species have no age or spatial structure; this is a teaching model, not an ecosystem forecast.",run:true,controls:[r("prey","Starting prey",100,800,25,400),r("predator","Starting predators",10,200,5,40),r("growth","Prey growth",.2,.8,.05,.5,"/ year"),r("attack","Attack coefficient",.0005,.004,.0001,.002),r("mortality","Predator mortality",.05,.4,.01,.15,"/ year")]},
 {slug:"animal-cell-3d",tag:"ORGANELLE SCANNER",mission:"Identify all six cell structures by matching each selected structure to its function.",hint:"Nucleus stores DNA; mitochondria release usable energy; Golgi modifies and sorts; ribosomes build proteins; lysosomes recycle; membrane controls transport.",science:"The model separates organelles and exaggerates their sizes so they can be inspected. Real animal cells vary in shape and organelle number, and structures are crowded and dynamic.",controls:[s("organelle","Structure",organelles.map(o=>o.name)),s("function","Match its function",["Choose a function",...organelles.map(o=>o.function)])]},
 {slug:"cell-membrane-transport",tag:"MEMBRANE GATEKEEPER",mission:"Demonstrate simple diffusion, facilitated diffusion, and ATP-powered active transport. Record all three.",hint:"Oxygen crosses directly from high to low. Glucose needs an open carrier. For active transport, use sodium, a pump, ATP, and move from low concentration toward high concentration.",science:"Passive flux follows a concentration gradient; facilitated transport also requires a compatible open protein. The active-pump case moves against the selected gradient only when ATP is available. Rates are dimensionless and omit charge and membrane voltage.",run:true,controls:[s("molecule","Molecule",["Oxygen","Glucose","Sodium","Water"]),s("transport","Transport route",["Through lipid bilayer","Channel / carrier","ATP pump"]),r("outside","Outside concentration",0,100,5,80),r("inside","Inside concentration",0,100,5,20),s("direction","Desired movement",["Into cell","Out of cell"]),s("open","Protein gate",["Closed","Open"],1),s("atp","ATP available",["No ATP","ATP ready"],1)] ,source:["NCBI: principles of membrane transport","https://www.ncbi.nlm.nih.gov/books/NBK26815/"]},
 {slug:"mitosis-challenge",tag:"DIVISION DIRECTOR",mission:"Guide one parent cell through every cell-cycle stage in the correct order to form two identical daughter cells.",hint:"Interphase → prophase → metaphase → anaphase → telophase → cytokinesis.",science:"A stage-sequence model emphasizes major chromosome events. Cell-cycle checkpoints and the continuous overlap between many molecular events are simplified.",controls:[]},
 {slug:"dna-replication",tag:"REPLICATION CREW",mission:"Build the complete complementary strand for 5′-ATGCCGTA-3′ with zero mismatches.",hint:"DNA pairing rules are A–T and C–G. Build one base at a time beneath the template.",science:"Complementary base pairing models one product strand. Cellular replication is semiconservative and polymerases extend DNA 5′→3′; helicase, primers, leading/lagging strands and proofreading are not dynamically modeled here.",controls:[],source:["Genome.gov: DNA and protein synthesis","https://www.genome.gov/Pages/Education/Modules/BluePrintToYou/Blueprint6.pdf"]},
 {slug:"protein-synthesis",tag:"GENE EXPRESS",mission:"Transcribe the DNA template into mRNA, then translate its codons into the correct peptide.",hint:"Template DNA TAC CGA TTT ACT gives mRNA AUG GCU AAA UGA. Translate: Met · Ala · Lys · Stop.",science:"The DNA template is transcribed by complementary RNA pairing (A–U, T–A, C–G, G–C), then the ribosome reads mRNA codons. The short exercise omits RNA processing and uses one unambiguous coding segment.",controls:[],source:["Genome.gov: DNA and protein synthesis","https://www.genome.gov/Pages/Education/Modules/BluePrintToYou/Blueprint6.pdf"]},
 {slug:"human-heart-3d",tag:"CIRCULATION PILOT",mission:"Route one blood cell through every chamber, valve, lungs and body, then return to the right atrium.",hint:"Body → vena cava → right atrium → tricuspid → right ventricle → pulmonary valve → lungs → pulmonary vein → left atrium → mitral → left ventricle → aortic valve → body.",science:"A one-way route model of pulmonary and systemic circulation. Oxygen level changes at lungs and body; pressures and detailed vessel branching are omitted. Valves are represented as checkpoints that prevent backflow.",controls:[],source:["NIH: how blood flows through the heart","https://www.nhlbi.nih.gov/health/heart/blood-flow"]},
 {slug:"natural-selection",tag:"EVOLUTION WATCH",mission:"Make the dark trait exceed 80%, then change selection so it falls below 20%. Record both outcomes.",hint:"Start at 50%. Set dark fitness above light fitness, run 20 generations, then reverse the two fitness values.",science:"Deterministic viability selection for two inherited variants: p′ = pwD/[pwD+(1−p)wL]. It shows differential reproductive success, not individuals changing traits. Mutation, migration, drift, dominance and population size are omitted.",run:true,controls:[r("dark","Initial dark trait",5,95,5,50,"%"),r("darkFitness","Dark fitness",.5,1.5,.05,1.25),r("lightFitness","Light fitness",.5,1.5,.05,.75)]},
 {slug:"food-web-builder",tag:"WEB ARCHITECT",mission:"Build all seven valid energy pathways, remove the grasshopper, and predict which population declines first.",hint:"Energy arrows point food → consumer. Grass and algae are producers. The frog depends directly on the grasshopper.",science:"A topology game showing the direction of energy transfer. The removal response follows direct feeding dependencies; it is not a quantitative population forecast. Omnivory, diet switching, decomposition and interaction strength are omitted.",controls:[s("removed","Removal experiment",["No removal","Remove grasshopper"]),s("prediction","Prediction",["Choose an outcome","Frog declines","Rabbit declines","Fish increase"])]},
 {slug:"photosynthesis-lab",tag:"LEAF OPTIMIZER",mission:"Reach at least 80% relative photosynthesis while using no more than 70% light and 600 ppm CO₂.",hint:"Try 70% light, 600 ppm CO₂, and 25°C. Each factor can limit the total rate.",science:"Relative rate multiplies saturating light and CO₂ responses by a bell-shaped temperature response centered at 25°C, then normalizes to the control range. It is not a species-specific biochemical model; water and nutrients are omitted.",run:true,controls:[r("light","Light intensity",0,100,5,50,"%"),r("co2","Carbon dioxide",0,1000,50,400,"ppm"),r("temperature","Leaf temperature",0,50,1,20,"°C")],source:["OpenStax: overview of photosynthesis","https://openstax.org/books/biology-2e/pages/8-1-overview-of-photosynthesis"]},
 {slug:"immune-system-defense",tag:"IMMUNE COMMAND",mission:"Clear a primary infection, create memory, then defeat the second exposure while keeping tissue health above 80%.",hint:"Activate B cells early, then use an antibody strike. Rechallenge after the first infection clears; memory makes the second response stronger.",science:"Turn-based strategy model. Innate cells act quickly, B-cell activation creates antibodies and memory, and memory accelerates a second response. Counts and damage are game units—not clinical values—and many immune cells and signaling pathways are omitted.",controls:[]},
];
export const initialValues=(a:Activity):Values=>Object.fromEntries(a.controls.map(c=>[c.key,c.initial]));
export const clamp=(n:number,a=0,b=1)=>Math.max(a,Math.min(b,n));
export const logistic=(v:Values,t:number)=>v.capacity/(1+((v.capacity-v.initial)/v.initial)*Math.exp(-v.rate*t));
export type SeriesPoint={t:number;a:number;b?:number};
export function predatorPrey(v:Values,years=60){let prey=v.prey,predator=v.predator;const points:SeriesPoint[]=[{t:0,a:prey,b:predator}],dt=.02;for(let i=1;i<=years/dt;i++){const dp=v.growth*prey*(1-prey/1000)-v.attack*prey*predator,dq=.15*v.attack*prey*predator-v.mortality*predator;prey=Math.max(0,prey+dp*dt);predator=Math.max(0,predator+dq*dt);if(i%50===0)points.push({t:i*dt,a:prey,b:predator});}return points;}
export function transport(v:Values){const names=["Oxygen","Glucose","Sodium","Water"],down=v.outside>v.inside?0:1,gradient=Math.abs(v.outside-v.inside),desired=v.direction;let valid=false,kind="Blocked",rate=0;if(v.transport===0&&[0,3].includes(v.molecule)&&desired===down){valid=true;kind=v.molecule===3?"Osmosis":"Simple diffusion";rate=gradient*.08;}else if(v.transport===1&&v.open===1&&desired===down){valid=true;kind="Facilitated diffusion";rate=gradient*.16;}else if(v.transport===2&&v.atp===1&&v.molecule===2&&desired!==down){valid=true;kind="Active transport";rate=Math.max(1,gradient*.1);}return{valid,kind,rate,direction:desired===0?"into cell":"out of cell",molecule:names[v.molecule],downhill:desired===down};}
export const stages=["Interphase","Prophase","Metaphase","Anaphase","Telophase","Cytokinesis","Daughter cells"];
export type SequenceState={index:number;mistakes:number};
export const sequenceMove=(state:SequenceState,choice:number)=>choice===state.index+1?{...state,index:choice}:{...state,mistakes:state.mistakes+1};
export const dnaTemplate="ATGCCGTA",dnaComplement="TACGGCAT",rnaTarget="AUGGCUAAAUGA",proteinTarget=["Met","Ala","Lys","Stop"];
export const dnaPair=(base:string)=>({A:"T",T:"A",C:"G",G:"C"})[base as "A"];
export const rnaPair=(base:string)=>({A:"U",T:"A",C:"G",G:"C"})[base as "A"];
export const codons:Record<string,string>={AUG:"Met",GCU:"Ala",AAA:"Lys",UGA:"Stop"};
export const heartRoute=["Body","Vena cava","Right atrium","Tricuspid valve","Right ventricle","Pulmonary valve","Lungs","Pulmonary vein","Left atrium","Mitral valve","Left ventricle","Aortic valve","Body"];
export function selection(v:Values,generations=20){let p=v.dark/100;const points:SeriesPoint[]=[{t:0,a:p*100,b:(1-p)*100}];for(let g=1;g<=generations;g++){p=p*v.darkFitness/(p*v.darkFitness+(1-p)*v.lightFitness);points.push({t:g,a:p*100,b:(1-p)*100});}return points;}
export const foodNodes=["Grass","Algae","Grasshopper","Rabbit","Frog","Fish","Hawk"];
export const validFoodEdges=["Grass→Grasshopper","Grass→Rabbit","Grasshopper→Frog","Algae→Fish","Rabbit→Hawk","Frog→Hawk","Fish→Hawk"];
export const foodChoices=[...validFoodEdges,"Rabbit→Grass","Hawk→Rabbit","Frog→Grasshopper","Fish→Algae","Grass→Hawk"];
export const photosynthesis=(v:Values)=>clamp((v.light/(v.light+20)/(.833333))*(v.co2/(v.co2+200)/(.833333))*Math.exp(-(((v.temperature-25)/12)**2)))*100;
export type ImmuneState={pathogens:number;tissue:number;energy:number;antibodies:number;memory:number;turn:number;exposure:1|2;cleared:boolean;won:boolean};
export const initialImmune=():ImmuneState=>({pathogens:30,tissue:100,energy:8,antibodies:0,memory:0,turn:0,exposure:1,cleared:false,won:false});
export type ImmuneAction="Innate cells"|"Activate B cells"|"Antibody strike"|"Rest";
export function immuneTurn(s:ImmuneState,action:ImmuneAction):ImmuneState{if(s.cleared||s.won||s.tissue<=0)return s;const cost=action==="Rest"?0:action==="Activate B cells"?3:2;if(s.energy<cost)return s;let pathogens=s.pathogens,antibodies=s.antibodies,memory=s.memory,energy=Math.min(10,s.energy-cost+1);if(s.exposure===2&&s.memory>0){antibodies=Math.max(antibodies,18);pathogens=Math.max(0,pathogens-8);}if(action==="Innate cells")pathogens=Math.max(0,pathogens-10);if(action==="Activate B cells"){antibodies+=15;memory=1;}if(action==="Antibody strike")pathogens=Math.max(0,pathogens-(antibodies>0?20:2));if(action==="Rest")energy=Math.min(10,energy+3);if(pathogens>0)pathogens=Math.min(100,pathogens*1.18);const tissue=Math.max(0,s.tissue-pathogens*.12),cleared=pathogens<=0;return{pathogens,tissue,energy,antibodies,memory,turn:s.turn+1,exposure:s.exposure,cleared,won:cleared&&s.exposure===2};}
export function rechallenge(s:ImmuneState):ImmuneState{return s.cleared&&s.exposure===1&&s.memory>0?{...s,pathogens:30,antibodies:0,exposure:2,cleared:false}:s;}
export function mission(slug:string,v:Values,ran:boolean,extra:{steps?:string[];sequence?:SequenceState;dna?:string;rna?:string;protein?:string[];heart?:number;edges?:string[];immune?:ImmuneState}={}){let ok=false,step="done",required=1,text="Complete the investigation, then record your evidence.";switch(slug){
 case"population-growth":{const n=logistic(v,20);ok=ran&&v.initial<100&&n>=.9*v.capacity&&n<=v.capacity&&n>=2*v.initial;text=`Generation 20: ${n.toFixed(0)} organisms; carrying capacity ${v.capacity}. Target 90–100% of K.`;break;}
 case"predator-prey":{const p=predatorPrey(v),prey=p.map(x=>x.a),pred=p.map(x=>x.b!);ok=ran&&Math.min(...prey)>10&&Math.min(...pred)>5&&Math.max(...prey)-Math.min(...prey)>100&&Math.max(...pred)-Math.min(...pred)>20;text=ok?"Both species survived and fluctuated: a persistent feedback cycle.":"One population collapsed or the populations did not cycle clearly. Rebalance growth, attack and mortality.";break;}
 case"animal-cell-3d":ok=v.function===v.organelle+1;step=String(v.organelle);required=6;text=ok?`${organelles[v.organelle].name}: ${organelles[v.organelle].function}.`:"Inspect the highlighted structure and choose its biological role.";break;
 case"cell-membrane-transport":{const m=transport(v);ok=ran&&m.valid;step=m.kind;required=3;text=ok?`${m.molecule} moved ${m.direction} by ${m.kind}.`:"This route cannot move that molecule in the selected direction under these conditions.";break;}
 case"mitosis-challenge":ok=extra.sequence?.index===6;text=ok?`Two daughter cells formed with ${extra.sequence?.mistakes||0} sequencing errors.`:"Continue the stages until cytokinesis forms two daughter cells.";break;
 case"dna-replication":ok=extra.dna===dnaComplement;text=ok?"Complement complete: every A–T and C–G pair matches.":"The complementary strand is incomplete or has a mismatch.";break;
 case"protein-synthesis":ok=extra.rna===rnaTarget&&extra.protein?.join("-")===proteinTarget.join("-");text=ok?"Gene expressed: AUG–GCU–AAA–UGA → Met–Ala–Lys–Stop.":extra.rna!==rnaTarget?"Complete the complementary mRNA first.":"Translate each mRNA codon in order.";break;
 case"human-heart-3d":ok=extra.heart===heartRoute.length-1;text=ok?"One complete pulmonary and systemic circuit traced with one-way valves.":"Keep routing the blood cell through the next correct chamber, valve or organ.";break;
 case"natural-selection":{const end=selection(v).at(-1)!.a;ok=ran&&(end>80||end<20);step=end>80?"dark rises":"dark falls";required=2;text=`Dark trait after 20 generations: ${end.toFixed(1)}%. Record one rise above 80% and one fall below 20%.`;break;}
 case"food-web-builder":{const chosen=new Set(extra.edges||[]);ok=validFoodEdges.every(e=>chosen.has(e))&&chosen.size===validFoodEdges.length&&v.removed===1&&v.prediction===1;text=ok?"Stable web built. Removing grasshopper removes the frog's direct food source.":"Connect every valid food → consumer pathway without reversed or unsupported links, then run the removal prediction.";break;}
 case"photosynthesis-lab":{const rate=photosynthesis(v);ok=ran&&rate>=80&&v.light<=70&&v.co2<=600;text=`Relative rate ${rate.toFixed(1)}%. Target ≥80% with light ≤70% and CO₂ ≤600 ppm.`;break;}
 case"immune-system-defense":ok=!!extra.immune?.won&&extra.immune.tissue>80&&extra.immune.memory>0;text=ok?`Both exposures cleared with ${extra.immune!.tissue.toFixed(0)}% tissue health and immune memory.`:"Create memory, clear the primary infection, then rechallenge and keep tissue health above 80%.";break;
 }return{ok,step,required,text};}
