"use client";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import type { SubjectDefinition, SimulationCard } from "@/lib/subjects/catalog";
import { activities, derivative, initialValues, lineTargets, matrix, mission, probability, quadratic, quadraticTargets, riemann, sliceShape, triangles, vector, type Values } from "@/lib/simulations/mathematicsLabs/model";
import { MathSliceScene } from "./MathSliceScene";
import { MathDisplay } from "./MathDisplay";
import styles from "../chemistry/chemistry.module.css";
import math from "./mathematics.module.css";

const STORE="learnerkits-mathematics-missions-v1";
type Journal={completed:string[];observations:Record<string,string[]>};
const emptyJournal=():Journal=>({completed:[],observations:{}});
function loadJournal():Journal{try{const p=JSON.parse(localStorage.getItem(STORE)||"{}");const observations=Object.fromEntries(Object.entries(p.observations||{}).filter((entry):entry is [string,string[]]=>{const [key,value]=entry;return activities.some(a=>a.slug===key)&&Array.isArray(value)&&value.every(v=>typeof v==="string");}));return{completed:Array.isArray(p.completed)?p.completed.filter((v:unknown)=>typeof v==="string"&&activities.some(a=>a.slug===v)):[],observations};}catch{return emptyJournal();}}
const fmt=(n:number,d=2)=>Number.isFinite(n)?n.toFixed(d):"—";
function metrics(slug:string,v:Values,time:number):[string,string][]{switch(slug){
 case"vector-lab":{const q=vector(v);return[["Resultant",`⟨${q.x}, ${q.y}⟩`],["Magnitude",fmt(q.magnitude)],["Direction",`${fmt(q.angle,1)}°`]];}
 case"function-explorer":{const q=quadratic(v);return[["Discriminant",fmt(q.disc)],["Vertex",Number.isFinite(q.vertexX)?`(${fmt(q.vertexX)}, ${fmt(q.vertexY)})`:"Not quadratic"],["Roots",q.roots.length?q.roots.map(x=>fmt(x)).join(", "):"No two real roots"]];}
 case"geometry-slice-3d":return[["Solid",["Cylinder","Cube","Cone","Sphere"][v.solid]],["Plane",["Horizontal","Vertical"][v.plane]],["Cross-section",sliceShape(v)]];
 case"pythagorean-puzzle":{const q=triangles[v.puzzle];return[["Leg a",String(q[0])],["Leg b",String(q[1])],["a² + b²",String(q[0]**2+q[1]**2)]];}
 case"unit-circle-challenge":{const a=v.angle*Math.PI/180;return[["Radians",`${fmt(a/Math.PI,2)}π`],["cos θ",fmt(Math.cos(a),3)],["sin θ",fmt(Math.sin(a),3)]];}
 case"quadratic-transformation":{const q=quadraticTargets[v.target];return[["Target vertex",`(${q.h}, ${q.k})`],["Your vertex",`(${v.h}, ${v.k})`],["Target scale",String(q.a)]];}
 case"slope-intercept-challenge":{const q=lineTargets[v.target];return[["Target slope",String(q.m)],["Target intercept",String(q.b)],["Your equation",`y = ${v.m}x ${v.b<0?"−":"+"} ${Math.abs(v.b)}`]];}
 case"geometry-transformation":return[["Challenge",["Translation","Rotation","Reflection","Dilation"][v.challenge]],["Invariant",["Lengths & angles","Lengths & angles","Lengths & angles","Angles"][v.challenge]],["Area scale",v.challenge===3?fmt(v.scale**2):"1.00"]];
 case"probability-experiment":{const p=probability({...v,trials:Math.max(1,Math.floor(v.trials*time/10))});return[["Trials complete",fmt(v.trials*time/10,0)],["Experimental",`${fmt(p.experimental*100,1)}%`],["Theoretical",`${fmt(p.theory*100,1)}%`]];}
 case"derivative-tangent":return[["Point x",fmt(v.x,1)],["Exact derivative",fmt(derivative(v.function,v.x),3)],["Your slope",fmt(v.guess,2)]];
 case"area-under-curve":{const q=riemann(v);return[["Riemann sum",fmt(q.sum,4)],["Exact integral",fmt(q.exact,4)],["Absolute error",fmt(q.error,4)]];}
 default:return[["Determinant",fmt(matrix(v).det)],["Basis i image",`⟨${v.a}, ${v.c}⟩`],["Basis j image",`⟨${v.b}, ${v.d}⟩`]];
}}

export function MathematicsActivitiesClient({locale,subject,simulation}:{locale:string;subject:SubjectDefinition;simulation:SimulationCard}){
 const activity=activities.find(a=>a.slug===simulation.slug)!,slug=activity.slug;const [values,setValues]=useState(()=>initialValues(activity)),[time,setTime]=useState(0),[running,setRunning]=useState(false),[speed,setSpeed]=useState(1),[journal,setJournal]=useState<Journal>(emptyJournal),[feedback,setFeedback]=useState<{ok:boolean;text:string}|null>(null),[hint,setHint]=useState(false),[saved,setSaved]=useState(true);const live=useRef({running,speed});live.current={running,speed};
 useEffect(()=>setJournal(loadJournal()),[]);useEffect(()=>{let last=performance.now();const timer=window.setInterval(()=>{const now=performance.now(),dt=Math.min(.1,(now-last)/1000);last=now;if(live.current.running&&!document.hidden)setTime(t=>Math.min(10,t+dt*live.current.speed));},50);return()=>clearInterval(timer);},[]);useEffect(()=>{if(time>=10)setRunning(false);},[time]);
 function update(key:string,value:number){setValues(v=>({...v,[key]:value}));setFeedback(null);if(activity.run){setTime(0);setRunning(false);}}
 function reset(){setValues(initialValues(activity));setTime(0);setRunning(false);setFeedback(null);}
 const result=mission(slug,values,time>=10),stamps=journal.observations[slug]||[],complete=journal.completed.includes(slug);
 function check(){const current=mission(slug,values,time>=10);if(!current.ok){setFeedback(current);return;}const stored=loadJournal(),steps=[...new Set([...(stored.observations[slug]||[]),...(journal.observations[slug]||[]),current.step])],done=steps.length>=current.required,next={completed:[...new Set([...stored.completed,...journal.completed,...(done?[slug]:[])])],observations:{...stored.observations,...journal.observations,[slug]:steps}};setJournal(next);try{localStorage.setItem(STORE,JSON.stringify(next));setSaved(true);}catch{setSaved(false);}setFeedback({ok:true,text:`${done?"Mission complete · mathematics badge earned!":`${steps.length}/${current.required} targets solved.`} ${current.text}`});}
 const number=activities.findIndex(a=>a.slug===slug)+1;
 return <main className={`${styles.page} ${math.page}`}><header className={styles.header}><div><Link className={styles.back} href={`/${locale}/subjects/mathematics`}>← Mathematics</Link><div className={styles.eyebrow}>MATHEMATICS MISSIONS / CHALLENGE {String(number).padStart(2,"0")}</div><h1>{simulation.title}</h1><p>{simulation.outcome}</p></div><div className={`${styles.notebook} ${math.badges}`}><span>YOUR MATH BADGES</span><strong>{journal.completed.length}<small> / 12</small></strong><span>{journal.completed.length>=9?"Master modeler":journal.completed.length>=5?"Pattern analyst":"Problem solver"}</span><div>{activities.map(a=><i key={a.slug} data-earned={journal.completed.includes(a.slug)}/>)}</div></div></header>
  <div className={math.ribbon}><strong>∑ {activity.tag}</strong><span>Manipulate. Predict. Prove it visually.</span><b>+1 MATH BADGE</b></div>
  <div className={styles.workspace}><section className={styles.scenePanel}><div className={styles.sceneTop}><span><i/>{slug==="geometry-slice-3d"?"INTERACTIVE 3D GEOMETRY":"LIVE MATHEMATICAL MODEL"}</span><span className={math.status}>{running?"● EXPERIMENT RUNNING":time>=10?"SAMPLE COMPLETE":"READY"}</span></div><div className={styles.stage}>{slug==="geometry-slice-3d"?<MathSliceScene values={values}/>:<MathDisplay slug={slug} values={values} time={time}/>}</div><div className={styles.metrics}>{metrics(slug,values,time).map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>
   {activity.run&&<div className={math.transport}><button onClick={()=>{if(time>=10)setTime(0);setRunning(r=>!r);}}>{running?"Ⅱ Pause":time>=10?"↻ Replay":"▶ Run trials"}</button><progress value={time} max="10" aria-label="Experiment progress"/><span>{fmt(time*10,0)}%</span><select value={speed} aria-label="Playback speed" onChange={e=>setSpeed(Number(e.target.value))}><option value="1">1×</option><option value="2">2×</option><option value=".5">½×</option></select></div>}
   {slug==="matrix-transformation"&&<div className={math.matrixReadout}><span>[ {values.a} {values.b} ]</span><span>[ {values.c} {values.d} ]</span><small>Columns are the transformed basis vectors · det = {fmt(matrix(values).det)}</small></div>}
   {slug==="area-under-curve"&&<div className={math.convergence}><span>Error meter</span><div><i style={{width:`${Math.min(100,riemann(values).error*100)}%`}}/></div><b>{riemann(values).error<=.03?"Converged":"Refine the partition"}</b></div>}
   <div className={math.caption}>The graph uses equal coordinate scale where geometry requires it. Values update directly from the displayed equations.</div>
  </section><aside className={styles.controlsPanel}><div className={styles.mission}><div className={styles.missionLabel}><span>YOUR MISSION</span><b>{complete?"✓ BADGE EARNED":"ACTIVE"}</b></div><h2>{activity.mission}</h2><div className={math.stamps}>{Array.from({length:result.required},(_,i)=><span key={i} data-filled={stamps.length>i}>{stamps.length>i?"✓":"◇"}</span>)}<small>{Math.min(stamps.length,result.required)} / {result.required}</small></div><button className={styles.hintButton} aria-expanded={hint} onClick={()=>setHint(h=>!h)}>{hint?"Close hint":"Need a hint?"}</button>{hint&&<p>{activity.hint}</p>}</div><div className={styles.controlTitle}><h2>Model controls</h2><button onClick={reset}>↺ Reset</button></div>
   <div className={styles.controls}>{activity.controls.map(c=><label key={c.key} className={styles.control}><span><b>{c.label}</b>{!c.options&&<output>{fmt(values[c.key],c.step<1?2:0)} {c.unit}</output>}</span>{c.options?<select value={values[c.key]} onChange={e=>update(c.key,Number(e.target.value))}>{c.options.map((option,i)=><option value={i} key={option}>{option}</option>)}</select>:<input type="range" min={c.min} max={c.max} step={c.step} value={values[c.key]} onChange={e=>update(c.key,Number(e.target.value))}/>}</label>)}</div>
   {activity.run&&<button className={styles.action} onClick={()=>{setTime(0);setRunning(true);setFeedback(null);}}>▶ Run a fresh experiment</button>}<button className={styles.checkButton} onClick={check}>Check solution <span>→</span></button><div className={styles.feedback} aria-live="polite">{feedback?<div data-success={feedback.ok}><strong>{feedback.ok?"✓ Solution recorded":"Not matched yet"}</strong><p>{feedback.text}</p></div>:<p>Change the parameters, use the visualization as evidence, then check your solution.</p>}</div>{!saved&&<p className={styles.saveWarning}>Progress is saved for this session only.</p>}<details className={styles.science}><summary>Why the mathematics works</summary><p>{activity.science}</p></details>
  </aside></div><section className={styles.library}><span className={styles.eyebrow}>CONTINUE YOUR MATH MISSIONS</span><h2>12 mathematical systems to master</h2><div className={styles.labLinks}>{subject.simulations.map((sim,i)=><Link key={sim.slug} href={`/${locale}/simulations/${sim.slug}`} aria-current={sim.slug===slug?"page":undefined}><span>{String(i+1).padStart(2,"0")}</span><strong>{sim.title}</strong><small>{journal.completed.includes(sim.slug)?"✓ Badge earned":"Open challenge ↗"}</small></Link>)}</div></section>
 </main>;
}
