"use client";
import { useId } from "react";
import { baseShape, derivative, functionValue, lineTargets, matrix, probability, quadraticTargets, riemann, sliceShape, transformShape, triangles, vector, type Values } from "@/lib/simulations/mathematicsLabs/model";

const blue="#9fc2fa",amber="#e8ba7d",pink="#df8da2",muted="#91a2ba";
const line=(points:[number,number][])=>points.map((p,i)=>`${i?"L":"M"}${p[0].toFixed(2)},${p[1].toFixed(2)}`).join(" ");
const polygon=(points:[number,number][])=>points.map(p=>p.join(",")).join(" ");
const gx=(x:number)=>325+x*25,gy=(y:number)=>220-y*25;
function grid(){return <>{Array.from({length:21},(_,i)=><path key={`v${i}`} d={`M${75+i*25} 35V405`} stroke={i===10?"#71829a":"#344257"} strokeWidth={i===10?1.5:1}/>)}{Array.from({length:15},(_,i)=><path key={`h${i}`} d={`M75 ${45+i*25}H575`} stroke={i===7?"#71829a":"#344257"} strokeWidth={i===7?1.5:1}/>)}</>}
export function MathDisplay({slug,values:v,time:t}:{slug:string;values:Values;time:number}){
 const id=useId().replaceAll(":","");let content:React.ReactNode;
 if(slug==="vector-lab"){
  const q=vector(v),origin:[number,number]=[325,220],a:[number,number]=[gx(v.ax),gy(v.ay)],end:[number,number]=[gx(q.x),gy(q.y)],corner:[number,number]=[gx(v.ax+v.bx),gy(v.ay+v.by)];
  content=<>{grid()}<path d={`M${origin}L${a}`} stroke={blue} strokeWidth="4" markerEnd={`url(#${id}blue)`}/><path d={`M${a}L${corner}`} stroke={amber} strokeWidth="4" markerEnd={`url(#${id}amber)`}/><path d={`M${origin}L${end}`} stroke="white" strokeWidth="3" strokeDasharray="7 5" markerEnd={`url(#${id}white)`}/><text x={a[0]+8} y={a[1]-8} fill={blue}>A</text><text x={corner[0]+8} y={corner[1]-8} fill={amber}>A + B</text><text x="90" y="390">R = ⟨{q.x}, {q.y}⟩ · |R| = {q.magnitude.toFixed(2)} · θ = {q.angle.toFixed(1)}°</text></>;
 }else if(slug==="function-explorer"){
  const fn=(x:number)=>v.a*x*x+v.b*x+v.c,points=Array.from({length:241},(_,i)=>{const x=-6+i*.05;return[gx(x),gy(fn(x))] as [number,number]}).filter(p=>p[1]>20&&p[1]<420);
  content=<>{grid()}<path d={line(points)} fill="none" stroke={blue} strokeWidth="4"/><circle cx={gx(0)} cy={gy(v.c)} r="6" fill={amber}/><text x="90" y="55" fill={blue}>f(x) = {v.a}x² {v.b<0?"−":"+"} {Math.abs(v.b)}x {v.c<0?"−":"+"} {Math.abs(v.c)}</text><text x="90" y="390">Gold point: y-intercept · roots occur where the curve crosses the x-axis</text></>;
 }else if(slug==="pythagorean-puzzle"){
  const [a,b,c]=triangles[v.puzzle],scale=15,A:[number,number]=[150,330],B:[number,number]=[150+a*scale,330],C:[number,number]=[150,330-b*scale];
  content=<>{<polygon points={polygon([A,B,C])} fill="#4b658b" fillOpacity=".55" stroke={blue} strokeWidth="4"/>}<path d={`M150 310H170V330`} fill="none" stroke={amber}/><text x={(A[0]+B[0])/2} y="360" textAnchor="middle" fill={amber}>{a}</text><text x="125" y={(A[1]+C[1])/2} fill={amber}>{b}</text><text x={(B[0]+C[0])/2+15} y={(B[1]+C[1])/2} fill="white">c = ?</text><g transform="translate(390 100)"><rect width="190" height="220" rx="18" fill="#252f3d" stroke="#4a5a70"/><text x="95" y="48" textAnchor="middle" fill={blue}>AREA EQUATION</text><text x="95" y="105" textAnchor="middle" fill="white" fontSize="25">{a}² + {b}² = c²</text><text x="95" y="158" textAnchor="middle">{a*a} + {b*b} = {c*c}</text><text x="95" y="200" textAnchor="middle" fill={amber}>Your c: {v.answer.toFixed(1)}</text></g></>;
 }else if(slug==="unit-circle-challenge"){
  const angle=v.angle*Math.PI/180,x=Math.cos(angle),y=Math.sin(angle),px=325+x*150,py=220-y*150;
  content=<>{grid()}<circle cx="325" cy="220" r="150" fill="#385272" fillOpacity=".2" stroke={blue} strokeWidth="3"/><path d={`M325 220L${px} ${py}`} stroke={amber} strokeWidth="4" markerEnd={`url(#${id}amber)`}/><path d={`M${px} ${py}V220M${px} ${py}H325`} stroke="#8193ad" strokeDasharray="5 6"/><circle cx={px} cy={py} r="8" fill={amber}/><path d={line(Array.from({length:31},(_,i)=>[325+45*Math.cos(i/30*angle),220-45*Math.sin(i/30*angle)] as [number,number]))} fill="none" stroke={pink} strokeWidth="3"/><text x="385" y="205" fill={pink}>{v.angle}°</text><text x="90" y="390">(cos θ, sin θ) = ({x.toFixed(3)}, {y.toFixed(3)})</text></>;
 }else if(slug==="quadratic-transformation"){
  const target=quadraticTargets[v.target],curve=(a:number,h:number,k:number)=>Array.from({length:241},(_,i)=>{const x=-6+i*.05;return[gx(x),gy(a*(x-h)**2+k)] as [number,number]}).filter(p=>p[1]>20&&p[1]<420);
  content=<>{grid()}<path d={line(curve(target.a,target.h,target.k))} fill="none" stroke={pink} strokeWidth="8" opacity=".45"/><path d={line(curve(v.a,v.h,v.k))} fill="none" stroke={blue} strokeWidth="3"/><circle cx={gx(target.h)} cy={gy(target.k)} r="8" fill={pink}/><circle cx={gx(v.h)} cy={gy(v.k)} r="5" fill={blue}/><text x="90" y="55" fill={pink}>TARGET</text><text x="165" y="55" fill={blue}>YOUR GRAPH</text><text x="90" y="390">y = {v.a}(x − {v.h})² {v.k<0?"−":"+"} {Math.abs(v.k)}</text></>;
 }else if(slug==="slope-intercept-challenge"){
  const target=lineTargets[v.target],segment=(m:number,b:number)=>[[-10,m*-10+b],[10,m*10+b]].map(([x,y])=>[gx(x),gy(y)] as [number,number]);
  content=<>{grid()}<path d={line(segment(target.m,target.b))} stroke={pink} strokeWidth="9" opacity=".4"/><path d={line(segment(v.m,v.b))} stroke={blue} strokeWidth="3"/><circle cx={gx(0)} cy={gy(target.b)} r="8" fill={pink}/><circle cx={gx(0)} cy={gy(v.b)} r="5" fill={blue}/><text x="90" y="55" fill={pink}>TARGET</text><text x="165" y="55" fill={blue}>YOUR LINE</text><text x="90" y="390">y = {v.m}x {v.b<0?"−":"+"} {Math.abs(v.b)}</text></>;
 }else if(slug==="geometry-transformation"){
  const current=transformShape(v),targets=[baseShape.map(([x,y])=>[x+4,y-2] as [number,number]),baseShape.map(([x,y])=>[-y,x] as [number,number]),baseShape.map(([x,y])=>[-x,y] as [number,number]),baseShape.map(([x,y])=>[2*x,2*y] as [number,number])][v.challenge];
  content=<>{grid()}<polygon points={polygon(baseShape.map(([x,y])=>[gx(x),gy(y)]))} fill="#718199" fillOpacity=".25" stroke="#8190a5" strokeDasharray="5 5"/><polygon points={polygon(targets.map(([x,y])=>[gx(x),gy(y)]))} fill={pink} fillOpacity=".28" stroke={pink} strokeWidth="8" opacity=".55"/><polygon points={polygon(current.map(([x,y])=>[gx(x),gy(y)]))} fill={blue} fillOpacity=".3" stroke={blue} strokeWidth="3"/><text x="90" y="55"><tspan fill="#8f9fb5">ORIGINAL</tspan><tspan x="190" fill={pink}>TARGET</tspan><tspan x="270" fill={blue}>YOUR IMAGE</tspan></text></>;
 }else if(slug==="probability-experiment"){
  const p=probability(v),shown=Math.max(1,Math.floor(v.trials*t/10)),q=probability({...v,trials:shown}),scale=400;
  content=<><text x="55" y="55" fill={blue}>LIVE FREQUENCY / {shown} TRIALS</text><path d="M80 350H580" stroke="#68778d"/><rect x="135" y={350-q.experimental*scale} width="130" height={q.experimental*scale} rx="8" fill={blue}/><rect x="380" y={350-q.theory*scale} width="130" height={q.theory*scale} rx="8" fill={amber}/><text x="200" y="382" textAnchor="middle">EXPERIMENTAL</text><text x="445" y="382" textAnchor="middle">THEORETICAL</text><text x="200" y={330-q.experimental*scale} textAnchor="middle" fill="white" fontSize="23">{(q.experimental*100).toFixed(1)}%</text><text x="445" y={330-q.theory*scale} textAnchor="middle" fill="white" fontSize="23">{(q.theory*100).toFixed(1)}%</text><text x="320" y="420" textAnchor="middle">Absolute error {(q.error*100).toFixed(1)} percentage points</text></>;
 }else if(slug==="derivative-tangent"){
  const x0=v.x,y0=functionValue(v.function,x0),d=derivative(v.function,x0),fn=Array.from({length:241},(_,i)=>{const x=-4+i/30;return[gx(x),gy(functionValue(v.function,x))] as [number,number]}).filter(p=>p[1]>15&&p[1]<425),tangent=[-5,5].map(x=>[gx(x),gy(y0+d*(x-x0))] as [number,number]);
  content=<>{grid()}<path d={line(fn)} fill="none" stroke={blue} strokeWidth="4"/><path d={line(tangent)} stroke={amber} strokeWidth="3"/><circle cx={gx(x0)} cy={gy(y0)} r="8" fill={amber}/><text x="90" y="55" fill={blue}>{["f(x)=x²","f(x)=x³","f(x)=sin(x)"][v.function]}</text><text x="90" y="390">Exact tangent slope {d.toFixed(3)} · your estimate {v.guess.toFixed(2)}</text></>;
 }else if(slug==="area-under-curve"){
  const q=riemann(v),xScale=480/(q.b-q.a),maxY=Math.max(...q.bars.map(b=>b.height),1),yScale=260/maxY;
  content=<><path d="M75 345H575M75 55V345" stroke="#71829a"/>{q.bars.map((bar,i)=><rect key={i} x={75+(bar.x-q.a)*xScale} y={345-bar.height*yScale} width={bar.width*xScale} height={bar.height*yScale} fill={blue} fillOpacity=".25" stroke={blue} strokeWidth=".7"/>)}<path d={line(Array.from({length:201},(_,i)=>{const x=q.a+(q.b-q.a)*i/200;return[75+(x-q.a)*xScale,345-q.fn(x)*yScale] as [number,number];}))} fill="none" stroke={amber} strokeWidth="4"/><text x="75" y="385">{v.rectangles} {['left','midpoint','right'][v.method]} rectangles</text><text x="575" y="385" textAnchor="end">sum {q.sum.toFixed(4)} · exact {q.exact.toFixed(4)}</text><text x="325" y="425" textAnchor="middle">absolute error {q.error.toFixed(4)}</text></>;
 }else{
  const m=matrix(v),original:[number,number][]=[[-4,-3],[4,-3],[4,3],[-4,3]],image=original.map(m.apply);
  const transformedLines=[] as [number,number][][];for(let i=-8;i<=8;i++){transformedLines.push([m.apply([i,-8]),m.apply([i,8])],[m.apply([-8,i]),m.apply([8,i])]);}
  content=<>{grid()}{transformedLines.map((l,i)=><path key={i} d={line(l.map(([x,y])=>[gx(x),gy(y)]))} stroke={i%2?"#526b8d":"#49617f"} strokeWidth="1"/>)}<polygon points={polygon(original.map(([x,y])=>[gx(x),gy(y)]))} fill="none" stroke="#8998ad" strokeDasharray="5 6"/><polygon points={polygon(image.map(([x,y])=>[gx(x),gy(y)]))} fill={blue} fillOpacity=".16" stroke={blue} strokeWidth="3"/><path d={`M325 220L${gx(v.a)} ${gy(v.c)}`} stroke={amber} strokeWidth="4" markerEnd={`url(#${id}amber)`}/><path d={`M325 220L${gx(v.b)} ${gy(v.d)}`} stroke={pink} strokeWidth="4" markerEnd={`url(#${id}pink)`}/><text x="90" y="55" fill={blue}>TRANSFORMED GRID</text><text x="90" y="390">det(A) = {m.det.toFixed(2)} · signed area scale</text></>;
 }
 return <div className="mathDiagram"><svg viewBox="0 0 650 440" role="img" aria-label={`${slug.replaceAll("-"," ")} interactive visualization`}><defs><radialGradient id={`${id}bg`}><stop stopColor="#344258"/><stop offset="1" stopColor="#1b242f"/></radialGradient>{[["blue",blue],["amber",amber],["pink",pink],["white","white"]].map(([name,color])=><marker key={name} id={`${id}${name}`} viewBox="0 0 10 10" refX="8" refY="5" markerWidth="5" markerHeight="5" orient="auto"><path d="M0 0L10 5 0 10Z" fill={color}/></marker>)}<clipPath id={`${id}clip`}><rect width="650" height="440" rx="10"/></clipPath></defs><rect width="650" height="440" fill={`url(#${id}bg)`}/><g clipPath={`url(#${id}clip)`} fill={muted} fontFamily="inherit" fontSize="13">{content}</g></svg></div>;
}
